// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: eventtypes.proto

package eventtypes

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventTypes_AllEventTypeGenerations_FullMethodName = "/Cratis.Chronicle.Contracts.EventTypes.EventTypes/AllEventTypeGenerations"
	EventTypes_AllEventTypes_FullMethodName           = "/Cratis.Chronicle.Contracts.EventTypes.EventTypes/AllEventTypes"
	EventTypes_CreateEventType_FullMethodName         = "/Cratis.Chronicle.Contracts.EventTypes.EventTypes/CreateEventType"
	EventTypes_ObserveEventTypes_FullMethodName       = "/Cratis.Chronicle.Contracts.EventTypes.EventTypes/ObserveEventTypes"
	EventTypes_RegisterEventTypes_FullMethodName      = "/Cratis.Chronicle.Contracts.EventTypes.EventTypes/RegisterEventTypes"
	EventTypes_RegisterSingleEventType_FullMethodName = "/Cratis.Chronicle.Contracts.EventTypes.EventTypes/RegisterSingleEventType"
)

// EventTypesClient is the client API for EventTypes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventTypesClient interface {
	AllEventTypeGenerations(ctx context.Context, in *AllEventTypeGenerationsRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_EventTypeDetailsResponse, error)
	AllEventTypes(ctx context.Context, in *AllEventTypesRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_EventTypeDetailsResponse, error)
	CreateEventType(ctx context.Context, in *CreateEventTypeRequest, opts ...grpc.CallOption) (*CommandResult, error)
	ObserveEventTypes(ctx context.Context, in *ObserveEventTypesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResult_IEnumerable_EventTypeDetailsResponse], error)
	RegisterEventTypes(ctx context.Context, in *RegisterEventTypesRequest, opts ...grpc.CallOption) (*CommandResult, error)
	RegisterSingleEventType(ctx context.Context, in *RegisterSingleEventTypeRequest, opts ...grpc.CallOption) (*CommandResult, error)
}

type eventTypesClient struct {
	cc grpc.ClientConnInterface
}

func NewEventTypesClient(cc grpc.ClientConnInterface) EventTypesClient {
	return &eventTypesClient{cc}
}

func (c *eventTypesClient) AllEventTypeGenerations(ctx context.Context, in *AllEventTypeGenerationsRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_EventTypeDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResult_IEnumerable_EventTypeDetailsResponse)
	err := c.cc.Invoke(ctx, EventTypes_AllEventTypeGenerations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventTypesClient) AllEventTypes(ctx context.Context, in *AllEventTypesRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_EventTypeDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResult_IEnumerable_EventTypeDetailsResponse)
	err := c.cc.Invoke(ctx, EventTypes_AllEventTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventTypesClient) CreateEventType(ctx context.Context, in *CreateEventTypeRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, EventTypes_CreateEventType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventTypesClient) ObserveEventTypes(ctx context.Context, in *ObserveEventTypesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResult_IEnumerable_EventTypeDetailsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventTypes_ServiceDesc.Streams[0], EventTypes_ObserveEventTypes_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ObserveEventTypesRequest, QueryResult_IEnumerable_EventTypeDetailsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventTypes_ObserveEventTypesClient = grpc.ServerStreamingClient[QueryResult_IEnumerable_EventTypeDetailsResponse]

func (c *eventTypesClient) RegisterEventTypes(ctx context.Context, in *RegisterEventTypesRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, EventTypes_RegisterEventTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventTypesClient) RegisterSingleEventType(ctx context.Context, in *RegisterSingleEventTypeRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, EventTypes_RegisterSingleEventType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventTypesServer is the server API for EventTypes service.
// All implementations must embed UnimplementedEventTypesServer
// for forward compatibility.
type EventTypesServer interface {
	AllEventTypeGenerations(context.Context, *AllEventTypeGenerationsRequest) (*QueryResult_IEnumerable_EventTypeDetailsResponse, error)
	AllEventTypes(context.Context, *AllEventTypesRequest) (*QueryResult_IEnumerable_EventTypeDetailsResponse, error)
	CreateEventType(context.Context, *CreateEventTypeRequest) (*CommandResult, error)
	ObserveEventTypes(*ObserveEventTypesRequest, grpc.ServerStreamingServer[QueryResult_IEnumerable_EventTypeDetailsResponse]) error
	RegisterEventTypes(context.Context, *RegisterEventTypesRequest) (*CommandResult, error)
	RegisterSingleEventType(context.Context, *RegisterSingleEventTypeRequest) (*CommandResult, error)
	mustEmbedUnimplementedEventTypesServer()
}

// UnimplementedEventTypesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventTypesServer struct{}

func (UnimplementedEventTypesServer) AllEventTypeGenerations(context.Context, *AllEventTypeGenerationsRequest) (*QueryResult_IEnumerable_EventTypeDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AllEventTypeGenerations not implemented")
}
func (UnimplementedEventTypesServer) AllEventTypes(context.Context, *AllEventTypesRequest) (*QueryResult_IEnumerable_EventTypeDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AllEventTypes not implemented")
}
func (UnimplementedEventTypesServer) CreateEventType(context.Context, *CreateEventTypeRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEventType not implemented")
}
func (UnimplementedEventTypesServer) ObserveEventTypes(*ObserveEventTypesRequest, grpc.ServerStreamingServer[QueryResult_IEnumerable_EventTypeDetailsResponse]) error {
	return status.Error(codes.Unimplemented, "method ObserveEventTypes not implemented")
}
func (UnimplementedEventTypesServer) RegisterEventTypes(context.Context, *RegisterEventTypesRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterEventTypes not implemented")
}
func (UnimplementedEventTypesServer) RegisterSingleEventType(context.Context, *RegisterSingleEventTypeRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterSingleEventType not implemented")
}
func (UnimplementedEventTypesServer) mustEmbedUnimplementedEventTypesServer() {}
func (UnimplementedEventTypesServer) testEmbeddedByValue()                    {}

// UnsafeEventTypesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventTypesServer will
// result in compilation errors.
type UnsafeEventTypesServer interface {
	mustEmbedUnimplementedEventTypesServer()
}

func RegisterEventTypesServer(s grpc.ServiceRegistrar, srv EventTypesServer) {
	// If the following call panics, it indicates UnimplementedEventTypesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventTypes_ServiceDesc, srv)
}

func _EventTypes_AllEventTypeGenerations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllEventTypeGenerationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventTypesServer).AllEventTypeGenerations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventTypes_AllEventTypeGenerations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventTypesServer).AllEventTypeGenerations(ctx, req.(*AllEventTypeGenerationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventTypes_AllEventTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllEventTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventTypesServer).AllEventTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventTypes_AllEventTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventTypesServer).AllEventTypes(ctx, req.(*AllEventTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventTypes_CreateEventType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEventTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventTypesServer).CreateEventType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventTypes_CreateEventType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventTypesServer).CreateEventType(ctx, req.(*CreateEventTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventTypes_ObserveEventTypes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ObserveEventTypesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventTypesServer).ObserveEventTypes(m, &grpc.GenericServerStream[ObserveEventTypesRequest, QueryResult_IEnumerable_EventTypeDetailsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventTypes_ObserveEventTypesServer = grpc.ServerStreamingServer[QueryResult_IEnumerable_EventTypeDetailsResponse]

func _EventTypes_RegisterEventTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterEventTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventTypesServer).RegisterEventTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventTypes_RegisterEventTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventTypesServer).RegisterEventTypes(ctx, req.(*RegisterEventTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventTypes_RegisterSingleEventType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSingleEventTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventTypesServer).RegisterSingleEventType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventTypes_RegisterSingleEventType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventTypesServer).RegisterSingleEventType(ctx, req.(*RegisterSingleEventTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventTypes_ServiceDesc is the grpc.ServiceDesc for EventTypes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventTypes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Cratis.Chronicle.Contracts.EventTypes.EventTypes",
	HandlerType: (*EventTypesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllEventTypeGenerations",
			Handler:    _EventTypes_AllEventTypeGenerations_Handler,
		},
		{
			MethodName: "AllEventTypes",
			Handler:    _EventTypes_AllEventTypes_Handler,
		},
		{
			MethodName: "CreateEventType",
			Handler:    _EventTypes_CreateEventType_Handler,
		},
		{
			MethodName: "RegisterEventTypes",
			Handler:    _EventTypes_RegisterEventTypes_Handler,
		},
		{
			MethodName: "RegisterSingleEventType",
			Handler:    _EventTypes_RegisterSingleEventType_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ObserveEventTypes",
			Handler:       _EventTypes_ObserveEventTypes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "eventtypes.proto",
}
