// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: identities.proto

package identities

import (
	bcl "github.com/cratis/chronicle.go/contracts/bcl"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidationResultSeverity int32

const (
	ValidationResultSeverity_Unknown     ValidationResultSeverity = 0
	ValidationResultSeverity_Information ValidationResultSeverity = 1
	ValidationResultSeverity_Warning     ValidationResultSeverity = 2
	ValidationResultSeverity_Error       ValidationResultSeverity = 3
)

// Enum value maps for ValidationResultSeverity.
var (
	ValidationResultSeverity_name = map[int32]string{
		0: "Unknown",
		1: "Information",
		2: "Warning",
		3: "Error",
	}
	ValidationResultSeverity_value = map[string]int32{
		"Unknown":     0,
		"Information": 1,
		"Warning":     2,
		"Error":       3,
	}
)

func (x ValidationResultSeverity) Enum() *ValidationResultSeverity {
	p := new(ValidationResultSeverity)
	*p = x
	return p
}

func (x ValidationResultSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidationResultSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_identities_proto_enumTypes[0].Descriptor()
}

func (ValidationResultSeverity) Type() protoreflect.EnumType {
	return &file_identities_proto_enumTypes[0]
}

func (x ValidationResultSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidationResultSeverity.Descriptor instead.
func (ValidationResultSeverity) EnumDescriptor() ([]byte, []int) {
	return file_identities_proto_rawDescGZIP(), []int{0}
}

type AllIdentitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventStore    string                 `protobuf:"bytes,1,opt,name=EventStore,proto3" json:"EventStore,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllIdentitiesRequest) Reset() {
	*x = AllIdentitiesRequest{}
	mi := &file_identities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllIdentitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllIdentitiesRequest) ProtoMessage() {}

func (x *AllIdentitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllIdentitiesRequest.ProtoReflect.Descriptor instead.
func (*AllIdentitiesRequest) Descriptor() ([]byte, []int) {
	return file_identities_proto_rawDescGZIP(), []int{0}
}

func (x *AllIdentitiesRequest) GetEventStore() string {
	if x != nil {
		return x.EventStore
	}
	return ""
}

func (x *AllIdentitiesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type CommandResult struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId              *bcl.Guid              `protobuf:"bytes,1,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"` // default value could not be applied: 00000000-0000-0000-0000-000000000000
	IsAuthorized               bool                   `protobuf:"varint,2,opt,name=IsAuthorized,proto3" json:"IsAuthorized,omitempty"`
	ValidationResults          []*ValidationResult    `protobuf:"bytes,3,rep,name=ValidationResults,proto3" json:"ValidationResults,omitempty"`
	ExceptionMessages          []string               `protobuf:"bytes,4,rep,name=ExceptionMessages,proto3" json:"ExceptionMessages,omitempty"`
	ExceptionStackTrace        string                 `protobuf:"bytes,5,opt,name=ExceptionStackTrace,proto3" json:"ExceptionStackTrace,omitempty"`
	AuthorizationFailureReason string                 `protobuf:"bytes,6,opt,name=AuthorizationFailureReason,proto3" json:"AuthorizationFailureReason,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_identities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_identities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_identities_proto_rawDescGZIP(), []int{1}
}

func (x *CommandResult) GetCorrelationId() *bcl.Guid {
	if x != nil {
		return x.CorrelationId
	}
	return nil
}

func (x *CommandResult) GetIsAuthorized() bool {
	if x != nil {
		return x.IsAuthorized
	}
	return false
}

func (x *CommandResult) GetValidationResults() []*ValidationResult {
	if x != nil {
		return x.ValidationResults
	}
	return nil
}

func (x *CommandResult) GetExceptionMessages() []string {
	if x != nil {
		return x.ExceptionMessages
	}
	return nil
}

func (x *CommandResult) GetExceptionStackTrace() string {
	if x != nil {
		return x.ExceptionStackTrace
	}
	return ""
}

func (x *CommandResult) GetAuthorizationFailureReason() string {
	if x != nil {
		return x.AuthorizationFailureReason
	}
	return ""
}

type GetIdentitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventStore    string                 `protobuf:"bytes,1,opt,name=EventStore,proto3" json:"EventStore,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdentitiesRequest) Reset() {
	*x = GetIdentitiesRequest{}
	mi := &file_identities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdentitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentitiesRequest) ProtoMessage() {}

func (x *GetIdentitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentitiesRequest.ProtoReflect.Descriptor instead.
func (*GetIdentitiesRequest) Descriptor() ([]byte, []int) {
	return file_identities_proto_rawDescGZIP(), []int{2}
}

func (x *GetIdentitiesRequest) GetEventStore() string {
	if x != nil {
		return x.EventStore
	}
	return ""
}

func (x *GetIdentitiesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=Subject,proto3" json:"Subject,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=UserName,proto3" json:"UserName,omitempty"`
	OnBehalfOf    *Identity              `protobuf:"bytes,4,opt,name=OnBehalfOf,proto3" json:"OnBehalfOf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_identities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_identities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_identities_proto_rawDescGZIP(), []int{3}
}

func (x *Identity) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Identity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Identity) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Identity) GetOnBehalfOf() *Identity {
	if x != nil {
		return x.OnBehalfOf
	}
	return nil
}

type IdentityDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=Subject,proto3" json:"Subject,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=UserName,proto3" json:"UserName,omitempty"`
	OnBehalfOf    *Identity              `protobuf:"bytes,4,opt,name=OnBehalfOf,proto3" json:"OnBehalfOf,omitempty"`
	Id            string                 `protobuf:"bytes,5,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityDetailsResponse) Reset() {
	*x = IdentityDetailsResponse{}
	mi := &file_identities_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityDetailsResponse) ProtoMessage() {}

func (x *IdentityDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identities_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityDetailsResponse.ProtoReflect.Descriptor instead.
func (*IdentityDetailsResponse) Descriptor() ([]byte, []int) {
	return file_identities_proto_rawDescGZIP(), []int{4}
}

func (x *IdentityDetailsResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *IdentityDetailsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IdentityDetailsResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *IdentityDetailsResponse) GetOnBehalfOf() *Identity {
	if x != nil {
		return x.OnBehalfOf
	}
	return nil
}

func (x *IdentityDetailsResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type QueryResult_IEnumerable_IdentityDetailsResponse struct {
	state               protoimpl.MessageState     `protogen:"open.v1"`
	CorrelationId       *bcl.Guid                  `protobuf:"bytes,1,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"` // default value could not be applied: 00000000-0000-0000-0000-000000000000
	IsAuthorized        bool                       `protobuf:"varint,2,opt,name=IsAuthorized,proto3" json:"IsAuthorized,omitempty"`
	ValidationResults   []*ValidationResult        `protobuf:"bytes,3,rep,name=ValidationResults,proto3" json:"ValidationResults,omitempty"`
	ExceptionMessages   []string                   `protobuf:"bytes,4,rep,name=ExceptionMessages,proto3" json:"ExceptionMessages,omitempty"`
	ExceptionStackTrace string                     `protobuf:"bytes,5,opt,name=ExceptionStackTrace,proto3" json:"ExceptionStackTrace,omitempty"`
	Data                []*IdentityDetailsResponse `protobuf:"bytes,6,rep,name=Data,proto3" json:"Data,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QueryResult_IEnumerable_IdentityDetailsResponse) Reset() {
	*x = QueryResult_IEnumerable_IdentityDetailsResponse{}
	mi := &file_identities_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult_IEnumerable_IdentityDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult_IEnumerable_IdentityDetailsResponse) ProtoMessage() {}

func (x *QueryResult_IEnumerable_IdentityDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identities_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult_IEnumerable_IdentityDetailsResponse.ProtoReflect.Descriptor instead.
func (*QueryResult_IEnumerable_IdentityDetailsResponse) Descriptor() ([]byte, []int) {
	return file_identities_proto_rawDescGZIP(), []int{5}
}

func (x *QueryResult_IEnumerable_IdentityDetailsResponse) GetCorrelationId() *bcl.Guid {
	if x != nil {
		return x.CorrelationId
	}
	return nil
}

func (x *QueryResult_IEnumerable_IdentityDetailsResponse) GetIsAuthorized() bool {
	if x != nil {
		return x.IsAuthorized
	}
	return false
}

func (x *QueryResult_IEnumerable_IdentityDetailsResponse) GetValidationResults() []*ValidationResult {
	if x != nil {
		return x.ValidationResults
	}
	return nil
}

func (x *QueryResult_IEnumerable_IdentityDetailsResponse) GetExceptionMessages() []string {
	if x != nil {
		return x.ExceptionMessages
	}
	return nil
}

func (x *QueryResult_IEnumerable_IdentityDetailsResponse) GetExceptionStackTrace() string {
	if x != nil {
		return x.ExceptionStackTrace
	}
	return ""
}

func (x *QueryResult_IEnumerable_IdentityDetailsResponse) GetData() []*IdentityDetailsResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type RenameIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventStore    string                 `protobuf:"bytes,1,opt,name=EventStore,proto3" json:"EventStore,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=Subject,proto3" json:"Subject,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameIdentityRequest) Reset() {
	*x = RenameIdentityRequest{}
	mi := &file_identities_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameIdentityRequest) ProtoMessage() {}

func (x *RenameIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identities_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameIdentityRequest.ProtoReflect.Descriptor instead.
func (*RenameIdentityRequest) Descriptor() ([]byte, []int) {
	return file_identities_proto_rawDescGZIP(), []int{6}
}

func (x *RenameIdentityRequest) GetEventStore() string {
	if x != nil {
		return x.EventStore
	}
	return ""
}

func (x *RenameIdentityRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RenameIdentityRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RenameIdentityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ValidationResult struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Severity      ValidationResultSeverity `protobuf:"varint,1,opt,name=Severity,proto3,enum=Cratis.Chronicle.Contracts.Identities.ValidationResultSeverity" json:"Severity,omitempty"` // default value could not be applied: Error
	Message       string                   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Members       []string                 `protobuf:"bytes,3,rep,name=Members,proto3" json:"Members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationResult) Reset() {
	*x = ValidationResult{}
	mi := &file_identities_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResult) ProtoMessage() {}

func (x *ValidationResult) ProtoReflect() protoreflect.Message {
	mi := &file_identities_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResult.ProtoReflect.Descriptor instead.
func (*ValidationResult) Descriptor() ([]byte, []int) {
	return file_identities_proto_rawDescGZIP(), []int{7}
}

func (x *ValidationResult) GetSeverity() ValidationResultSeverity {
	if x != nil {
		return x.Severity
	}
	return ValidationResultSeverity_Unknown
}

func (x *ValidationResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationResult) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_identities_proto protoreflect.FileDescriptor

const file_identities_proto_rawDesc = "" +
	"\n" +
	"\x10identities.proto\x12%Cratis.Chronicle.Contracts.Identities\x1a\x16protobuf-net/bcl.proto\"T\n" +
	"\x14AllIdentitiesRequest\x12\x1e\n" +
	"\n" +
	"EventStore\x18\x01 \x01(\tR\n" +
	"EventStore\x12\x1c\n" +
	"\tNamespace\x18\x02 \x01(\tR\tNamespace\"\xeb\x02\n" +
	"\rCommandResult\x12/\n" +
	"\rCorrelationId\x18\x01 \x01(\v2\t.bcl.GuidR\rCorrelationId\x12\"\n" +
	"\fIsAuthorized\x18\x02 \x01(\bR\fIsAuthorized\x12e\n" +
	"\x11ValidationResults\x18\x03 \x03(\v27.Cratis.Chronicle.Contracts.Identities.ValidationResultR\x11ValidationResults\x12,\n" +
	"\x11ExceptionMessages\x18\x04 \x03(\tR\x11ExceptionMessages\x120\n" +
	"\x13ExceptionStackTrace\x18\x05 \x01(\tR\x13ExceptionStackTrace\x12>\n" +
	"\x1aAuthorizationFailureReason\x18\x06 \x01(\tR\x1aAuthorizationFailureReason\"T\n" +
	"\x14GetIdentitiesRequest\x12\x1e\n" +
	"\n" +
	"EventStore\x18\x01 \x01(\tR\n" +
	"EventStore\x12\x1c\n" +
	"\tNamespace\x18\x02 \x01(\tR\tNamespace\"\xa5\x01\n" +
	"\bIdentity\x12\x18\n" +
	"\aSubject\x18\x01 \x01(\tR\aSubject\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1a\n" +
	"\bUserName\x18\x03 \x01(\tR\bUserName\x12O\n" +
	"\n" +
	"OnBehalfOf\x18\x04 \x01(\v2/.Cratis.Chronicle.Contracts.Identities.IdentityR\n" +
	"OnBehalfOf\"\xc4\x01\n" +
	"\x17IdentityDetailsResponse\x12\x18\n" +
	"\aSubject\x18\x01 \x01(\tR\aSubject\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1a\n" +
	"\bUserName\x18\x03 \x01(\tR\bUserName\x12O\n" +
	"\n" +
	"OnBehalfOf\x18\x04 \x01(\v2/.Cratis.Chronicle.Contracts.Identities.IdentityR\n" +
	"OnBehalfOf\x12\x0e\n" +
	"\x02Id\x18\x05 \x01(\tR\x02Id\"\xa1\x03\n" +
	"/QueryResult_IEnumerable_IdentityDetailsResponse\x12/\n" +
	"\rCorrelationId\x18\x01 \x01(\v2\t.bcl.GuidR\rCorrelationId\x12\"\n" +
	"\fIsAuthorized\x18\x02 \x01(\bR\fIsAuthorized\x12e\n" +
	"\x11ValidationResults\x18\x03 \x03(\v27.Cratis.Chronicle.Contracts.Identities.ValidationResultR\x11ValidationResults\x12,\n" +
	"\x11ExceptionMessages\x18\x04 \x03(\tR\x11ExceptionMessages\x120\n" +
	"\x13ExceptionStackTrace\x18\x05 \x01(\tR\x13ExceptionStackTrace\x12R\n" +
	"\x04Data\x18\x06 \x03(\v2>.Cratis.Chronicle.Contracts.Identities.IdentityDetailsResponseR\x04Data\"\x83\x01\n" +
	"\x15RenameIdentityRequest\x12\x1e\n" +
	"\n" +
	"EventStore\x18\x01 \x01(\tR\n" +
	"EventStore\x12\x1c\n" +
	"\tNamespace\x18\x02 \x01(\tR\tNamespace\x12\x18\n" +
	"\aSubject\x18\x03 \x01(\tR\aSubject\x12\x12\n" +
	"\x04Name\x18\x04 \x01(\tR\x04Name\"\xa3\x01\n" +
	"\x10ValidationResult\x12[\n" +
	"\bSeverity\x18\x01 \x01(\x0e2?.Cratis.Chronicle.Contracts.Identities.ValidationResultSeverityR\bSeverity\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\x12\x18\n" +
	"\aMembers\x18\x03 \x03(\tR\aMembers*P\n" +
	"\x18ValidationResultSeverity\x12\v\n" +
	"\aUnknown\x10\x00\x12\x0f\n" +
	"\vInformation\x10\x01\x12\v\n" +
	"\aWarning\x10\x02\x12\t\n" +
	"\x05Error\x10\x032\xe3\x03\n" +
	"\n" +
	"Identities\x12\xa6\x01\n" +
	"\rAllIdentities\x12;.Cratis.Chronicle.Contracts.Identities.AllIdentitiesRequest\x1aV.Cratis.Chronicle.Contracts.Identities.QueryResult_IEnumerable_IdentityDetailsResponse0\x01\x12\xa4\x01\n" +
	"\rGetIdentities\x12;.Cratis.Chronicle.Contracts.Identities.GetIdentitiesRequest\x1aV.Cratis.Chronicle.Contracts.Identities.QueryResult_IEnumerable_IdentityDetailsResponse\x12\x84\x01\n" +
	"\x0eRenameIdentity\x12<.Cratis.Chronicle.Contracts.Identities.RenameIdentityRequest\x1a4.Cratis.Chronicle.Contracts.Identities.CommandResultB\xa9\x02\n" +
	")com.Cratis.Chronicle.Contracts.IdentitiesB\x0fIdentitiesProtoP\x01Z3github.com/cratis/chronicle.go/contracts/identities\xa2\x02\x04CCCI\xaa\x02%Cratis.Chronicle.Contracts.Identities\xca\x02%Cratis\\Chronicle\\Contracts\\Identities\xe2\x021Cratis\\Chronicle\\Contracts\\Identities\\GPBMetadata\xea\x02(Cratis::Chronicle::Contracts::Identitiesb\x06proto3"

var (
	file_identities_proto_rawDescOnce sync.Once
	file_identities_proto_rawDescData []byte
)

func file_identities_proto_rawDescGZIP() []byte {
	file_identities_proto_rawDescOnce.Do(func() {
		file_identities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identities_proto_rawDesc), len(file_identities_proto_rawDesc)))
	})
	return file_identities_proto_rawDescData
}

var file_identities_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_identities_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_identities_proto_goTypes = []any{
	(ValidationResultSeverity)(0),                           // 0: Cratis.Chronicle.Contracts.Identities.ValidationResultSeverity
	(*AllIdentitiesRequest)(nil),                            // 1: Cratis.Chronicle.Contracts.Identities.AllIdentitiesRequest
	(*CommandResult)(nil),                                   // 2: Cratis.Chronicle.Contracts.Identities.CommandResult
	(*GetIdentitiesRequest)(nil),                            // 3: Cratis.Chronicle.Contracts.Identities.GetIdentitiesRequest
	(*Identity)(nil),                                        // 4: Cratis.Chronicle.Contracts.Identities.Identity
	(*IdentityDetailsResponse)(nil),                         // 5: Cratis.Chronicle.Contracts.Identities.IdentityDetailsResponse
	(*QueryResult_IEnumerable_IdentityDetailsResponse)(nil), // 6: Cratis.Chronicle.Contracts.Identities.QueryResult_IEnumerable_IdentityDetailsResponse
	(*RenameIdentityRequest)(nil),                           // 7: Cratis.Chronicle.Contracts.Identities.RenameIdentityRequest
	(*ValidationResult)(nil),                                // 8: Cratis.Chronicle.Contracts.Identities.ValidationResult
	(*bcl.Guid)(nil),                                        // 9: bcl.Guid
}
var file_identities_proto_depIdxs = []int32{
	9,  // 0: Cratis.Chronicle.Contracts.Identities.CommandResult.CorrelationId:type_name -> bcl.Guid
	8,  // 1: Cratis.Chronicle.Contracts.Identities.CommandResult.ValidationResults:type_name -> Cratis.Chronicle.Contracts.Identities.ValidationResult
	4,  // 2: Cratis.Chronicle.Contracts.Identities.Identity.OnBehalfOf:type_name -> Cratis.Chronicle.Contracts.Identities.Identity
	4,  // 3: Cratis.Chronicle.Contracts.Identities.IdentityDetailsResponse.OnBehalfOf:type_name -> Cratis.Chronicle.Contracts.Identities.Identity
	9,  // 4: Cratis.Chronicle.Contracts.Identities.QueryResult_IEnumerable_IdentityDetailsResponse.CorrelationId:type_name -> bcl.Guid
	8,  // 5: Cratis.Chronicle.Contracts.Identities.QueryResult_IEnumerable_IdentityDetailsResponse.ValidationResults:type_name -> Cratis.Chronicle.Contracts.Identities.ValidationResult
	5,  // 6: Cratis.Chronicle.Contracts.Identities.QueryResult_IEnumerable_IdentityDetailsResponse.Data:type_name -> Cratis.Chronicle.Contracts.Identities.IdentityDetailsResponse
	0,  // 7: Cratis.Chronicle.Contracts.Identities.ValidationResult.Severity:type_name -> Cratis.Chronicle.Contracts.Identities.ValidationResultSeverity
	1,  // 8: Cratis.Chronicle.Contracts.Identities.Identities.AllIdentities:input_type -> Cratis.Chronicle.Contracts.Identities.AllIdentitiesRequest
	3,  // 9: Cratis.Chronicle.Contracts.Identities.Identities.GetIdentities:input_type -> Cratis.Chronicle.Contracts.Identities.GetIdentitiesRequest
	7,  // 10: Cratis.Chronicle.Contracts.Identities.Identities.RenameIdentity:input_type -> Cratis.Chronicle.Contracts.Identities.RenameIdentityRequest
	6,  // 11: Cratis.Chronicle.Contracts.Identities.Identities.AllIdentities:output_type -> Cratis.Chronicle.Contracts.Identities.QueryResult_IEnumerable_IdentityDetailsResponse
	6,  // 12: Cratis.Chronicle.Contracts.Identities.Identities.GetIdentities:output_type -> Cratis.Chronicle.Contracts.Identities.QueryResult_IEnumerable_IdentityDetailsResponse
	2,  // 13: Cratis.Chronicle.Contracts.Identities.Identities.RenameIdentity:output_type -> Cratis.Chronicle.Contracts.Identities.CommandResult
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_identities_proto_init() }
func file_identities_proto_init() {
	if File_identities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identities_proto_rawDesc), len(file_identities_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identities_proto_goTypes,
		DependencyIndexes: file_identities_proto_depIdxs,
		EnumInfos:         file_identities_proto_enumTypes,
		MessageInfos:      file_identities_proto_msgTypes,
	}.Build()
	File_identities_proto = out.File
	file_identities_proto_goTypes = nil
	file_identities_proto_depIdxs = nil
}
