// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: identities.proto

package identities

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Identities_AllIdentities_FullMethodName  = "/Cratis.Chronicle.Contracts.Identities.Identities/AllIdentities"
	Identities_GetIdentities_FullMethodName  = "/Cratis.Chronicle.Contracts.Identities.Identities/GetIdentities"
	Identities_RenameIdentity_FullMethodName = "/Cratis.Chronicle.Contracts.Identities.Identities/RenameIdentity"
)

// IdentitiesClient is the client API for Identities service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentitiesClient interface {
	AllIdentities(ctx context.Context, in *AllIdentitiesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResult_IEnumerable_IdentityDetailsResponse], error)
	GetIdentities(ctx context.Context, in *GetIdentitiesRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_IdentityDetailsResponse, error)
	RenameIdentity(ctx context.Context, in *RenameIdentityRequest, opts ...grpc.CallOption) (*CommandResult, error)
}

type identitiesClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentitiesClient(cc grpc.ClientConnInterface) IdentitiesClient {
	return &identitiesClient{cc}
}

func (c *identitiesClient) AllIdentities(ctx context.Context, in *AllIdentitiesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResult_IEnumerable_IdentityDetailsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Identities_ServiceDesc.Streams[0], Identities_AllIdentities_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AllIdentitiesRequest, QueryResult_IEnumerable_IdentityDetailsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Identities_AllIdentitiesClient = grpc.ServerStreamingClient[QueryResult_IEnumerable_IdentityDetailsResponse]

func (c *identitiesClient) GetIdentities(ctx context.Context, in *GetIdentitiesRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_IdentityDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResult_IEnumerable_IdentityDetailsResponse)
	err := c.cc.Invoke(ctx, Identities_GetIdentities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identitiesClient) RenameIdentity(ctx context.Context, in *RenameIdentityRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, Identities_RenameIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentitiesServer is the server API for Identities service.
// All implementations must embed UnimplementedIdentitiesServer
// for forward compatibility.
type IdentitiesServer interface {
	AllIdentities(*AllIdentitiesRequest, grpc.ServerStreamingServer[QueryResult_IEnumerable_IdentityDetailsResponse]) error
	GetIdentities(context.Context, *GetIdentitiesRequest) (*QueryResult_IEnumerable_IdentityDetailsResponse, error)
	RenameIdentity(context.Context, *RenameIdentityRequest) (*CommandResult, error)
	mustEmbedUnimplementedIdentitiesServer()
}

// UnimplementedIdentitiesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentitiesServer struct{}

func (UnimplementedIdentitiesServer) AllIdentities(*AllIdentitiesRequest, grpc.ServerStreamingServer[QueryResult_IEnumerable_IdentityDetailsResponse]) error {
	return status.Error(codes.Unimplemented, "method AllIdentities not implemented")
}
func (UnimplementedIdentitiesServer) GetIdentities(context.Context, *GetIdentitiesRequest) (*QueryResult_IEnumerable_IdentityDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIdentities not implemented")
}
func (UnimplementedIdentitiesServer) RenameIdentity(context.Context, *RenameIdentityRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameIdentity not implemented")
}
func (UnimplementedIdentitiesServer) mustEmbedUnimplementedIdentitiesServer() {}
func (UnimplementedIdentitiesServer) testEmbeddedByValue()                    {}

// UnsafeIdentitiesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentitiesServer will
// result in compilation errors.
type UnsafeIdentitiesServer interface {
	mustEmbedUnimplementedIdentitiesServer()
}

func RegisterIdentitiesServer(s grpc.ServiceRegistrar, srv IdentitiesServer) {
	// If the following call panics, it indicates UnimplementedIdentitiesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Identities_ServiceDesc, srv)
}

func _Identities_AllIdentities_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AllIdentitiesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IdentitiesServer).AllIdentities(m, &grpc.GenericServerStream[AllIdentitiesRequest, QueryResult_IEnumerable_IdentityDetailsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Identities_AllIdentitiesServer = grpc.ServerStreamingServer[QueryResult_IEnumerable_IdentityDetailsResponse]

func _Identities_GetIdentities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdentitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentitiesServer).GetIdentities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identities_GetIdentities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentitiesServer).GetIdentities(ctx, req.(*GetIdentitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identities_RenameIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentitiesServer).RenameIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Identities_RenameIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentitiesServer).RenameIdentity(ctx, req.(*RenameIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Identities_ServiceDesc is the grpc.ServiceDesc for Identities service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Identities_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Cratis.Chronicle.Contracts.Identities.Identities",
	HandlerType: (*IdentitiesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIdentities",
			Handler:    _Identities_GetIdentities_Handler,
		},
		{
			MethodName: "RenameIdentity",
			Handler:    _Identities_RenameIdentity_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AllIdentities",
			Handler:       _Identities_AllIdentities_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "identities.proto",
}
