// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: observation_webhooks.proto

package webhooks

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Webhooks_AddWebhook_FullMethodName      = "/Cratis.Chronicle.Contracts.Observation.Webhooks.Webhooks/AddWebhook"
	Webhooks_AddWebhooks_FullMethodName     = "/Cratis.Chronicle.Contracts.Observation.Webhooks.Webhooks/AddWebhooks"
	Webhooks_GetWebhooks_FullMethodName     = "/Cratis.Chronicle.Contracts.Observation.Webhooks.Webhooks/GetWebhooks"
	Webhooks_ObserveWebhooks_FullMethodName = "/Cratis.Chronicle.Contracts.Observation.Webhooks.Webhooks/ObserveWebhooks"
	Webhooks_RemoveWebhook_FullMethodName   = "/Cratis.Chronicle.Contracts.Observation.Webhooks.Webhooks/RemoveWebhook"
	Webhooks_RemoveWebhooks_FullMethodName  = "/Cratis.Chronicle.Contracts.Observation.Webhooks.Webhooks/RemoveWebhooks"
)

// WebhooksClient is the client API for Webhooks service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebhooksClient interface {
	AddWebhook(ctx context.Context, in *AddWebhookRequest, opts ...grpc.CallOption) (*CommandResult, error)
	AddWebhooks(ctx context.Context, in *AddWebhooksRequest, opts ...grpc.CallOption) (*CommandResult, error)
	GetWebhooks(ctx context.Context, in *GetWebhooksRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_WebhookDetailsResponse, error)
	ObserveWebhooks(ctx context.Context, in *ObserveWebhooksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResult_IEnumerable_WebhookDetailsResponse], error)
	RemoveWebhook(ctx context.Context, in *RemoveWebhookRequest, opts ...grpc.CallOption) (*CommandResult, error)
	RemoveWebhooks(ctx context.Context, in *RemoveWebhooksRequest, opts ...grpc.CallOption) (*CommandResult, error)
}

type webhooksClient struct {
	cc grpc.ClientConnInterface
}

func NewWebhooksClient(cc grpc.ClientConnInterface) WebhooksClient {
	return &webhooksClient{cc}
}

func (c *webhooksClient) AddWebhook(ctx context.Context, in *AddWebhookRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, Webhooks_AddWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhooksClient) AddWebhooks(ctx context.Context, in *AddWebhooksRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, Webhooks_AddWebhooks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhooksClient) GetWebhooks(ctx context.Context, in *GetWebhooksRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_WebhookDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResult_IEnumerable_WebhookDetailsResponse)
	err := c.cc.Invoke(ctx, Webhooks_GetWebhooks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhooksClient) ObserveWebhooks(ctx context.Context, in *ObserveWebhooksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResult_IEnumerable_WebhookDetailsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Webhooks_ServiceDesc.Streams[0], Webhooks_ObserveWebhooks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ObserveWebhooksRequest, QueryResult_IEnumerable_WebhookDetailsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Webhooks_ObserveWebhooksClient = grpc.ServerStreamingClient[QueryResult_IEnumerable_WebhookDetailsResponse]

func (c *webhooksClient) RemoveWebhook(ctx context.Context, in *RemoveWebhookRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, Webhooks_RemoveWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhooksClient) RemoveWebhooks(ctx context.Context, in *RemoveWebhooksRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, Webhooks_RemoveWebhooks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebhooksServer is the server API for Webhooks service.
// All implementations must embed UnimplementedWebhooksServer
// for forward compatibility.
type WebhooksServer interface {
	AddWebhook(context.Context, *AddWebhookRequest) (*CommandResult, error)
	AddWebhooks(context.Context, *AddWebhooksRequest) (*CommandResult, error)
	GetWebhooks(context.Context, *GetWebhooksRequest) (*QueryResult_IEnumerable_WebhookDetailsResponse, error)
	ObserveWebhooks(*ObserveWebhooksRequest, grpc.ServerStreamingServer[QueryResult_IEnumerable_WebhookDetailsResponse]) error
	RemoveWebhook(context.Context, *RemoveWebhookRequest) (*CommandResult, error)
	RemoveWebhooks(context.Context, *RemoveWebhooksRequest) (*CommandResult, error)
	mustEmbedUnimplementedWebhooksServer()
}

// UnimplementedWebhooksServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebhooksServer struct{}

func (UnimplementedWebhooksServer) AddWebhook(context.Context, *AddWebhookRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method AddWebhook not implemented")
}
func (UnimplementedWebhooksServer) AddWebhooks(context.Context, *AddWebhooksRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method AddWebhooks not implemented")
}
func (UnimplementedWebhooksServer) GetWebhooks(context.Context, *GetWebhooksRequest) (*QueryResult_IEnumerable_WebhookDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWebhooks not implemented")
}
func (UnimplementedWebhooksServer) ObserveWebhooks(*ObserveWebhooksRequest, grpc.ServerStreamingServer[QueryResult_IEnumerable_WebhookDetailsResponse]) error {
	return status.Error(codes.Unimplemented, "method ObserveWebhooks not implemented")
}
func (UnimplementedWebhooksServer) RemoveWebhook(context.Context, *RemoveWebhookRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveWebhook not implemented")
}
func (UnimplementedWebhooksServer) RemoveWebhooks(context.Context, *RemoveWebhooksRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveWebhooks not implemented")
}
func (UnimplementedWebhooksServer) mustEmbedUnimplementedWebhooksServer() {}
func (UnimplementedWebhooksServer) testEmbeddedByValue()                  {}

// UnsafeWebhooksServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebhooksServer will
// result in compilation errors.
type UnsafeWebhooksServer interface {
	mustEmbedUnimplementedWebhooksServer()
}

func RegisterWebhooksServer(s grpc.ServiceRegistrar, srv WebhooksServer) {
	// If the following call panics, it indicates UnimplementedWebhooksServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Webhooks_ServiceDesc, srv)
}

func _Webhooks_AddWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhooksServer).AddWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Webhooks_AddWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhooksServer).AddWebhook(ctx, req.(*AddWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Webhooks_AddWebhooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWebhooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhooksServer).AddWebhooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Webhooks_AddWebhooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhooksServer).AddWebhooks(ctx, req.(*AddWebhooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Webhooks_GetWebhooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWebhooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhooksServer).GetWebhooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Webhooks_GetWebhooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhooksServer).GetWebhooks(ctx, req.(*GetWebhooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Webhooks_ObserveWebhooks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ObserveWebhooksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WebhooksServer).ObserveWebhooks(m, &grpc.GenericServerStream[ObserveWebhooksRequest, QueryResult_IEnumerable_WebhookDetailsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Webhooks_ObserveWebhooksServer = grpc.ServerStreamingServer[QueryResult_IEnumerable_WebhookDetailsResponse]

func _Webhooks_RemoveWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhooksServer).RemoveWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Webhooks_RemoveWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhooksServer).RemoveWebhook(ctx, req.(*RemoveWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Webhooks_RemoveWebhooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveWebhooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhooksServer).RemoveWebhooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Webhooks_RemoveWebhooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhooksServer).RemoveWebhooks(ctx, req.(*RemoveWebhooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Webhooks_ServiceDesc is the grpc.ServiceDesc for Webhooks service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Webhooks_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Cratis.Chronicle.Contracts.Observation.Webhooks.Webhooks",
	HandlerType: (*WebhooksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddWebhook",
			Handler:    _Webhooks_AddWebhook_Handler,
		},
		{
			MethodName: "AddWebhooks",
			Handler:    _Webhooks_AddWebhooks_Handler,
		},
		{
			MethodName: "GetWebhooks",
			Handler:    _Webhooks_GetWebhooks_Handler,
		},
		{
			MethodName: "RemoveWebhook",
			Handler:    _Webhooks_RemoveWebhook_Handler,
		},
		{
			MethodName: "RemoveWebhooks",
			Handler:    _Webhooks_RemoveWebhooks_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ObserveWebhooks",
			Handler:       _Webhooks_ObserveWebhooks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "observation_webhooks.proto",
}
