// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: alerts.proto

package alerts

import (
	bcl "github.com/cratis/chronicle.go/contracts/bcl"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlertIncidentsReadinessState int32

const (
	AlertIncidentsReadinessState_CatchingUp AlertIncidentsReadinessState = 0
	AlertIncidentsReadinessState_Ready      AlertIncidentsReadinessState = 1
	AlertIncidentsReadinessState_Degraded   AlertIncidentsReadinessState = 2
)

// Enum value maps for AlertIncidentsReadinessState.
var (
	AlertIncidentsReadinessState_name = map[int32]string{
		0: "CatchingUp",
		1: "Ready",
		2: "Degraded",
	}
	AlertIncidentsReadinessState_value = map[string]int32{
		"CatchingUp": 0,
		"Ready":      1,
		"Degraded":   2,
	}
)

func (x AlertIncidentsReadinessState) Enum() *AlertIncidentsReadinessState {
	p := new(AlertIncidentsReadinessState)
	*p = x
	return p
}

func (x AlertIncidentsReadinessState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertIncidentsReadinessState) Descriptor() protoreflect.EnumDescriptor {
	return file_alerts_proto_enumTypes[0].Descriptor()
}

func (AlertIncidentsReadinessState) Type() protoreflect.EnumType {
	return &file_alerts_proto_enumTypes[0]
}

func (x AlertIncidentsReadinessState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertIncidentsReadinessState.Descriptor instead.
func (AlertIncidentsReadinessState) EnumDescriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{0}
}

type AlertSeverity int32

const (
	AlertSeverity_ALERT_SEVERITY_Warning AlertSeverity = 0
	AlertSeverity_Critical               AlertSeverity = 1
)

// Enum value maps for AlertSeverity.
var (
	AlertSeverity_name = map[int32]string{
		0: "ALERT_SEVERITY_Warning",
		1: "Critical",
	}
	AlertSeverity_value = map[string]int32{
		"ALERT_SEVERITY_Warning": 0,
		"Critical":               1,
	}
)

func (x AlertSeverity) Enum() *AlertSeverity {
	p := new(AlertSeverity)
	*p = x
	return p
}

func (x AlertSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_alerts_proto_enumTypes[1].Descriptor()
}

func (AlertSeverity) Type() protoreflect.EnumType {
	return &file_alerts_proto_enumTypes[1]
}

func (x AlertSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertSeverity.Descriptor instead.
func (AlertSeverity) EnumDescriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{1}
}

type FailureKind int32

const (
	FailureKind_FAILURE_KIND_Unknown FailureKind = 0
	FailureKind_Handling             FailureKind = 1
	FailureKind_Timeout              FailureKind = 2
	FailureKind_Disconnected         FailureKind = 3
)

// Enum value maps for FailureKind.
var (
	FailureKind_name = map[int32]string{
		0: "FAILURE_KIND_Unknown",
		1: "Handling",
		2: "Timeout",
		3: "Disconnected",
	}
	FailureKind_value = map[string]int32{
		"FAILURE_KIND_Unknown": 0,
		"Handling":             1,
		"Timeout":              2,
		"Disconnected":         3,
	}
)

func (x FailureKind) Enum() *FailureKind {
	p := new(FailureKind)
	*p = x
	return p
}

func (x FailureKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureKind) Descriptor() protoreflect.EnumDescriptor {
	return file_alerts_proto_enumTypes[2].Descriptor()
}

func (FailureKind) Type() protoreflect.EnumType {
	return &file_alerts_proto_enumTypes[2]
}

func (x FailureKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureKind.Descriptor instead.
func (FailureKind) EnumDescriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{2}
}

type ValidationResultSeverity int32

const (
	ValidationResultSeverity_VALIDATION_RESULT_SEVERITY_Unknown ValidationResultSeverity = 0
	ValidationResultSeverity_Information                        ValidationResultSeverity = 1
	ValidationResultSeverity_VALIDATION_RESULT_SEVERITY_Warning ValidationResultSeverity = 2
	ValidationResultSeverity_Error                              ValidationResultSeverity = 3
)

// Enum value maps for ValidationResultSeverity.
var (
	ValidationResultSeverity_name = map[int32]string{
		0: "VALIDATION_RESULT_SEVERITY_Unknown",
		1: "Information",
		2: "VALIDATION_RESULT_SEVERITY_Warning",
		3: "Error",
	}
	ValidationResultSeverity_value = map[string]int32{
		"VALIDATION_RESULT_SEVERITY_Unknown": 0,
		"Information":                        1,
		"VALIDATION_RESULT_SEVERITY_Warning": 2,
		"Error":                              3,
	}
)

func (x ValidationResultSeverity) Enum() *ValidationResultSeverity {
	p := new(ValidationResultSeverity)
	*p = x
	return p
}

func (x ValidationResultSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidationResultSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_alerts_proto_enumTypes[3].Descriptor()
}

func (ValidationResultSeverity) Type() protoreflect.EnumType {
	return &file_alerts_proto_enumTypes[3]
}

func (x ValidationResultSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidationResultSeverity.Descriptor instead.
func (ValidationResultSeverity) EnumDescriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{3}
}

type AlertEvidence struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	AttemptCount  int32                       `protobuf:"varint,1,opt,name=AttemptCount,proto3" json:"AttemptCount,omitempty"`
	FirstFailure  *SerializableDateTimeOffset `protobuf:"bytes,2,opt,name=FirstFailure,proto3" json:"FirstFailure,omitempty"`
	LastFailure   *SerializableDateTimeOffset `protobuf:"bytes,3,opt,name=LastFailure,proto3" json:"LastFailure,omitempty"`
	FailureKind   FailureKind                 `protobuf:"varint,4,opt,name=FailureKind,proto3,enum=Cratis.Chronicle.Contracts.Alerts.FailureKind" json:"FailureKind,omitempty"`
	Message       string                      `protobuf:"bytes,5,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertEvidence) Reset() {
	*x = AlertEvidence{}
	mi := &file_alerts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertEvidence) ProtoMessage() {}

func (x *AlertEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertEvidence.ProtoReflect.Descriptor instead.
func (*AlertEvidence) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{0}
}

func (x *AlertEvidence) GetAttemptCount() int32 {
	if x != nil {
		return x.AttemptCount
	}
	return 0
}

func (x *AlertEvidence) GetFirstFailure() *SerializableDateTimeOffset {
	if x != nil {
		return x.FirstFailure
	}
	return nil
}

func (x *AlertEvidence) GetLastFailure() *SerializableDateTimeOffset {
	if x != nil {
		return x.LastFailure
	}
	return nil
}

func (x *AlertEvidence) GetFailureKind() FailureKind {
	if x != nil {
		return x.FailureKind
	}
	return FailureKind_FAILURE_KIND_Unknown
}

func (x *AlertEvidence) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AlertIncidentContinuation struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RaisedSequenceNumber uint64                 `protobuf:"varint,1,opt,name=RaisedSequenceNumber,proto3" json:"RaisedSequenceNumber,omitempty"`
	IncidentId           *bcl.Guid              `protobuf:"bytes,2,opt,name=IncidentId,proto3" json:"IncidentId,omitempty"` // default value could not be applied: 00000000-0000-0000-0000-000000000000
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AlertIncidentContinuation) Reset() {
	*x = AlertIncidentContinuation{}
	mi := &file_alerts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertIncidentContinuation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertIncidentContinuation) ProtoMessage() {}

func (x *AlertIncidentContinuation) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertIncidentContinuation.ProtoReflect.Descriptor instead.
func (*AlertIncidentContinuation) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{1}
}

func (x *AlertIncidentContinuation) GetRaisedSequenceNumber() uint64 {
	if x != nil {
		return x.RaisedSequenceNumber
	}
	return 0
}

func (x *AlertIncidentContinuation) GetIncidentId() *bcl.Guid {
	if x != nil {
		return x.IncidentId
	}
	return nil
}

type AlertIncidentCountDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	Condition     string                 `protobuf:"bytes,2,opt,name=Condition,proto3" json:"Condition,omitempty"`
	Severity      AlertSeverity          `protobuf:"varint,3,opt,name=Severity,proto3,enum=Cratis.Chronicle.Contracts.Alerts.AlertSeverity" json:"Severity,omitempty"`
	Count         int64                  `protobuf:"varint,4,opt,name=Count,proto3" json:"Count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertIncidentCountDetails) Reset() {
	*x = AlertIncidentCountDetails{}
	mi := &file_alerts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertIncidentCountDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertIncidentCountDetails) ProtoMessage() {}

func (x *AlertIncidentCountDetails) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertIncidentCountDetails.ProtoReflect.Descriptor instead.
func (*AlertIncidentCountDetails) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{2}
}

func (x *AlertIncidentCountDetails) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AlertIncidentCountDetails) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *AlertIncidentCountDetails) GetSeverity() AlertSeverity {
	if x != nil {
		return x.Severity
	}
	return AlertSeverity_ALERT_SEVERITY_Warning
}

func (x *AlertIncidentCountDetails) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type AlertIncidentDetails struct {
	state                        protoimpl.MessageState      `protogen:"open.v1"`
	Id                           *bcl.Guid                   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"` // default value could not be applied: 00000000-0000-0000-0000-000000000000
	Target                       *AlertTarget                `protobuf:"bytes,2,opt,name=Target,proto3" json:"Target,omitempty"`
	Condition                    string                      `protobuf:"bytes,3,opt,name=Condition,proto3" json:"Condition,omitempty"`
	Severity                     AlertSeverity               `protobuf:"varint,4,opt,name=Severity,proto3,enum=Cratis.Chronicle.Contracts.Alerts.AlertSeverity" json:"Severity,omitempty"`
	Evidence                     *AlertEvidence              `protobuf:"bytes,5,opt,name=Evidence,proto3" json:"Evidence,omitempty"`
	RaisedAt                     *SerializableDateTimeOffset `protobuf:"bytes,6,opt,name=RaisedAt,proto3" json:"RaisedAt,omitempty"`
	LastChangedAt                *SerializableDateTimeOffset `protobuf:"bytes,7,opt,name=LastChangedAt,proto3" json:"LastChangedAt,omitempty"`
	RaisedSequenceNumber         uint64                      `protobuf:"varint,8,opt,name=RaisedSequenceNumber,proto3" json:"RaisedSequenceNumber,omitempty"`
	LastTransitionSequenceNumber uint64                      `protobuf:"varint,9,opt,name=LastTransitionSequenceNumber,proto3" json:"LastTransitionSequenceNumber,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *AlertIncidentDetails) Reset() {
	*x = AlertIncidentDetails{}
	mi := &file_alerts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertIncidentDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertIncidentDetails) ProtoMessage() {}

func (x *AlertIncidentDetails) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertIncidentDetails.ProtoReflect.Descriptor instead.
func (*AlertIncidentDetails) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{3}
}

func (x *AlertIncidentDetails) GetId() *bcl.Guid {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *AlertIncidentDetails) GetTarget() *AlertTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *AlertIncidentDetails) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *AlertIncidentDetails) GetSeverity() AlertSeverity {
	if x != nil {
		return x.Severity
	}
	return AlertSeverity_ALERT_SEVERITY_Warning
}

func (x *AlertIncidentDetails) GetEvidence() *AlertEvidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *AlertIncidentDetails) GetRaisedAt() *SerializableDateTimeOffset {
	if x != nil {
		return x.RaisedAt
	}
	return nil
}

func (x *AlertIncidentDetails) GetLastChangedAt() *SerializableDateTimeOffset {
	if x != nil {
		return x.LastChangedAt
	}
	return nil
}

func (x *AlertIncidentDetails) GetRaisedSequenceNumber() uint64 {
	if x != nil {
		return x.RaisedSequenceNumber
	}
	return 0
}

func (x *AlertIncidentDetails) GetLastTransitionSequenceNumber() uint64 {
	if x != nil {
		return x.LastTransitionSequenceNumber
	}
	return 0
}

type AlertIncidentLookupResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Status        AlertIncidentsReadinessState `protobuf:"varint,1,opt,name=Status,proto3,enum=Cratis.Chronicle.Contracts.Alerts.AlertIncidentsReadinessState" json:"Status,omitempty"`
	Incident      *AlertIncidentDetails        `protobuf:"bytes,2,opt,name=Incident,proto3" json:"Incident,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertIncidentLookupResponse) Reset() {
	*x = AlertIncidentLookupResponse{}
	mi := &file_alerts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertIncidentLookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertIncidentLookupResponse) ProtoMessage() {}

func (x *AlertIncidentLookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertIncidentLookupResponse.ProtoReflect.Descriptor instead.
func (*AlertIncidentLookupResponse) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{4}
}

func (x *AlertIncidentLookupResponse) GetStatus() AlertIncidentsReadinessState {
	if x != nil {
		return x.Status
	}
	return AlertIncidentsReadinessState_CatchingUp
}

func (x *AlertIncidentLookupResponse) GetIncident() *AlertIncidentDetails {
	if x != nil {
		return x.Incident
	}
	return nil
}

type AlertIncidentPageResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Status        AlertIncidentsReadinessState `protobuf:"varint,1,opt,name=Status,proto3,enum=Cratis.Chronicle.Contracts.Alerts.AlertIncidentsReadinessState" json:"Status,omitempty"`
	Items         []*AlertIncidentDetails      `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
	Next          *AlertIncidentContinuation   `protobuf:"bytes,3,opt,name=Next,proto3" json:"Next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertIncidentPageResponse) Reset() {
	*x = AlertIncidentPageResponse{}
	mi := &file_alerts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertIncidentPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertIncidentPageResponse) ProtoMessage() {}

func (x *AlertIncidentPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertIncidentPageResponse.ProtoReflect.Descriptor instead.
func (*AlertIncidentPageResponse) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{5}
}

func (x *AlertIncidentPageResponse) GetStatus() AlertIncidentsReadinessState {
	if x != nil {
		return x.Status
	}
	return AlertIncidentsReadinessState_CatchingUp
}

func (x *AlertIncidentPageResponse) GetItems() []*AlertIncidentDetails {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *AlertIncidentPageResponse) GetNext() *AlertIncidentContinuation {
	if x != nil {
		return x.Next
	}
	return nil
}

type AlertIncidentSummaryResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Status        AlertIncidentsReadinessState `protobuf:"varint,1,opt,name=Status,proto3,enum=Cratis.Chronicle.Contracts.Alerts.AlertIncidentsReadinessState" json:"Status,omitempty"`
	Counts        []*AlertIncidentCountDetails `protobuf:"bytes,2,rep,name=Counts,proto3" json:"Counts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertIncidentSummaryResponse) Reset() {
	*x = AlertIncidentSummaryResponse{}
	mi := &file_alerts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertIncidentSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertIncidentSummaryResponse) ProtoMessage() {}

func (x *AlertIncidentSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertIncidentSummaryResponse.ProtoReflect.Descriptor instead.
func (*AlertIncidentSummaryResponse) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{6}
}

func (x *AlertIncidentSummaryResponse) GetStatus() AlertIncidentsReadinessState {
	if x != nil {
		return x.Status
	}
	return AlertIncidentsReadinessState_CatchingUp
}

func (x *AlertIncidentSummaryResponse) GetCounts() []*AlertIncidentCountDetails {
	if x != nil {
		return x.Counts
	}
	return nil
}

type AlertTarget struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventStore      string                 `protobuf:"bytes,1,opt,name=EventStore,proto3" json:"EventStore,omitempty"`
	Namespace       string                 `protobuf:"bytes,2,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	ObserverId      string                 `protobuf:"bytes,3,opt,name=ObserverId,proto3" json:"ObserverId,omitempty"`
	EventSequenceId string                 `protobuf:"bytes,4,opt,name=EventSequenceId,proto3" json:"EventSequenceId,omitempty"`
	Partition       string                 `protobuf:"bytes,5,opt,name=Partition,proto3" json:"Partition,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AlertTarget) Reset() {
	*x = AlertTarget{}
	mi := &file_alerts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertTarget) ProtoMessage() {}

func (x *AlertTarget) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertTarget.ProtoReflect.Descriptor instead.
func (*AlertTarget) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{7}
}

func (x *AlertTarget) GetEventStore() string {
	if x != nil {
		return x.EventStore
	}
	return ""
}

func (x *AlertTarget) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AlertTarget) GetObserverId() string {
	if x != nil {
		return x.ObserverId
	}
	return ""
}

func (x *AlertTarget) GetEventSequenceId() string {
	if x != nil {
		return x.EventSequenceId
	}
	return ""
}

func (x *AlertTarget) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

type GetOpenIncidentCountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventStore    string                 `protobuf:"bytes,1,opt,name=EventStore,proto3" json:"EventStore,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOpenIncidentCountsRequest) Reset() {
	*x = GetOpenIncidentCountsRequest{}
	mi := &file_alerts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOpenIncidentCountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpenIncidentCountsRequest) ProtoMessage() {}

func (x *GetOpenIncidentCountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpenIncidentCountsRequest.ProtoReflect.Descriptor instead.
func (*GetOpenIncidentCountsRequest) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{8}
}

func (x *GetOpenIncidentCountsRequest) GetEventStore() string {
	if x != nil {
		return x.EventStore
	}
	return ""
}

func (x *GetOpenIncidentCountsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type GetOpenIncidentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventStore    string                 `protobuf:"bytes,1,opt,name=EventStore,proto3" json:"EventStore,omitempty"`
	IncidentId    *bcl.Guid              `protobuf:"bytes,2,opt,name=IncidentId,proto3" json:"IncidentId,omitempty"` // default value could not be applied: 00000000-0000-0000-0000-000000000000
	Namespace     string                 `protobuf:"bytes,3,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOpenIncidentRequest) Reset() {
	*x = GetOpenIncidentRequest{}
	mi := &file_alerts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOpenIncidentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpenIncidentRequest) ProtoMessage() {}

func (x *GetOpenIncidentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpenIncidentRequest.ProtoReflect.Descriptor instead.
func (*GetOpenIncidentRequest) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{9}
}

func (x *GetOpenIncidentRequest) GetEventStore() string {
	if x != nil {
		return x.EventStore
	}
	return ""
}

func (x *GetOpenIncidentRequest) GetIncidentId() *bcl.Guid {
	if x != nil {
		return x.IncidentId
	}
	return nil
}

func (x *GetOpenIncidentRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type GetOpenIncidentsRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	EventStore                string                 `protobuf:"bytes,1,opt,name=EventStore,proto3" json:"EventStore,omitempty"`
	Namespace                 string                 `protobuf:"bytes,2,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	ObserverId                string                 `protobuf:"bytes,3,opt,name=ObserverId,proto3" json:"ObserverId,omitempty"`
	Condition                 string                 `protobuf:"bytes,4,opt,name=Condition,proto3" json:"Condition,omitempty"`
	MinimumSeverity           AlertSeverity          `protobuf:"varint,5,opt,name=MinimumSeverity,proto3,enum=Cratis.Chronicle.Contracts.Alerts.AlertSeverity" json:"MinimumSeverity,omitempty"`
	Limit                     int32                  `protobuf:"varint,6,opt,name=Limit,proto3" json:"Limit,omitempty"`
	AfterRaisedSequenceNumber uint64                 `protobuf:"varint,7,opt,name=AfterRaisedSequenceNumber,proto3" json:"AfterRaisedSequenceNumber,omitempty"`
	AfterIncidentId           *bcl.Guid              `protobuf:"bytes,8,opt,name=AfterIncidentId,proto3" json:"AfterIncidentId,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *GetOpenIncidentsRequest) Reset() {
	*x = GetOpenIncidentsRequest{}
	mi := &file_alerts_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOpenIncidentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpenIncidentsRequest) ProtoMessage() {}

func (x *GetOpenIncidentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpenIncidentsRequest.ProtoReflect.Descriptor instead.
func (*GetOpenIncidentsRequest) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{10}
}

func (x *GetOpenIncidentsRequest) GetEventStore() string {
	if x != nil {
		return x.EventStore
	}
	return ""
}

func (x *GetOpenIncidentsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetOpenIncidentsRequest) GetObserverId() string {
	if x != nil {
		return x.ObserverId
	}
	return ""
}

func (x *GetOpenIncidentsRequest) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *GetOpenIncidentsRequest) GetMinimumSeverity() AlertSeverity {
	if x != nil {
		return x.MinimumSeverity
	}
	return AlertSeverity_ALERT_SEVERITY_Warning
}

func (x *GetOpenIncidentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetOpenIncidentsRequest) GetAfterRaisedSequenceNumber() uint64 {
	if x != nil {
		return x.AfterRaisedSequenceNumber
	}
	return 0
}

func (x *GetOpenIncidentsRequest) GetAfterIncidentId() *bcl.Guid {
	if x != nil {
		return x.AfterIncidentId
	}
	return nil
}

type QueryResult_AlertIncidentLookupResponse struct {
	state               protoimpl.MessageState       `protogen:"open.v1"`
	CorrelationId       *bcl.Guid                    `protobuf:"bytes,1,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"` // default value could not be applied: 00000000-0000-0000-0000-000000000000
	IsAuthorized        bool                         `protobuf:"varint,2,opt,name=IsAuthorized,proto3" json:"IsAuthorized,omitempty"`
	ValidationResults   []*ValidationResult          `protobuf:"bytes,3,rep,name=ValidationResults,proto3" json:"ValidationResults,omitempty"`
	ExceptionMessages   []string                     `protobuf:"bytes,4,rep,name=ExceptionMessages,proto3" json:"ExceptionMessages,omitempty"`
	ExceptionStackTrace string                       `protobuf:"bytes,5,opt,name=ExceptionStackTrace,proto3" json:"ExceptionStackTrace,omitempty"`
	Data                *AlertIncidentLookupResponse `protobuf:"bytes,6,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QueryResult_AlertIncidentLookupResponse) Reset() {
	*x = QueryResult_AlertIncidentLookupResponse{}
	mi := &file_alerts_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult_AlertIncidentLookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult_AlertIncidentLookupResponse) ProtoMessage() {}

func (x *QueryResult_AlertIncidentLookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult_AlertIncidentLookupResponse.ProtoReflect.Descriptor instead.
func (*QueryResult_AlertIncidentLookupResponse) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{11}
}

func (x *QueryResult_AlertIncidentLookupResponse) GetCorrelationId() *bcl.Guid {
	if x != nil {
		return x.CorrelationId
	}
	return nil
}

func (x *QueryResult_AlertIncidentLookupResponse) GetIsAuthorized() bool {
	if x != nil {
		return x.IsAuthorized
	}
	return false
}

func (x *QueryResult_AlertIncidentLookupResponse) GetValidationResults() []*ValidationResult {
	if x != nil {
		return x.ValidationResults
	}
	return nil
}

func (x *QueryResult_AlertIncidentLookupResponse) GetExceptionMessages() []string {
	if x != nil {
		return x.ExceptionMessages
	}
	return nil
}

func (x *QueryResult_AlertIncidentLookupResponse) GetExceptionStackTrace() string {
	if x != nil {
		return x.ExceptionStackTrace
	}
	return ""
}

func (x *QueryResult_AlertIncidentLookupResponse) GetData() *AlertIncidentLookupResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type QueryResult_AlertIncidentPageResponse struct {
	state               protoimpl.MessageState     `protogen:"open.v1"`
	CorrelationId       *bcl.Guid                  `protobuf:"bytes,1,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"` // default value could not be applied: 00000000-0000-0000-0000-000000000000
	IsAuthorized        bool                       `protobuf:"varint,2,opt,name=IsAuthorized,proto3" json:"IsAuthorized,omitempty"`
	ValidationResults   []*ValidationResult        `protobuf:"bytes,3,rep,name=ValidationResults,proto3" json:"ValidationResults,omitempty"`
	ExceptionMessages   []string                   `protobuf:"bytes,4,rep,name=ExceptionMessages,proto3" json:"ExceptionMessages,omitempty"`
	ExceptionStackTrace string                     `protobuf:"bytes,5,opt,name=ExceptionStackTrace,proto3" json:"ExceptionStackTrace,omitempty"`
	Data                *AlertIncidentPageResponse `protobuf:"bytes,6,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QueryResult_AlertIncidentPageResponse) Reset() {
	*x = QueryResult_AlertIncidentPageResponse{}
	mi := &file_alerts_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult_AlertIncidentPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult_AlertIncidentPageResponse) ProtoMessage() {}

func (x *QueryResult_AlertIncidentPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult_AlertIncidentPageResponse.ProtoReflect.Descriptor instead.
func (*QueryResult_AlertIncidentPageResponse) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{12}
}

func (x *QueryResult_AlertIncidentPageResponse) GetCorrelationId() *bcl.Guid {
	if x != nil {
		return x.CorrelationId
	}
	return nil
}

func (x *QueryResult_AlertIncidentPageResponse) GetIsAuthorized() bool {
	if x != nil {
		return x.IsAuthorized
	}
	return false
}

func (x *QueryResult_AlertIncidentPageResponse) GetValidationResults() []*ValidationResult {
	if x != nil {
		return x.ValidationResults
	}
	return nil
}

func (x *QueryResult_AlertIncidentPageResponse) GetExceptionMessages() []string {
	if x != nil {
		return x.ExceptionMessages
	}
	return nil
}

func (x *QueryResult_AlertIncidentPageResponse) GetExceptionStackTrace() string {
	if x != nil {
		return x.ExceptionStackTrace
	}
	return ""
}

func (x *QueryResult_AlertIncidentPageResponse) GetData() *AlertIncidentPageResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type QueryResult_AlertIncidentSummaryResponse struct {
	state               protoimpl.MessageState        `protogen:"open.v1"`
	CorrelationId       *bcl.Guid                     `protobuf:"bytes,1,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"` // default value could not be applied: 00000000-0000-0000-0000-000000000000
	IsAuthorized        bool                          `protobuf:"varint,2,opt,name=IsAuthorized,proto3" json:"IsAuthorized,omitempty"`
	ValidationResults   []*ValidationResult           `protobuf:"bytes,3,rep,name=ValidationResults,proto3" json:"ValidationResults,omitempty"`
	ExceptionMessages   []string                      `protobuf:"bytes,4,rep,name=ExceptionMessages,proto3" json:"ExceptionMessages,omitempty"`
	ExceptionStackTrace string                        `protobuf:"bytes,5,opt,name=ExceptionStackTrace,proto3" json:"ExceptionStackTrace,omitempty"`
	Data                *AlertIncidentSummaryResponse `protobuf:"bytes,6,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QueryResult_AlertIncidentSummaryResponse) Reset() {
	*x = QueryResult_AlertIncidentSummaryResponse{}
	mi := &file_alerts_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult_AlertIncidentSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult_AlertIncidentSummaryResponse) ProtoMessage() {}

func (x *QueryResult_AlertIncidentSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult_AlertIncidentSummaryResponse.ProtoReflect.Descriptor instead.
func (*QueryResult_AlertIncidentSummaryResponse) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{13}
}

func (x *QueryResult_AlertIncidentSummaryResponse) GetCorrelationId() *bcl.Guid {
	if x != nil {
		return x.CorrelationId
	}
	return nil
}

func (x *QueryResult_AlertIncidentSummaryResponse) GetIsAuthorized() bool {
	if x != nil {
		return x.IsAuthorized
	}
	return false
}

func (x *QueryResult_AlertIncidentSummaryResponse) GetValidationResults() []*ValidationResult {
	if x != nil {
		return x.ValidationResults
	}
	return nil
}

func (x *QueryResult_AlertIncidentSummaryResponse) GetExceptionMessages() []string {
	if x != nil {
		return x.ExceptionMessages
	}
	return nil
}

func (x *QueryResult_AlertIncidentSummaryResponse) GetExceptionStackTrace() string {
	if x != nil {
		return x.ExceptionStackTrace
	}
	return ""
}

func (x *QueryResult_AlertIncidentSummaryResponse) GetData() *AlertIncidentSummaryResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

// Represents a DateTimeOffset value as an ISO 8601 string (e.g., "2024-01-15T12:30:00.0000000+02:00").
type SerializableDateTimeOffset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerializableDateTimeOffset) Reset() {
	*x = SerializableDateTimeOffset{}
	mi := &file_alerts_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializableDateTimeOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializableDateTimeOffset) ProtoMessage() {}

func (x *SerializableDateTimeOffset) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializableDateTimeOffset.ProtoReflect.Descriptor instead.
func (*SerializableDateTimeOffset) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{14}
}

func (x *SerializableDateTimeOffset) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ValidationResult struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Severity      ValidationResultSeverity `protobuf:"varint,1,opt,name=Severity,proto3,enum=Cratis.Chronicle.Contracts.Alerts.ValidationResultSeverity" json:"Severity,omitempty"` // default value could not be applied: Error
	Message       string                   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Members       []string                 `protobuf:"bytes,3,rep,name=Members,proto3" json:"Members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationResult) Reset() {
	*x = ValidationResult{}
	mi := &file_alerts_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResult) ProtoMessage() {}

func (x *ValidationResult) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResult.ProtoReflect.Descriptor instead.
func (*ValidationResult) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{15}
}

func (x *ValidationResult) GetSeverity() ValidationResultSeverity {
	if x != nil {
		return x.Severity
	}
	return ValidationResultSeverity_VALIDATION_RESULT_SEVERITY_Unknown
}

func (x *ValidationResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationResult) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_alerts_proto protoreflect.FileDescriptor

const file_alerts_proto_rawDesc = "" +
	"\n" +
	"\falerts.proto\x12!Cratis.Chronicle.Contracts.Alerts\x1a\x16protobuf-net/bcl.proto\"\xe3\x02\n" +
	"\rAlertEvidence\x12\"\n" +
	"\fAttemptCount\x18\x01 \x01(\x05R\fAttemptCount\x12a\n" +
	"\fFirstFailure\x18\x02 \x01(\v2=.Cratis.Chronicle.Contracts.Alerts.SerializableDateTimeOffsetR\fFirstFailure\x12_\n" +
	"\vLastFailure\x18\x03 \x01(\v2=.Cratis.Chronicle.Contracts.Alerts.SerializableDateTimeOffsetR\vLastFailure\x12P\n" +
	"\vFailureKind\x18\x04 \x01(\x0e2..Cratis.Chronicle.Contracts.Alerts.FailureKindR\vFailureKind\x12\x18\n" +
	"\aMessage\x18\x05 \x01(\tR\aMessage\"z\n" +
	"\x19AlertIncidentContinuation\x122\n" +
	"\x14RaisedSequenceNumber\x18\x01 \x01(\x04R\x14RaisedSequenceNumber\x12)\n" +
	"\n" +
	"IncidentId\x18\x02 \x01(\v2\t.bcl.GuidR\n" +
	"IncidentId\"\xbb\x01\n" +
	"\x19AlertIncidentCountDetails\x12\x1c\n" +
	"\tNamespace\x18\x01 \x01(\tR\tNamespace\x12\x1c\n" +
	"\tCondition\x18\x02 \x01(\tR\tCondition\x12L\n" +
	"\bSeverity\x18\x03 \x01(\x0e20.Cratis.Chronicle.Contracts.Alerts.AlertSeverityR\bSeverity\x12\x14\n" +
	"\x05Count\x18\x04 \x01(\x03R\x05Count\"\xeb\x04\n" +
	"\x14AlertIncidentDetails\x12\x19\n" +
	"\x02Id\x18\x01 \x01(\v2\t.bcl.GuidR\x02Id\x12F\n" +
	"\x06Target\x18\x02 \x01(\v2..Cratis.Chronicle.Contracts.Alerts.AlertTargetR\x06Target\x12\x1c\n" +
	"\tCondition\x18\x03 \x01(\tR\tCondition\x12L\n" +
	"\bSeverity\x18\x04 \x01(\x0e20.Cratis.Chronicle.Contracts.Alerts.AlertSeverityR\bSeverity\x12L\n" +
	"\bEvidence\x18\x05 \x01(\v20.Cratis.Chronicle.Contracts.Alerts.AlertEvidenceR\bEvidence\x12Y\n" +
	"\bRaisedAt\x18\x06 \x01(\v2=.Cratis.Chronicle.Contracts.Alerts.SerializableDateTimeOffsetR\bRaisedAt\x12c\n" +
	"\rLastChangedAt\x18\a \x01(\v2=.Cratis.Chronicle.Contracts.Alerts.SerializableDateTimeOffsetR\rLastChangedAt\x122\n" +
	"\x14RaisedSequenceNumber\x18\b \x01(\x04R\x14RaisedSequenceNumber\x12B\n" +
	"\x1cLastTransitionSequenceNumber\x18\t \x01(\x04R\x1cLastTransitionSequenceNumber\"\xcb\x01\n" +
	"\x1bAlertIncidentLookupResponse\x12W\n" +
	"\x06Status\x18\x01 \x01(\x0e2?.Cratis.Chronicle.Contracts.Alerts.AlertIncidentsReadinessStateR\x06Status\x12S\n" +
	"\bIncident\x18\x02 \x01(\v27.Cratis.Chronicle.Contracts.Alerts.AlertIncidentDetailsR\bIncident\"\x95\x02\n" +
	"\x19AlertIncidentPageResponse\x12W\n" +
	"\x06Status\x18\x01 \x01(\x0e2?.Cratis.Chronicle.Contracts.Alerts.AlertIncidentsReadinessStateR\x06Status\x12M\n" +
	"\x05Items\x18\x02 \x03(\v27.Cratis.Chronicle.Contracts.Alerts.AlertIncidentDetailsR\x05Items\x12P\n" +
	"\x04Next\x18\x03 \x01(\v2<.Cratis.Chronicle.Contracts.Alerts.AlertIncidentContinuationR\x04Next\"\xcd\x01\n" +
	"\x1cAlertIncidentSummaryResponse\x12W\n" +
	"\x06Status\x18\x01 \x01(\x0e2?.Cratis.Chronicle.Contracts.Alerts.AlertIncidentsReadinessStateR\x06Status\x12T\n" +
	"\x06Counts\x18\x02 \x03(\v2<.Cratis.Chronicle.Contracts.Alerts.AlertIncidentCountDetailsR\x06Counts\"\xb3\x01\n" +
	"\vAlertTarget\x12\x1e\n" +
	"\n" +
	"EventStore\x18\x01 \x01(\tR\n" +
	"EventStore\x12\x1c\n" +
	"\tNamespace\x18\x02 \x01(\tR\tNamespace\x12\x1e\n" +
	"\n" +
	"ObserverId\x18\x03 \x01(\tR\n" +
	"ObserverId\x12(\n" +
	"\x0fEventSequenceId\x18\x04 \x01(\tR\x0fEventSequenceId\x12\x1c\n" +
	"\tPartition\x18\x05 \x01(\tR\tPartition\"\\\n" +
	"\x1cGetOpenIncidentCountsRequest\x12\x1e\n" +
	"\n" +
	"EventStore\x18\x01 \x01(\tR\n" +
	"EventStore\x12\x1c\n" +
	"\tNamespace\x18\x02 \x01(\tR\tNamespace\"\x81\x01\n" +
	"\x16GetOpenIncidentRequest\x12\x1e\n" +
	"\n" +
	"EventStore\x18\x01 \x01(\tR\n" +
	"EventStore\x12)\n" +
	"\n" +
	"IncidentId\x18\x02 \x01(\v2\t.bcl.GuidR\n" +
	"IncidentId\x12\x1c\n" +
	"\tNamespace\x18\x03 \x01(\tR\tNamespace\"\xfa\x02\n" +
	"\x17GetOpenIncidentsRequest\x12\x1e\n" +
	"\n" +
	"EventStore\x18\x01 \x01(\tR\n" +
	"EventStore\x12\x1c\n" +
	"\tNamespace\x18\x02 \x01(\tR\tNamespace\x12\x1e\n" +
	"\n" +
	"ObserverId\x18\x03 \x01(\tR\n" +
	"ObserverId\x12\x1c\n" +
	"\tCondition\x18\x04 \x01(\tR\tCondition\x12Z\n" +
	"\x0fMinimumSeverity\x18\x05 \x01(\x0e20.Cratis.Chronicle.Contracts.Alerts.AlertSeverityR\x0fMinimumSeverity\x12\x14\n" +
	"\x05Limit\x18\x06 \x01(\x05R\x05Limit\x12<\n" +
	"\x19AfterRaisedSequenceNumber\x18\a \x01(\x04R\x19AfterRaisedSequenceNumber\x123\n" +
	"\x0fAfterIncidentId\x18\b \x01(\v2\t.bcl.GuidR\x0fAfterIncidentId\"\x95\x03\n" +
	"'QueryResult_AlertIncidentLookupResponse\x12/\n" +
	"\rCorrelationId\x18\x01 \x01(\v2\t.bcl.GuidR\rCorrelationId\x12\"\n" +
	"\fIsAuthorized\x18\x02 \x01(\bR\fIsAuthorized\x12a\n" +
	"\x11ValidationResults\x18\x03 \x03(\v23.Cratis.Chronicle.Contracts.Alerts.ValidationResultR\x11ValidationResults\x12,\n" +
	"\x11ExceptionMessages\x18\x04 \x03(\tR\x11ExceptionMessages\x120\n" +
	"\x13ExceptionStackTrace\x18\x05 \x01(\tR\x13ExceptionStackTrace\x12R\n" +
	"\x04Data\x18\x06 \x01(\v2>.Cratis.Chronicle.Contracts.Alerts.AlertIncidentLookupResponseR\x04Data\"\x91\x03\n" +
	"%QueryResult_AlertIncidentPageResponse\x12/\n" +
	"\rCorrelationId\x18\x01 \x01(\v2\t.bcl.GuidR\rCorrelationId\x12\"\n" +
	"\fIsAuthorized\x18\x02 \x01(\bR\fIsAuthorized\x12a\n" +
	"\x11ValidationResults\x18\x03 \x03(\v23.Cratis.Chronicle.Contracts.Alerts.ValidationResultR\x11ValidationResults\x12,\n" +
	"\x11ExceptionMessages\x18\x04 \x03(\tR\x11ExceptionMessages\x120\n" +
	"\x13ExceptionStackTrace\x18\x05 \x01(\tR\x13ExceptionStackTrace\x12P\n" +
	"\x04Data\x18\x06 \x01(\v2<.Cratis.Chronicle.Contracts.Alerts.AlertIncidentPageResponseR\x04Data\"\x97\x03\n" +
	"(QueryResult_AlertIncidentSummaryResponse\x12/\n" +
	"\rCorrelationId\x18\x01 \x01(\v2\t.bcl.GuidR\rCorrelationId\x12\"\n" +
	"\fIsAuthorized\x18\x02 \x01(\bR\fIsAuthorized\x12a\n" +
	"\x11ValidationResults\x18\x03 \x03(\v23.Cratis.Chronicle.Contracts.Alerts.ValidationResultR\x11ValidationResults\x12,\n" +
	"\x11ExceptionMessages\x18\x04 \x03(\tR\x11ExceptionMessages\x120\n" +
	"\x13ExceptionStackTrace\x18\x05 \x01(\tR\x13ExceptionStackTrace\x12S\n" +
	"\x04Data\x18\x06 \x01(\v2?.Cratis.Chronicle.Contracts.Alerts.AlertIncidentSummaryResponseR\x04Data\"2\n" +
	"\x1aSerializableDateTimeOffset\x12\x14\n" +
	"\x05Value\x18\x01 \x01(\tR\x05Value\"\x9f\x01\n" +
	"\x10ValidationResult\x12W\n" +
	"\bSeverity\x18\x01 \x01(\x0e2;.Cratis.Chronicle.Contracts.Alerts.ValidationResultSeverityR\bSeverity\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\x12\x18\n" +
	"\aMembers\x18\x03 \x03(\tR\aMembers*G\n" +
	"\x1cAlertIncidentsReadinessState\x12\x0e\n" +
	"\n" +
	"CatchingUp\x10\x00\x12\t\n" +
	"\x05Ready\x10\x01\x12\f\n" +
	"\bDegraded\x10\x02*9\n" +
	"\rAlertSeverity\x12\x1a\n" +
	"\x16ALERT_SEVERITY_Warning\x10\x00\x12\f\n" +
	"\bCritical\x10\x01*T\n" +
	"\vFailureKind\x12\x18\n" +
	"\x14FAILURE_KIND_Unknown\x10\x00\x12\f\n" +
	"\bHandling\x10\x01\x12\v\n" +
	"\aTimeout\x10\x02\x12\x10\n" +
	"\fDisconnected\x10\x03*\x86\x01\n" +
	"\x18ValidationResultSeverity\x12&\n" +
	"\"VALIDATION_RESULT_SEVERITY_Unknown\x10\x00\x12\x0f\n" +
	"\vInformation\x10\x01\x12&\n" +
	"\"VALIDATION_RESULT_SEVERITY_Warning\x10\x02\x12\t\n" +
	"\x05Error\x10\x032\xe6\x03\n" +
	"\x06Alerts\x12\x98\x01\n" +
	"\x0fGetOpenIncident\x129.Cratis.Chronicle.Contracts.Alerts.GetOpenIncidentRequest\x1aJ.Cratis.Chronicle.Contracts.Alerts.QueryResult_AlertIncidentLookupResponse\x12\xa5\x01\n" +
	"\x15GetOpenIncidentCounts\x12?.Cratis.Chronicle.Contracts.Alerts.GetOpenIncidentCountsRequest\x1aK.Cratis.Chronicle.Contracts.Alerts.QueryResult_AlertIncidentSummaryResponse\x12\x98\x01\n" +
	"\x10GetOpenIncidents\x12:.Cratis.Chronicle.Contracts.Alerts.GetOpenIncidentsRequest\x1aH.Cratis.Chronicle.Contracts.Alerts.QueryResult_AlertIncidentPageResponseB\x8d\x02\n" +
	"%com.Cratis.Chronicle.Contracts.AlertsB\vAlertsProtoP\x01Z/github.com/cratis/chronicle.go/contracts/alerts\xa2\x02\x04CCCA\xaa\x02!Cratis.Chronicle.Contracts.Alerts\xca\x02!Cratis\\Chronicle\\Contracts\\Alerts\xe2\x02-Cratis\\Chronicle\\Contracts\\Alerts\\GPBMetadata\xea\x02$Cratis::Chronicle::Contracts::Alertsb\x06proto3"

var (
	file_alerts_proto_rawDescOnce sync.Once
	file_alerts_proto_rawDescData []byte
)

func file_alerts_proto_rawDescGZIP() []byte {
	file_alerts_proto_rawDescOnce.Do(func() {
		file_alerts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alerts_proto_rawDesc), len(file_alerts_proto_rawDesc)))
	})
	return file_alerts_proto_rawDescData
}

var file_alerts_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_alerts_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_alerts_proto_goTypes = []any{
	(AlertIncidentsReadinessState)(0),                // 0: Cratis.Chronicle.Contracts.Alerts.AlertIncidentsReadinessState
	(AlertSeverity)(0),                               // 1: Cratis.Chronicle.Contracts.Alerts.AlertSeverity
	(FailureKind)(0),                                 // 2: Cratis.Chronicle.Contracts.Alerts.FailureKind
	(ValidationResultSeverity)(0),                    // 3: Cratis.Chronicle.Contracts.Alerts.ValidationResultSeverity
	(*AlertEvidence)(nil),                            // 4: Cratis.Chronicle.Contracts.Alerts.AlertEvidence
	(*AlertIncidentContinuation)(nil),                // 5: Cratis.Chronicle.Contracts.Alerts.AlertIncidentContinuation
	(*AlertIncidentCountDetails)(nil),                // 6: Cratis.Chronicle.Contracts.Alerts.AlertIncidentCountDetails
	(*AlertIncidentDetails)(nil),                     // 7: Cratis.Chronicle.Contracts.Alerts.AlertIncidentDetails
	(*AlertIncidentLookupResponse)(nil),              // 8: Cratis.Chronicle.Contracts.Alerts.AlertIncidentLookupResponse
	(*AlertIncidentPageResponse)(nil),                // 9: Cratis.Chronicle.Contracts.Alerts.AlertIncidentPageResponse
	(*AlertIncidentSummaryResponse)(nil),             // 10: Cratis.Chronicle.Contracts.Alerts.AlertIncidentSummaryResponse
	(*AlertTarget)(nil),                              // 11: Cratis.Chronicle.Contracts.Alerts.AlertTarget
	(*GetOpenIncidentCountsRequest)(nil),             // 12: Cratis.Chronicle.Contracts.Alerts.GetOpenIncidentCountsRequest
	(*GetOpenIncidentRequest)(nil),                   // 13: Cratis.Chronicle.Contracts.Alerts.GetOpenIncidentRequest
	(*GetOpenIncidentsRequest)(nil),                  // 14: Cratis.Chronicle.Contracts.Alerts.GetOpenIncidentsRequest
	(*QueryResult_AlertIncidentLookupResponse)(nil),  // 15: Cratis.Chronicle.Contracts.Alerts.QueryResult_AlertIncidentLookupResponse
	(*QueryResult_AlertIncidentPageResponse)(nil),    // 16: Cratis.Chronicle.Contracts.Alerts.QueryResult_AlertIncidentPageResponse
	(*QueryResult_AlertIncidentSummaryResponse)(nil), // 17: Cratis.Chronicle.Contracts.Alerts.QueryResult_AlertIncidentSummaryResponse
	(*SerializableDateTimeOffset)(nil),               // 18: Cratis.Chronicle.Contracts.Alerts.SerializableDateTimeOffset
	(*ValidationResult)(nil),                         // 19: Cratis.Chronicle.Contracts.Alerts.ValidationResult
	(*bcl.Guid)(nil),                                 // 20: bcl.Guid
}
var file_alerts_proto_depIdxs = []int32{
	18, // 0: Cratis.Chronicle.Contracts.Alerts.AlertEvidence.FirstFailure:type_name -> Cratis.Chronicle.Contracts.Alerts.SerializableDateTimeOffset
	18, // 1: Cratis.Chronicle.Contracts.Alerts.AlertEvidence.LastFailure:type_name -> Cratis.Chronicle.Contracts.Alerts.SerializableDateTimeOffset
	2,  // 2: Cratis.Chronicle.Contracts.Alerts.AlertEvidence.FailureKind:type_name -> Cratis.Chronicle.Contracts.Alerts.FailureKind
	20, // 3: Cratis.Chronicle.Contracts.Alerts.AlertIncidentContinuation.IncidentId:type_name -> bcl.Guid
	1,  // 4: Cratis.Chronicle.Contracts.Alerts.AlertIncidentCountDetails.Severity:type_name -> Cratis.Chronicle.Contracts.Alerts.AlertSeverity
	20, // 5: Cratis.Chronicle.Contracts.Alerts.AlertIncidentDetails.Id:type_name -> bcl.Guid
	11, // 6: Cratis.Chronicle.Contracts.Alerts.AlertIncidentDetails.Target:type_name -> Cratis.Chronicle.Contracts.Alerts.AlertTarget
	1,  // 7: Cratis.Chronicle.Contracts.Alerts.AlertIncidentDetails.Severity:type_name -> Cratis.Chronicle.Contracts.Alerts.AlertSeverity
	4,  // 8: Cratis.Chronicle.Contracts.Alerts.AlertIncidentDetails.Evidence:type_name -> Cratis.Chronicle.Contracts.Alerts.AlertEvidence
	18, // 9: Cratis.Chronicle.Contracts.Alerts.AlertIncidentDetails.RaisedAt:type_name -> Cratis.Chronicle.Contracts.Alerts.SerializableDateTimeOffset
	18, // 10: Cratis.Chronicle.Contracts.Alerts.AlertIncidentDetails.LastChangedAt:type_name -> Cratis.Chronicle.Contracts.Alerts.SerializableDateTimeOffset
	0,  // 11: Cratis.Chronicle.Contracts.Alerts.AlertIncidentLookupResponse.Status:type_name -> Cratis.Chronicle.Contracts.Alerts.AlertIncidentsReadinessState
	7,  // 12: Cratis.Chronicle.Contracts.Alerts.AlertIncidentLookupResponse.Incident:type_name -> Cratis.Chronicle.Contracts.Alerts.AlertIncidentDetails
	0,  // 13: Cratis.Chronicle.Contracts.Alerts.AlertIncidentPageResponse.Status:type_name -> Cratis.Chronicle.Contracts.Alerts.AlertIncidentsReadinessState
	7,  // 14: Cratis.Chronicle.Contracts.Alerts.AlertIncidentPageResponse.Items:type_name -> Cratis.Chronicle.Contracts.Alerts.AlertIncidentDetails
	5,  // 15: Cratis.Chronicle.Contracts.Alerts.AlertIncidentPageResponse.Next:type_name -> Cratis.Chronicle.Contracts.Alerts.AlertIncidentContinuation
	0,  // 16: Cratis.Chronicle.Contracts.Alerts.AlertIncidentSummaryResponse.Status:type_name -> Cratis.Chronicle.Contracts.Alerts.AlertIncidentsReadinessState
	6,  // 17: Cratis.Chronicle.Contracts.Alerts.AlertIncidentSummaryResponse.Counts:type_name -> Cratis.Chronicle.Contracts.Alerts.AlertIncidentCountDetails
	20, // 18: Cratis.Chronicle.Contracts.Alerts.GetOpenIncidentRequest.IncidentId:type_name -> bcl.Guid
	1,  // 19: Cratis.Chronicle.Contracts.Alerts.GetOpenIncidentsRequest.MinimumSeverity:type_name -> Cratis.Chronicle.Contracts.Alerts.AlertSeverity
	20, // 20: Cratis.Chronicle.Contracts.Alerts.GetOpenIncidentsRequest.AfterIncidentId:type_name -> bcl.Guid
	20, // 21: Cratis.Chronicle.Contracts.Alerts.QueryResult_AlertIncidentLookupResponse.CorrelationId:type_name -> bcl.Guid
	19, // 22: Cratis.Chronicle.Contracts.Alerts.QueryResult_AlertIncidentLookupResponse.ValidationResults:type_name -> Cratis.Chronicle.Contracts.Alerts.ValidationResult
	8,  // 23: Cratis.Chronicle.Contracts.Alerts.QueryResult_AlertIncidentLookupResponse.Data:type_name -> Cratis.Chronicle.Contracts.Alerts.AlertIncidentLookupResponse
	20, // 24: Cratis.Chronicle.Contracts.Alerts.QueryResult_AlertIncidentPageResponse.CorrelationId:type_name -> bcl.Guid
	19, // 25: Cratis.Chronicle.Contracts.Alerts.QueryResult_AlertIncidentPageResponse.ValidationResults:type_name -> Cratis.Chronicle.Contracts.Alerts.ValidationResult
	9,  // 26: Cratis.Chronicle.Contracts.Alerts.QueryResult_AlertIncidentPageResponse.Data:type_name -> Cratis.Chronicle.Contracts.Alerts.AlertIncidentPageResponse
	20, // 27: Cratis.Chronicle.Contracts.Alerts.QueryResult_AlertIncidentSummaryResponse.CorrelationId:type_name -> bcl.Guid
	19, // 28: Cratis.Chronicle.Contracts.Alerts.QueryResult_AlertIncidentSummaryResponse.ValidationResults:type_name -> Cratis.Chronicle.Contracts.Alerts.ValidationResult
	10, // 29: Cratis.Chronicle.Contracts.Alerts.QueryResult_AlertIncidentSummaryResponse.Data:type_name -> Cratis.Chronicle.Contracts.Alerts.AlertIncidentSummaryResponse
	3,  // 30: Cratis.Chronicle.Contracts.Alerts.ValidationResult.Severity:type_name -> Cratis.Chronicle.Contracts.Alerts.ValidationResultSeverity
	13, // 31: Cratis.Chronicle.Contracts.Alerts.Alerts.GetOpenIncident:input_type -> Cratis.Chronicle.Contracts.Alerts.GetOpenIncidentRequest
	12, // 32: Cratis.Chronicle.Contracts.Alerts.Alerts.GetOpenIncidentCounts:input_type -> Cratis.Chronicle.Contracts.Alerts.GetOpenIncidentCountsRequest
	14, // 33: Cratis.Chronicle.Contracts.Alerts.Alerts.GetOpenIncidents:input_type -> Cratis.Chronicle.Contracts.Alerts.GetOpenIncidentsRequest
	15, // 34: Cratis.Chronicle.Contracts.Alerts.Alerts.GetOpenIncident:output_type -> Cratis.Chronicle.Contracts.Alerts.QueryResult_AlertIncidentLookupResponse
	17, // 35: Cratis.Chronicle.Contracts.Alerts.Alerts.GetOpenIncidentCounts:output_type -> Cratis.Chronicle.Contracts.Alerts.QueryResult_AlertIncidentSummaryResponse
	16, // 36: Cratis.Chronicle.Contracts.Alerts.Alerts.GetOpenIncidents:output_type -> Cratis.Chronicle.Contracts.Alerts.QueryResult_AlertIncidentPageResponse
	34, // [34:37] is the sub-list for method output_type
	31, // [31:34] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_alerts_proto_init() }
func file_alerts_proto_init() {
	if File_alerts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alerts_proto_rawDesc), len(file_alerts_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alerts_proto_goTypes,
		DependencyIndexes: file_alerts_proto_depIdxs,
		EnumInfos:         file_alerts_proto_enumTypes,
		MessageInfos:      file_alerts_proto_msgTypes,
	}.Build()
	File_alerts_proto = out.File
	file_alerts_proto_goTypes = nil
	file_alerts_proto_depIdxs = nil
}
