// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: seeding.proto

package seeding

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventSeeding_AddSeedEntry_FullMethodName         = "/Cratis.Chronicle.Contracts.Seeding.EventSeeding/AddSeedEntry"
	EventSeeding_GetGlobalSeedData_FullMethodName    = "/Cratis.Chronicle.Contracts.Seeding.EventSeeding/GetGlobalSeedData"
	EventSeeding_GetNamespaceSeedData_FullMethodName = "/Cratis.Chronicle.Contracts.Seeding.EventSeeding/GetNamespaceSeedData"
	EventSeeding_SeedEvents_FullMethodName           = "/Cratis.Chronicle.Contracts.Seeding.EventSeeding/SeedEvents"
)

// EventSeedingClient is the client API for EventSeeding service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventSeedingClient interface {
	AddSeedEntry(ctx context.Context, in *AddSeedEntryRequest, opts ...grpc.CallOption) (*CommandResult, error)
	GetGlobalSeedData(ctx context.Context, in *GetGlobalSeedDataRequest, opts ...grpc.CallOption) (*QueryResult_SeedDataResponse, error)
	GetNamespaceSeedData(ctx context.Context, in *GetNamespaceSeedDataRequest, opts ...grpc.CallOption) (*QueryResult_SeedDataResponse, error)
	SeedEvents(ctx context.Context, in *SeedEventsRequest, opts ...grpc.CallOption) (*CommandResult, error)
}

type eventSeedingClient struct {
	cc grpc.ClientConnInterface
}

func NewEventSeedingClient(cc grpc.ClientConnInterface) EventSeedingClient {
	return &eventSeedingClient{cc}
}

func (c *eventSeedingClient) AddSeedEntry(ctx context.Context, in *AddSeedEntryRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, EventSeeding_AddSeedEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSeedingClient) GetGlobalSeedData(ctx context.Context, in *GetGlobalSeedDataRequest, opts ...grpc.CallOption) (*QueryResult_SeedDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResult_SeedDataResponse)
	err := c.cc.Invoke(ctx, EventSeeding_GetGlobalSeedData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSeedingClient) GetNamespaceSeedData(ctx context.Context, in *GetNamespaceSeedDataRequest, opts ...grpc.CallOption) (*QueryResult_SeedDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResult_SeedDataResponse)
	err := c.cc.Invoke(ctx, EventSeeding_GetNamespaceSeedData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSeedingClient) SeedEvents(ctx context.Context, in *SeedEventsRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, EventSeeding_SeedEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventSeedingServer is the server API for EventSeeding service.
// All implementations must embed UnimplementedEventSeedingServer
// for forward compatibility.
type EventSeedingServer interface {
	AddSeedEntry(context.Context, *AddSeedEntryRequest) (*CommandResult, error)
	GetGlobalSeedData(context.Context, *GetGlobalSeedDataRequest) (*QueryResult_SeedDataResponse, error)
	GetNamespaceSeedData(context.Context, *GetNamespaceSeedDataRequest) (*QueryResult_SeedDataResponse, error)
	SeedEvents(context.Context, *SeedEventsRequest) (*CommandResult, error)
	mustEmbedUnimplementedEventSeedingServer()
}

// UnimplementedEventSeedingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventSeedingServer struct{}

func (UnimplementedEventSeedingServer) AddSeedEntry(context.Context, *AddSeedEntryRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method AddSeedEntry not implemented")
}
func (UnimplementedEventSeedingServer) GetGlobalSeedData(context.Context, *GetGlobalSeedDataRequest) (*QueryResult_SeedDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGlobalSeedData not implemented")
}
func (UnimplementedEventSeedingServer) GetNamespaceSeedData(context.Context, *GetNamespaceSeedDataRequest) (*QueryResult_SeedDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNamespaceSeedData not implemented")
}
func (UnimplementedEventSeedingServer) SeedEvents(context.Context, *SeedEventsRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SeedEvents not implemented")
}
func (UnimplementedEventSeedingServer) mustEmbedUnimplementedEventSeedingServer() {}
func (UnimplementedEventSeedingServer) testEmbeddedByValue()                      {}

// UnsafeEventSeedingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventSeedingServer will
// result in compilation errors.
type UnsafeEventSeedingServer interface {
	mustEmbedUnimplementedEventSeedingServer()
}

func RegisterEventSeedingServer(s grpc.ServiceRegistrar, srv EventSeedingServer) {
	// If the following call panics, it indicates UnimplementedEventSeedingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventSeeding_ServiceDesc, srv)
}

func _EventSeeding_AddSeedEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSeedEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSeedingServer).AddSeedEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSeeding_AddSeedEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSeedingServer).AddSeedEntry(ctx, req.(*AddSeedEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSeeding_GetGlobalSeedData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGlobalSeedDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSeedingServer).GetGlobalSeedData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSeeding_GetGlobalSeedData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSeedingServer).GetGlobalSeedData(ctx, req.(*GetGlobalSeedDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSeeding_GetNamespaceSeedData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNamespaceSeedDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSeedingServer).GetNamespaceSeedData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSeeding_GetNamespaceSeedData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSeedingServer).GetNamespaceSeedData(ctx, req.(*GetNamespaceSeedDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSeeding_SeedEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeedEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSeedingServer).SeedEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSeeding_SeedEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSeedingServer).SeedEvents(ctx, req.(*SeedEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventSeeding_ServiceDesc is the grpc.ServiceDesc for EventSeeding service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventSeeding_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Cratis.Chronicle.Contracts.Seeding.EventSeeding",
	HandlerType: (*EventSeedingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddSeedEntry",
			Handler:    _EventSeeding_AddSeedEntry_Handler,
		},
		{
			MethodName: "GetGlobalSeedData",
			Handler:    _EventSeeding_GetGlobalSeedData_Handler,
		},
		{
			MethodName: "GetNamespaceSeedData",
			Handler:    _EventSeeding_GetNamespaceSeedData_Handler,
		},
		{
			MethodName: "SeedEvents",
			Handler:    _EventSeeding_SeedEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seeding.proto",
}
