// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: security.proto

package security

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Applications_AddApplication_FullMethodName          = "/Cratis.Chronicle.Contracts.Security.Applications/AddApplication"
	Applications_AllApplications_FullMethodName         = "/Cratis.Chronicle.Contracts.Security.Applications/AllApplications"
	Applications_ChangeApplicationSecret_FullMethodName = "/Cratis.Chronicle.Contracts.Security.Applications/ChangeApplicationSecret"
	Applications_RemoveApplication_FullMethodName       = "/Cratis.Chronicle.Contracts.Security.Applications/RemoveApplication"
)

// ApplicationsClient is the client API for Applications service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApplicationsClient interface {
	AddApplication(ctx context.Context, in *AddApplicationRequest, opts ...grpc.CallOption) (*CommandResult, error)
	AllApplications(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResult_IEnumerable_ApplicationResponse], error)
	ChangeApplicationSecret(ctx context.Context, in *ChangeApplicationSecretRequest, opts ...grpc.CallOption) (*CommandResult, error)
	RemoveApplication(ctx context.Context, in *RemoveApplicationRequest, opts ...grpc.CallOption) (*CommandResult, error)
}

type applicationsClient struct {
	cc grpc.ClientConnInterface
}

func NewApplicationsClient(cc grpc.ClientConnInterface) ApplicationsClient {
	return &applicationsClient{cc}
}

func (c *applicationsClient) AddApplication(ctx context.Context, in *AddApplicationRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, Applications_AddApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationsClient) AllApplications(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResult_IEnumerable_ApplicationResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Applications_ServiceDesc.Streams[0], Applications_AllApplications_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, QueryResult_IEnumerable_ApplicationResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Applications_AllApplicationsClient = grpc.ServerStreamingClient[QueryResult_IEnumerable_ApplicationResponse]

func (c *applicationsClient) ChangeApplicationSecret(ctx context.Context, in *ChangeApplicationSecretRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, Applications_ChangeApplicationSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationsClient) RemoveApplication(ctx context.Context, in *RemoveApplicationRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, Applications_RemoveApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApplicationsServer is the server API for Applications service.
// All implementations must embed UnimplementedApplicationsServer
// for forward compatibility.
type ApplicationsServer interface {
	AddApplication(context.Context, *AddApplicationRequest) (*CommandResult, error)
	AllApplications(*emptypb.Empty, grpc.ServerStreamingServer[QueryResult_IEnumerable_ApplicationResponse]) error
	ChangeApplicationSecret(context.Context, *ChangeApplicationSecretRequest) (*CommandResult, error)
	RemoveApplication(context.Context, *RemoveApplicationRequest) (*CommandResult, error)
	mustEmbedUnimplementedApplicationsServer()
}

// UnimplementedApplicationsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApplicationsServer struct{}

func (UnimplementedApplicationsServer) AddApplication(context.Context, *AddApplicationRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method AddApplication not implemented")
}
func (UnimplementedApplicationsServer) AllApplications(*emptypb.Empty, grpc.ServerStreamingServer[QueryResult_IEnumerable_ApplicationResponse]) error {
	return status.Error(codes.Unimplemented, "method AllApplications not implemented")
}
func (UnimplementedApplicationsServer) ChangeApplicationSecret(context.Context, *ChangeApplicationSecretRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeApplicationSecret not implemented")
}
func (UnimplementedApplicationsServer) RemoveApplication(context.Context, *RemoveApplicationRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveApplication not implemented")
}
func (UnimplementedApplicationsServer) mustEmbedUnimplementedApplicationsServer() {}
func (UnimplementedApplicationsServer) testEmbeddedByValue()                      {}

// UnsafeApplicationsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApplicationsServer will
// result in compilation errors.
type UnsafeApplicationsServer interface {
	mustEmbedUnimplementedApplicationsServer()
}

func RegisterApplicationsServer(s grpc.ServiceRegistrar, srv ApplicationsServer) {
	// If the following call panics, it indicates UnimplementedApplicationsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Applications_ServiceDesc, srv)
}

func _Applications_AddApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationsServer).AddApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Applications_AddApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationsServer).AddApplication(ctx, req.(*AddApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Applications_AllApplications_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApplicationsServer).AllApplications(m, &grpc.GenericServerStream[emptypb.Empty, QueryResult_IEnumerable_ApplicationResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Applications_AllApplicationsServer = grpc.ServerStreamingServer[QueryResult_IEnumerable_ApplicationResponse]

func _Applications_ChangeApplicationSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeApplicationSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationsServer).ChangeApplicationSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Applications_ChangeApplicationSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationsServer).ChangeApplicationSecret(ctx, req.(*ChangeApplicationSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Applications_RemoveApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationsServer).RemoveApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Applications_RemoveApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationsServer).RemoveApplication(ctx, req.(*RemoveApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Applications_ServiceDesc is the grpc.ServiceDesc for Applications service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Applications_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Cratis.Chronicle.Contracts.Security.Applications",
	HandlerType: (*ApplicationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddApplication",
			Handler:    _Applications_AddApplication_Handler,
		},
		{
			MethodName: "ChangeApplicationSecret",
			Handler:    _Applications_ChangeApplicationSecret_Handler,
		},
		{
			MethodName: "RemoveApplication",
			Handler:    _Applications_RemoveApplication_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AllApplications",
			Handler:       _Applications_AllApplications_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "security.proto",
}

const (
	Users_AddUser_FullMethodName                 = "/Cratis.Chronicle.Contracts.Security.Users/AddUser"
	Users_AllUsers_FullMethodName                = "/Cratis.Chronicle.Contracts.Security.Users/AllUsers"
	Users_ChangeUserPassword_FullMethodName      = "/Cratis.Chronicle.Contracts.Security.Users/ChangeUserPassword"
	Users_GetStatus_FullMethodName               = "/Cratis.Chronicle.Contracts.Security.Users/GetStatus"
	Users_RemoveUser_FullMethodName              = "/Cratis.Chronicle.Contracts.Security.Users/RemoveUser"
	Users_RequirePasswordChange_FullMethodName   = "/Cratis.Chronicle.Contracts.Security.Users/RequirePasswordChange"
	Users_SetInitialAdminPassword_FullMethodName = "/Cratis.Chronicle.Contracts.Security.Users/SetInitialAdminPassword"
)

// UsersClient is the client API for Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsersClient interface {
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*CommandResult, error)
	AllUsers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResult_IEnumerable_UserResponse], error)
	ChangeUserPassword(ctx context.Context, in *ChangeUserPasswordRequest, opts ...grpc.CallOption) (*CommandResult, error)
	GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*QueryResult_AdminPasswordStatusResponse, error)
	RemoveUser(ctx context.Context, in *RemoveUserRequest, opts ...grpc.CallOption) (*CommandResult, error)
	RequirePasswordChange(ctx context.Context, in *RequirePasswordChangeRequest, opts ...grpc.CallOption) (*CommandResult, error)
	SetInitialAdminPassword(ctx context.Context, in *SetInitialAdminPasswordRequest, opts ...grpc.CallOption) (*CommandResult, error)
}

type usersClient struct {
	cc grpc.ClientConnInterface
}

func NewUsersClient(cc grpc.ClientConnInterface) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, Users_AddUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) AllUsers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResult_IEnumerable_UserResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Users_ServiceDesc.Streams[0], Users_AllUsers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, QueryResult_IEnumerable_UserResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Users_AllUsersClient = grpc.ServerStreamingClient[QueryResult_IEnumerable_UserResponse]

func (c *usersClient) ChangeUserPassword(ctx context.Context, in *ChangeUserPasswordRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, Users_ChangeUserPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*QueryResult_AdminPasswordStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResult_AdminPasswordStatusResponse)
	err := c.cc.Invoke(ctx, Users_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) RemoveUser(ctx context.Context, in *RemoveUserRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, Users_RemoveUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) RequirePasswordChange(ctx context.Context, in *RequirePasswordChangeRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, Users_RequirePasswordChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) SetInitialAdminPassword(ctx context.Context, in *SetInitialAdminPasswordRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, Users_SetInitialAdminPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServer is the server API for Users service.
// All implementations must embed UnimplementedUsersServer
// for forward compatibility.
type UsersServer interface {
	AddUser(context.Context, *AddUserRequest) (*CommandResult, error)
	AllUsers(*emptypb.Empty, grpc.ServerStreamingServer[QueryResult_IEnumerable_UserResponse]) error
	ChangeUserPassword(context.Context, *ChangeUserPasswordRequest) (*CommandResult, error)
	GetStatus(context.Context, *emptypb.Empty) (*QueryResult_AdminPasswordStatusResponse, error)
	RemoveUser(context.Context, *RemoveUserRequest) (*CommandResult, error)
	RequirePasswordChange(context.Context, *RequirePasswordChangeRequest) (*CommandResult, error)
	SetInitialAdminPassword(context.Context, *SetInitialAdminPasswordRequest) (*CommandResult, error)
	mustEmbedUnimplementedUsersServer()
}

// UnimplementedUsersServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUsersServer struct{}

func (UnimplementedUsersServer) AddUser(context.Context, *AddUserRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUser not implemented")
}
func (UnimplementedUsersServer) AllUsers(*emptypb.Empty, grpc.ServerStreamingServer[QueryResult_IEnumerable_UserResponse]) error {
	return status.Error(codes.Unimplemented, "method AllUsers not implemented")
}
func (UnimplementedUsersServer) ChangeUserPassword(context.Context, *ChangeUserPasswordRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeUserPassword not implemented")
}
func (UnimplementedUsersServer) GetStatus(context.Context, *emptypb.Empty) (*QueryResult_AdminPasswordStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedUsersServer) RemoveUser(context.Context, *RemoveUserRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveUser not implemented")
}
func (UnimplementedUsersServer) RequirePasswordChange(context.Context, *RequirePasswordChangeRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RequirePasswordChange not implemented")
}
func (UnimplementedUsersServer) SetInitialAdminPassword(context.Context, *SetInitialAdminPasswordRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SetInitialAdminPassword not implemented")
}
func (UnimplementedUsersServer) mustEmbedUnimplementedUsersServer() {}
func (UnimplementedUsersServer) testEmbeddedByValue()               {}

// UnsafeUsersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsersServer will
// result in compilation errors.
type UnsafeUsersServer interface {
	mustEmbedUnimplementedUsersServer()
}

func RegisterUsersServer(s grpc.ServiceRegistrar, srv UsersServer) {
	// If the following call panics, it indicates UnimplementedUsersServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Users_ServiceDesc, srv)
}

func _Users_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_AddUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_AllUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UsersServer).AllUsers(m, &grpc.GenericServerStream[emptypb.Empty, QueryResult_IEnumerable_UserResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Users_AllUsersServer = grpc.ServerStreamingServer[QueryResult_IEnumerable_UserResponse]

func _Users_ChangeUserPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeUserPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).ChangeUserPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_ChangeUserPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).ChangeUserPassword(ctx, req.(*ChangeUserPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_RemoveUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).RemoveUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_RemoveUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).RemoveUser(ctx, req.(*RemoveUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_RequirePasswordChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequirePasswordChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).RequirePasswordChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_RequirePasswordChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).RequirePasswordChange(ctx, req.(*RequirePasswordChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_SetInitialAdminPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetInitialAdminPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).SetInitialAdminPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_SetInitialAdminPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).SetInitialAdminPassword(ctx, req.(*SetInitialAdminPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Users_ServiceDesc is the grpc.ServiceDesc for Users service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Users_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Cratis.Chronicle.Contracts.Security.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUser",
			Handler:    _Users_AddUser_Handler,
		},
		{
			MethodName: "ChangeUserPassword",
			Handler:    _Users_ChangeUserPassword_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _Users_GetStatus_Handler,
		},
		{
			MethodName: "RemoveUser",
			Handler:    _Users_RemoveUser_Handler,
		},
		{
			MethodName: "RequirePasswordChange",
			Handler:    _Users_RequirePasswordChange_Handler,
		},
		{
			MethodName: "SetInitialAdminPassword",
			Handler:    _Users_SetInitialAdminPassword_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AllUsers",
			Handler:       _Users_AllUsers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "security.proto",
}
