// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: observation_eventstoresubscriptions.proto

package eventstoresubscriptions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddEventStoreSubscriptions struct {
	state            protoimpl.MessageState              `protogen:"open.v1"`
	TargetEventStore string                              `protobuf:"bytes,1,opt,name=TargetEventStore,proto3" json:"TargetEventStore,omitempty"`
	Subscriptions    []*EventStoreSubscriptionDefinition `protobuf:"bytes,2,rep,name=Subscriptions,proto3" json:"Subscriptions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AddEventStoreSubscriptions) Reset() {
	*x = AddEventStoreSubscriptions{}
	mi := &file_observation_eventstoresubscriptions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEventStoreSubscriptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEventStoreSubscriptions) ProtoMessage() {}

func (x *AddEventStoreSubscriptions) ProtoReflect() protoreflect.Message {
	mi := &file_observation_eventstoresubscriptions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEventStoreSubscriptions.ProtoReflect.Descriptor instead.
func (*AddEventStoreSubscriptions) Descriptor() ([]byte, []int) {
	return file_observation_eventstoresubscriptions_proto_rawDescGZIP(), []int{0}
}

func (x *AddEventStoreSubscriptions) GetTargetEventStore() string {
	if x != nil {
		return x.TargetEventStore
	}
	return ""
}

func (x *AddEventStoreSubscriptions) GetSubscriptions() []*EventStoreSubscriptionDefinition {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type EventStoreSubscriptionDefinition struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Identifier       string                 `protobuf:"bytes,1,opt,name=Identifier,proto3" json:"Identifier,omitempty"`
	SourceEventStore string                 `protobuf:"bytes,2,opt,name=SourceEventStore,proto3" json:"SourceEventStore,omitempty"`
	EventTypes       []*EventType           `protobuf:"bytes,3,rep,name=EventTypes,proto3" json:"EventTypes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventStoreSubscriptionDefinition) Reset() {
	*x = EventStoreSubscriptionDefinition{}
	mi := &file_observation_eventstoresubscriptions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStoreSubscriptionDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStoreSubscriptionDefinition) ProtoMessage() {}

func (x *EventStoreSubscriptionDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_observation_eventstoresubscriptions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStoreSubscriptionDefinition.ProtoReflect.Descriptor instead.
func (*EventStoreSubscriptionDefinition) Descriptor() ([]byte, []int) {
	return file_observation_eventstoresubscriptions_proto_rawDescGZIP(), []int{1}
}

func (x *EventStoreSubscriptionDefinition) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *EventStoreSubscriptionDefinition) GetSourceEventStore() string {
	if x != nil {
		return x.SourceEventStore
	}
	return ""
}

func (x *EventStoreSubscriptionDefinition) GetEventTypes() []*EventType {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type EventType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Generation    uint32                 `protobuf:"varint,2,opt,name=Generation,proto3" json:"Generation,omitempty"`
	Tombstone     bool                   `protobuf:"varint,3,opt,name=Tombstone,proto3" json:"Tombstone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventType) Reset() {
	*x = EventType{}
	mi := &file_observation_eventstoresubscriptions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventType) ProtoMessage() {}

func (x *EventType) ProtoReflect() protoreflect.Message {
	mi := &file_observation_eventstoresubscriptions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventType.ProtoReflect.Descriptor instead.
func (*EventType) Descriptor() ([]byte, []int) {
	return file_observation_eventstoresubscriptions_proto_rawDescGZIP(), []int{2}
}

func (x *EventType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventType) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *EventType) GetTombstone() bool {
	if x != nil {
		return x.Tombstone
	}
	return false
}

type GetEventStoreSubscriptionsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TargetEventStore string                 `protobuf:"bytes,1,opt,name=TargetEventStore,proto3" json:"TargetEventStore,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetEventStoreSubscriptionsRequest) Reset() {
	*x = GetEventStoreSubscriptionsRequest{}
	mi := &file_observation_eventstoresubscriptions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventStoreSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventStoreSubscriptionsRequest) ProtoMessage() {}

func (x *GetEventStoreSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_observation_eventstoresubscriptions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventStoreSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*GetEventStoreSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_observation_eventstoresubscriptions_proto_rawDescGZIP(), []int{3}
}

func (x *GetEventStoreSubscriptionsRequest) GetTargetEventStore() string {
	if x != nil {
		return x.TargetEventStore
	}
	return ""
}

type IEnumerable_EventStoreSubscriptionDefinition struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Items         []*EventStoreSubscriptionDefinition `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IEnumerable_EventStoreSubscriptionDefinition) Reset() {
	*x = IEnumerable_EventStoreSubscriptionDefinition{}
	mi := &file_observation_eventstoresubscriptions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IEnumerable_EventStoreSubscriptionDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IEnumerable_EventStoreSubscriptionDefinition) ProtoMessage() {}

func (x *IEnumerable_EventStoreSubscriptionDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_observation_eventstoresubscriptions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IEnumerable_EventStoreSubscriptionDefinition.ProtoReflect.Descriptor instead.
func (*IEnumerable_EventStoreSubscriptionDefinition) Descriptor() ([]byte, []int) {
	return file_observation_eventstoresubscriptions_proto_rawDescGZIP(), []int{4}
}

func (x *IEnumerable_EventStoreSubscriptionDefinition) GetItems() []*EventStoreSubscriptionDefinition {
	if x != nil {
		return x.Items
	}
	return nil
}

type RemoveEventStoreSubscriptions struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TargetEventStore string                 `protobuf:"bytes,1,opt,name=TargetEventStore,proto3" json:"TargetEventStore,omitempty"`
	SubscriptionIds  []string               `protobuf:"bytes,2,rep,name=SubscriptionIds,proto3" json:"SubscriptionIds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RemoveEventStoreSubscriptions) Reset() {
	*x = RemoveEventStoreSubscriptions{}
	mi := &file_observation_eventstoresubscriptions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveEventStoreSubscriptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveEventStoreSubscriptions) ProtoMessage() {}

func (x *RemoveEventStoreSubscriptions) ProtoReflect() protoreflect.Message {
	mi := &file_observation_eventstoresubscriptions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveEventStoreSubscriptions.ProtoReflect.Descriptor instead.
func (*RemoveEventStoreSubscriptions) Descriptor() ([]byte, []int) {
	return file_observation_eventstoresubscriptions_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveEventStoreSubscriptions) GetTargetEventStore() string {
	if x != nil {
		return x.TargetEventStore
	}
	return ""
}

func (x *RemoveEventStoreSubscriptions) GetSubscriptionIds() []string {
	if x != nil {
		return x.SubscriptionIds
	}
	return nil
}

var File_observation_eventstoresubscriptions_proto protoreflect.FileDescriptor

const file_observation_eventstoresubscriptions_proto_rawDesc = "" +
	"\n" +
	")observation_eventstoresubscriptions.proto\x12>Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions\x1a\x1bgoogle/protobuf/empty.proto\"\xd1\x01\n" +
	"\x1aAddEventStoreSubscriptions\x12*\n" +
	"\x10TargetEventStore\x18\x01 \x01(\tR\x10TargetEventStore\x12\x86\x01\n" +
	"\rSubscriptions\x18\x02 \x03(\v2`.Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.EventStoreSubscriptionDefinitionR\rSubscriptions\"\xd9\x01\n" +
	" EventStoreSubscriptionDefinition\x12\x1e\n" +
	"\n" +
	"Identifier\x18\x01 \x01(\tR\n" +
	"Identifier\x12*\n" +
	"\x10SourceEventStore\x18\x02 \x01(\tR\x10SourceEventStore\x12i\n" +
	"\n" +
	"EventTypes\x18\x03 \x03(\v2I.Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.EventTypeR\n" +
	"EventTypes\"Y\n" +
	"\tEventType\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x1e\n" +
	"\n" +
	"Generation\x18\x02 \x01(\rR\n" +
	"Generation\x12\x1c\n" +
	"\tTombstone\x18\x03 \x01(\bR\tTombstone\"O\n" +
	"!GetEventStoreSubscriptionsRequest\x12*\n" +
	"\x10TargetEventStore\x18\x01 \x01(\tR\x10TargetEventStore\"\xa6\x01\n" +
	",IEnumerable_EventStoreSubscriptionDefinition\x12v\n" +
	"\x05items\x18\x01 \x03(\v2`.Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.EventStoreSubscriptionDefinitionR\x05items\"u\n" +
	"\x1dRemoveEventStoreSubscriptions\x12*\n" +
	"\x10TargetEventStore\x18\x01 \x01(\tR\x10TargetEventStore\x12(\n" +
	"\x0fSubscriptionIds\x18\x02 \x03(\tR\x0fSubscriptionIds2\xfb\x03\n" +
	"\x17EventStoreSubscriptions\x12y\n" +
	"\x03Add\x12Z.Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.AddEventStoreSubscriptions\x1a\x16.google.protobuf.Empty\x12\xe3\x01\n" +
	"\x10GetSubscriptions\x12a.Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.GetEventStoreSubscriptionsRequest\x1al.Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.IEnumerable_EventStoreSubscriptionDefinition\x12\x7f\n" +
	"\x06Remove\x12].Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.RemoveEventStoreSubscriptions\x1a\x16.google.protobuf.EmptyB\xd9\x03\n" +
	"Bcom.Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptionsB'ObservationEventstoresubscriptionsProtoP\x01ZLgithub.com/cratis/chronicle.go/contracts/observation/eventstoresubscriptions\xa2\x02\x05CCCOE\xaa\x02>Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions\xca\x02>Cratis\\Chronicle\\Contracts\\Observation\\EventStoreSubscriptions\xe2\x02JCratis\\Chronicle\\Contracts\\Observation\\EventStoreSubscriptions\\GPBMetadata\xea\x02BCratis::Chronicle::Contracts::Observation::EventStoreSubscriptionsb\x06proto3"

var (
	file_observation_eventstoresubscriptions_proto_rawDescOnce sync.Once
	file_observation_eventstoresubscriptions_proto_rawDescData []byte
)

func file_observation_eventstoresubscriptions_proto_rawDescGZIP() []byte {
	file_observation_eventstoresubscriptions_proto_rawDescOnce.Do(func() {
		file_observation_eventstoresubscriptions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_observation_eventstoresubscriptions_proto_rawDesc), len(file_observation_eventstoresubscriptions_proto_rawDesc)))
	})
	return file_observation_eventstoresubscriptions_proto_rawDescData
}

var file_observation_eventstoresubscriptions_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_observation_eventstoresubscriptions_proto_goTypes = []any{
	(*AddEventStoreSubscriptions)(nil),                   // 0: Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.AddEventStoreSubscriptions
	(*EventStoreSubscriptionDefinition)(nil),             // 1: Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.EventStoreSubscriptionDefinition
	(*EventType)(nil),                                    // 2: Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.EventType
	(*GetEventStoreSubscriptionsRequest)(nil),            // 3: Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.GetEventStoreSubscriptionsRequest
	(*IEnumerable_EventStoreSubscriptionDefinition)(nil), // 4: Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.IEnumerable_EventStoreSubscriptionDefinition
	(*RemoveEventStoreSubscriptions)(nil),                // 5: Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.RemoveEventStoreSubscriptions
	(*emptypb.Empty)(nil),                                // 6: google.protobuf.Empty
}
var file_observation_eventstoresubscriptions_proto_depIdxs = []int32{
	1, // 0: Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.AddEventStoreSubscriptions.Subscriptions:type_name -> Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.EventStoreSubscriptionDefinition
	2, // 1: Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.EventStoreSubscriptionDefinition.EventTypes:type_name -> Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.EventType
	1, // 2: Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.IEnumerable_EventStoreSubscriptionDefinition.items:type_name -> Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.EventStoreSubscriptionDefinition
	0, // 3: Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.EventStoreSubscriptions.Add:input_type -> Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.AddEventStoreSubscriptions
	3, // 4: Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.EventStoreSubscriptions.GetSubscriptions:input_type -> Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.GetEventStoreSubscriptionsRequest
	5, // 5: Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.EventStoreSubscriptions.Remove:input_type -> Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.RemoveEventStoreSubscriptions
	6, // 6: Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.EventStoreSubscriptions.Add:output_type -> google.protobuf.Empty
	4, // 7: Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.EventStoreSubscriptions.GetSubscriptions:output_type -> Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.IEnumerable_EventStoreSubscriptionDefinition
	6, // 8: Cratis.Chronicle.Contracts.Observation.EventStoreSubscriptions.EventStoreSubscriptions.Remove:output_type -> google.protobuf.Empty
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_observation_eventstoresubscriptions_proto_init() }
func file_observation_eventstoresubscriptions_proto_init() {
	if File_observation_eventstoresubscriptions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_observation_eventstoresubscriptions_proto_rawDesc), len(file_observation_eventstoresubscriptions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_observation_eventstoresubscriptions_proto_goTypes,
		DependencyIndexes: file_observation_eventstoresubscriptions_proto_depIdxs,
		MessageInfos:      file_observation_eventstoresubscriptions_proto_msgTypes,
	}.Build()
	File_observation_eventstoresubscriptions_proto = out.File
	file_observation_eventstoresubscriptions_proto_goTypes = nil
	file_observation_eventstoresubscriptions_proto_depIdxs = nil
}
