// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: externalservices.proto

package externalservices

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExternalServices_AddExternalService_FullMethodName      = "/Cratis.Chronicle.Contracts.ExternalServices.ExternalServices/AddExternalService"
	ExternalServices_AddExternalServices_FullMethodName     = "/Cratis.Chronicle.Contracts.ExternalServices.ExternalServices/AddExternalServices"
	ExternalServices_GetExternalServices_FullMethodName     = "/Cratis.Chronicle.Contracts.ExternalServices.ExternalServices/GetExternalServices"
	ExternalServices_ObserveExternalServices_FullMethodName = "/Cratis.Chronicle.Contracts.ExternalServices.ExternalServices/ObserveExternalServices"
	ExternalServices_RemoveExternalService_FullMethodName   = "/Cratis.Chronicle.Contracts.ExternalServices.ExternalServices/RemoveExternalService"
	ExternalServices_RemoveExternalServices_FullMethodName  = "/Cratis.Chronicle.Contracts.ExternalServices.ExternalServices/RemoveExternalServices"
)

// ExternalServicesClient is the client API for ExternalServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExternalServicesClient interface {
	AddExternalService(ctx context.Context, in *AddExternalServiceRequest, opts ...grpc.CallOption) (*CommandResult, error)
	AddExternalServices(ctx context.Context, in *AddExternalServicesRequest, opts ...grpc.CallOption) (*CommandResult, error)
	GetExternalServices(ctx context.Context, in *GetExternalServicesRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_ExternalServiceResponse, error)
	ObserveExternalServices(ctx context.Context, in *ObserveExternalServicesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResult_IEnumerable_ExternalServiceResponse], error)
	RemoveExternalService(ctx context.Context, in *RemoveExternalServiceRequest, opts ...grpc.CallOption) (*CommandResult, error)
	RemoveExternalServices(ctx context.Context, in *RemoveExternalServicesRequest, opts ...grpc.CallOption) (*CommandResult, error)
}

type externalServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewExternalServicesClient(cc grpc.ClientConnInterface) ExternalServicesClient {
	return &externalServicesClient{cc}
}

func (c *externalServicesClient) AddExternalService(ctx context.Context, in *AddExternalServiceRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, ExternalServices_AddExternalService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalServicesClient) AddExternalServices(ctx context.Context, in *AddExternalServicesRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, ExternalServices_AddExternalServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalServicesClient) GetExternalServices(ctx context.Context, in *GetExternalServicesRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_ExternalServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResult_IEnumerable_ExternalServiceResponse)
	err := c.cc.Invoke(ctx, ExternalServices_GetExternalServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalServicesClient) ObserveExternalServices(ctx context.Context, in *ObserveExternalServicesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResult_IEnumerable_ExternalServiceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExternalServices_ServiceDesc.Streams[0], ExternalServices_ObserveExternalServices_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ObserveExternalServicesRequest, QueryResult_IEnumerable_ExternalServiceResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExternalServices_ObserveExternalServicesClient = grpc.ServerStreamingClient[QueryResult_IEnumerable_ExternalServiceResponse]

func (c *externalServicesClient) RemoveExternalService(ctx context.Context, in *RemoveExternalServiceRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, ExternalServices_RemoveExternalService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalServicesClient) RemoveExternalServices(ctx context.Context, in *RemoveExternalServicesRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, ExternalServices_RemoveExternalServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExternalServicesServer is the server API for ExternalServices service.
// All implementations must embed UnimplementedExternalServicesServer
// for forward compatibility.
type ExternalServicesServer interface {
	AddExternalService(context.Context, *AddExternalServiceRequest) (*CommandResult, error)
	AddExternalServices(context.Context, *AddExternalServicesRequest) (*CommandResult, error)
	GetExternalServices(context.Context, *GetExternalServicesRequest) (*QueryResult_IEnumerable_ExternalServiceResponse, error)
	ObserveExternalServices(*ObserveExternalServicesRequest, grpc.ServerStreamingServer[QueryResult_IEnumerable_ExternalServiceResponse]) error
	RemoveExternalService(context.Context, *RemoveExternalServiceRequest) (*CommandResult, error)
	RemoveExternalServices(context.Context, *RemoveExternalServicesRequest) (*CommandResult, error)
	mustEmbedUnimplementedExternalServicesServer()
}

// UnimplementedExternalServicesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExternalServicesServer struct{}

func (UnimplementedExternalServicesServer) AddExternalService(context.Context, *AddExternalServiceRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method AddExternalService not implemented")
}
func (UnimplementedExternalServicesServer) AddExternalServices(context.Context, *AddExternalServicesRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method AddExternalServices not implemented")
}
func (UnimplementedExternalServicesServer) GetExternalServices(context.Context, *GetExternalServicesRequest) (*QueryResult_IEnumerable_ExternalServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExternalServices not implemented")
}
func (UnimplementedExternalServicesServer) ObserveExternalServices(*ObserveExternalServicesRequest, grpc.ServerStreamingServer[QueryResult_IEnumerable_ExternalServiceResponse]) error {
	return status.Error(codes.Unimplemented, "method ObserveExternalServices not implemented")
}
func (UnimplementedExternalServicesServer) RemoveExternalService(context.Context, *RemoveExternalServiceRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveExternalService not implemented")
}
func (UnimplementedExternalServicesServer) RemoveExternalServices(context.Context, *RemoveExternalServicesRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveExternalServices not implemented")
}
func (UnimplementedExternalServicesServer) mustEmbedUnimplementedExternalServicesServer() {}
func (UnimplementedExternalServicesServer) testEmbeddedByValue()                          {}

// UnsafeExternalServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExternalServicesServer will
// result in compilation errors.
type UnsafeExternalServicesServer interface {
	mustEmbedUnimplementedExternalServicesServer()
}

func RegisterExternalServicesServer(s grpc.ServiceRegistrar, srv ExternalServicesServer) {
	// If the following call panics, it indicates UnimplementedExternalServicesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExternalServices_ServiceDesc, srv)
}

func _ExternalServices_AddExternalService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddExternalServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServicesServer).AddExternalService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalServices_AddExternalService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServicesServer).AddExternalService(ctx, req.(*AddExternalServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalServices_AddExternalServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddExternalServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServicesServer).AddExternalServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalServices_AddExternalServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServicesServer).AddExternalServices(ctx, req.(*AddExternalServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalServices_GetExternalServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExternalServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServicesServer).GetExternalServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalServices_GetExternalServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServicesServer).GetExternalServices(ctx, req.(*GetExternalServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalServices_ObserveExternalServices_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ObserveExternalServicesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExternalServicesServer).ObserveExternalServices(m, &grpc.GenericServerStream[ObserveExternalServicesRequest, QueryResult_IEnumerable_ExternalServiceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExternalServices_ObserveExternalServicesServer = grpc.ServerStreamingServer[QueryResult_IEnumerable_ExternalServiceResponse]

func _ExternalServices_RemoveExternalService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveExternalServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServicesServer).RemoveExternalService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalServices_RemoveExternalService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServicesServer).RemoveExternalService(ctx, req.(*RemoveExternalServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalServices_RemoveExternalServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveExternalServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalServicesServer).RemoveExternalServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalServices_RemoveExternalServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalServicesServer).RemoveExternalServices(ctx, req.(*RemoveExternalServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExternalServices_ServiceDesc is the grpc.ServiceDesc for ExternalServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExternalServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Cratis.Chronicle.Contracts.ExternalServices.ExternalServices",
	HandlerType: (*ExternalServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddExternalService",
			Handler:    _ExternalServices_AddExternalService_Handler,
		},
		{
			MethodName: "AddExternalServices",
			Handler:    _ExternalServices_AddExternalServices_Handler,
		},
		{
			MethodName: "GetExternalServices",
			Handler:    _ExternalServices_GetExternalServices_Handler,
		},
		{
			MethodName: "RemoveExternalService",
			Handler:    _ExternalServices_RemoveExternalService_Handler,
		},
		{
			MethodName: "RemoveExternalServices",
			Handler:    _ExternalServices_RemoveExternalServices_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ObserveExternalServices",
			Handler:       _ExternalServices_ObserveExternalServices_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "externalservices.proto",
}
