// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: externalservices.proto

package externalservices

import (
	bcl "github.com/cratis/chronicle.go/contracts/bcl"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizationType int32

const (
	AuthorizationType_None   AuthorizationType = 0
	AuthorizationType_Basic  AuthorizationType = 1
	AuthorizationType_Bearer AuthorizationType = 2
	AuthorizationType_OAuth  AuthorizationType = 3
)

// Enum value maps for AuthorizationType.
var (
	AuthorizationType_name = map[int32]string{
		0: "None",
		1: "Basic",
		2: "Bearer",
		3: "OAuth",
	}
	AuthorizationType_value = map[string]int32{
		"None":   0,
		"Basic":  1,
		"Bearer": 2,
		"OAuth":  3,
	}
)

func (x AuthorizationType) Enum() *AuthorizationType {
	p := new(AuthorizationType)
	*p = x
	return p
}

func (x AuthorizationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthorizationType) Descriptor() protoreflect.EnumDescriptor {
	return file_externalservices_proto_enumTypes[0].Descriptor()
}

func (AuthorizationType) Type() protoreflect.EnumType {
	return &file_externalservices_proto_enumTypes[0]
}

func (x AuthorizationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthorizationType.Descriptor instead.
func (AuthorizationType) EnumDescriptor() ([]byte, []int) {
	return file_externalservices_proto_rawDescGZIP(), []int{0}
}

type ExternalServiceEndpointType int32

const (
	ExternalServiceEndpointType_Http       ExternalServiceEndpointType = 0
	ExternalServiceEndpointType_MsSql      ExternalServiceEndpointType = 1
	ExternalServiceEndpointType_PostgreSql ExternalServiceEndpointType = 2
)

// Enum value maps for ExternalServiceEndpointType.
var (
	ExternalServiceEndpointType_name = map[int32]string{
		0: "Http",
		1: "MsSql",
		2: "PostgreSql",
	}
	ExternalServiceEndpointType_value = map[string]int32{
		"Http":       0,
		"MsSql":      1,
		"PostgreSql": 2,
	}
)

func (x ExternalServiceEndpointType) Enum() *ExternalServiceEndpointType {
	p := new(ExternalServiceEndpointType)
	*p = x
	return p
}

func (x ExternalServiceEndpointType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExternalServiceEndpointType) Descriptor() protoreflect.EnumDescriptor {
	return file_externalservices_proto_enumTypes[1].Descriptor()
}

func (ExternalServiceEndpointType) Type() protoreflect.EnumType {
	return &file_externalservices_proto_enumTypes[1]
}

func (x ExternalServiceEndpointType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExternalServiceEndpointType.Descriptor instead.
func (ExternalServiceEndpointType) EnumDescriptor() ([]byte, []int) {
	return file_externalservices_proto_rawDescGZIP(), []int{1}
}

type ValidationResultSeverity int32

const (
	ValidationResultSeverity_Unknown     ValidationResultSeverity = 0
	ValidationResultSeverity_Information ValidationResultSeverity = 1
	ValidationResultSeverity_Warning     ValidationResultSeverity = 2
	ValidationResultSeverity_Error       ValidationResultSeverity = 3
)

// Enum value maps for ValidationResultSeverity.
var (
	ValidationResultSeverity_name = map[int32]string{
		0: "Unknown",
		1: "Information",
		2: "Warning",
		3: "Error",
	}
	ValidationResultSeverity_value = map[string]int32{
		"Unknown":     0,
		"Information": 1,
		"Warning":     2,
		"Error":       3,
	}
)

func (x ValidationResultSeverity) Enum() *ValidationResultSeverity {
	p := new(ValidationResultSeverity)
	*p = x
	return p
}

func (x ValidationResultSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidationResultSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_externalservices_proto_enumTypes[2].Descriptor()
}

func (ValidationResultSeverity) Type() protoreflect.EnumType {
	return &file_externalservices_proto_enumTypes[2]
}

func (x ValidationResultSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidationResultSeverity.Descriptor instead.
func (ValidationResultSeverity) EnumDescriptor() ([]byte, []int) {
	return file_externalservices_proto_rawDescGZIP(), []int{2}
}

type AddExternalServiceRequest struct {
	state             protoimpl.MessageState      `protogen:"open.v1"`
	EventStore        string                      `protobuf:"bytes,1,opt,name=EventStore,proto3" json:"EventStore,omitempty"`
	Id                string                      `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Name              string                      `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	EndpointType      ExternalServiceEndpointType `protobuf:"varint,4,opt,name=EndpointType,proto3,enum=Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceEndpointType" json:"EndpointType,omitempty"`
	Url               string                      `protobuf:"bytes,5,opt,name=Url,proto3" json:"Url,omitempty"`
	AuthorizationType AuthorizationType           `protobuf:"varint,6,opt,name=AuthorizationType,proto3,enum=Cratis.Chronicle.Contracts.ExternalServices.AuthorizationType" json:"AuthorizationType,omitempty"`
	BasicUsername     string                      `protobuf:"bytes,7,opt,name=BasicUsername,proto3" json:"BasicUsername,omitempty"`
	BasicPassword     string                      `protobuf:"bytes,8,opt,name=BasicPassword,proto3" json:"BasicPassword,omitempty"`
	BearerToken       string                      `protobuf:"bytes,9,opt,name=BearerToken,proto3" json:"BearerToken,omitempty"`
	OAuthAuthority    string                      `protobuf:"bytes,10,opt,name=OAuthAuthority,proto3" json:"OAuthAuthority,omitempty"`
	OAuthClientId     string                      `protobuf:"bytes,11,opt,name=OAuthClientId,proto3" json:"OAuthClientId,omitempty"`
	OAuthClientSecret string                      `protobuf:"bytes,12,opt,name=OAuthClientSecret,proto3" json:"OAuthClientSecret,omitempty"`
	Headers           map[string]string           `protobuf:"bytes,13,rep,name=Headers,proto3" json:"Headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Host              string                      `protobuf:"bytes,14,opt,name=Host,proto3" json:"Host,omitempty"`
	Port              int32                       `protobuf:"varint,15,opt,name=Port,proto3" json:"Port,omitempty"`
	Database          string                      `protobuf:"bytes,16,opt,name=Database,proto3" json:"Database,omitempty"`
	Username          string                      `protobuf:"bytes,17,opt,name=Username,proto3" json:"Username,omitempty"`
	Password          string                      `protobuf:"bytes,18,opt,name=Password,proto3" json:"Password,omitempty"`
	Options           map[string]string           `protobuf:"bytes,19,rep,name=Options,proto3" json:"Options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddExternalServiceRequest) Reset() {
	*x = AddExternalServiceRequest{}
	mi := &file_externalservices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddExternalServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddExternalServiceRequest) ProtoMessage() {}

func (x *AddExternalServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_externalservices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddExternalServiceRequest.ProtoReflect.Descriptor instead.
func (*AddExternalServiceRequest) Descriptor() ([]byte, []int) {
	return file_externalservices_proto_rawDescGZIP(), []int{0}
}

func (x *AddExternalServiceRequest) GetEventStore() string {
	if x != nil {
		return x.EventStore
	}
	return ""
}

func (x *AddExternalServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddExternalServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddExternalServiceRequest) GetEndpointType() ExternalServiceEndpointType {
	if x != nil {
		return x.EndpointType
	}
	return ExternalServiceEndpointType_Http
}

func (x *AddExternalServiceRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AddExternalServiceRequest) GetAuthorizationType() AuthorizationType {
	if x != nil {
		return x.AuthorizationType
	}
	return AuthorizationType_None
}

func (x *AddExternalServiceRequest) GetBasicUsername() string {
	if x != nil {
		return x.BasicUsername
	}
	return ""
}

func (x *AddExternalServiceRequest) GetBasicPassword() string {
	if x != nil {
		return x.BasicPassword
	}
	return ""
}

func (x *AddExternalServiceRequest) GetBearerToken() string {
	if x != nil {
		return x.BearerToken
	}
	return ""
}

func (x *AddExternalServiceRequest) GetOAuthAuthority() string {
	if x != nil {
		return x.OAuthAuthority
	}
	return ""
}

func (x *AddExternalServiceRequest) GetOAuthClientId() string {
	if x != nil {
		return x.OAuthClientId
	}
	return ""
}

func (x *AddExternalServiceRequest) GetOAuthClientSecret() string {
	if x != nil {
		return x.OAuthClientSecret
	}
	return ""
}

func (x *AddExternalServiceRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *AddExternalServiceRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *AddExternalServiceRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *AddExternalServiceRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *AddExternalServiceRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AddExternalServiceRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AddExternalServiceRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type AddExternalServicesRequest struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	EventStore       string                       `protobuf:"bytes,1,opt,name=EventStore,proto3" json:"EventStore,omitempty"`
	ExternalServices []*ExternalServiceDefinition `protobuf:"bytes,2,rep,name=ExternalServices,proto3" json:"ExternalServices,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AddExternalServicesRequest) Reset() {
	*x = AddExternalServicesRequest{}
	mi := &file_externalservices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddExternalServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddExternalServicesRequest) ProtoMessage() {}

func (x *AddExternalServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_externalservices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddExternalServicesRequest.ProtoReflect.Descriptor instead.
func (*AddExternalServicesRequest) Descriptor() ([]byte, []int) {
	return file_externalservices_proto_rawDescGZIP(), []int{1}
}

func (x *AddExternalServicesRequest) GetEventStore() string {
	if x != nil {
		return x.EventStore
	}
	return ""
}

func (x *AddExternalServicesRequest) GetExternalServices() []*ExternalServiceDefinition {
	if x != nil {
		return x.ExternalServices
	}
	return nil
}

type BasicAuthorization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicAuthorization) Reset() {
	*x = BasicAuthorization{}
	mi := &file_externalservices_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicAuthorization) ProtoMessage() {}

func (x *BasicAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_externalservices_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicAuthorization.ProtoReflect.Descriptor instead.
func (*BasicAuthorization) Descriptor() ([]byte, []int) {
	return file_externalservices_proto_rawDescGZIP(), []int{2}
}

func (x *BasicAuthorization) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BasicAuthorization) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type BearerTokenAuthorization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BearerTokenAuthorization) Reset() {
	*x = BearerTokenAuthorization{}
	mi := &file_externalservices_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BearerTokenAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BearerTokenAuthorization) ProtoMessage() {}

func (x *BearerTokenAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_externalservices_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BearerTokenAuthorization.ProtoReflect.Descriptor instead.
func (*BearerTokenAuthorization) Descriptor() ([]byte, []int) {
	return file_externalservices_proto_rawDescGZIP(), []int{3}
}

func (x *BearerTokenAuthorization) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CommandResult struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId              *bcl.Guid              `protobuf:"bytes,1,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"` // default value could not be applied: 00000000-0000-0000-0000-000000000000
	IsAuthorized               bool                   `protobuf:"varint,2,opt,name=IsAuthorized,proto3" json:"IsAuthorized,omitempty"`
	ValidationResults          []*ValidationResult    `protobuf:"bytes,3,rep,name=ValidationResults,proto3" json:"ValidationResults,omitempty"`
	ExceptionMessages          []string               `protobuf:"bytes,4,rep,name=ExceptionMessages,proto3" json:"ExceptionMessages,omitempty"`
	ExceptionStackTrace        string                 `protobuf:"bytes,5,opt,name=ExceptionStackTrace,proto3" json:"ExceptionStackTrace,omitempty"`
	AuthorizationFailureReason string                 `protobuf:"bytes,6,opt,name=AuthorizationFailureReason,proto3" json:"AuthorizationFailureReason,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_externalservices_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_externalservices_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_externalservices_proto_rawDescGZIP(), []int{4}
}

func (x *CommandResult) GetCorrelationId() *bcl.Guid {
	if x != nil {
		return x.CorrelationId
	}
	return nil
}

func (x *CommandResult) GetIsAuthorized() bool {
	if x != nil {
		return x.IsAuthorized
	}
	return false
}

func (x *CommandResult) GetValidationResults() []*ValidationResult {
	if x != nil {
		return x.ValidationResults
	}
	return nil
}

func (x *CommandResult) GetExceptionMessages() []string {
	if x != nil {
		return x.ExceptionMessages
	}
	return nil
}

func (x *CommandResult) GetExceptionStackTrace() string {
	if x != nil {
		return x.ExceptionStackTrace
	}
	return ""
}

func (x *CommandResult) GetAuthorizationFailureReason() string {
	if x != nil {
		return x.AuthorizationFailureReason
	}
	return ""
}

type DatabaseEndpointConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=Host,proto3" json:"Host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
	Database      string                 `protobuf:"bytes,3,opt,name=Database,proto3" json:"Database,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=Username,proto3" json:"Username,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=Password,proto3" json:"Password,omitempty"`
	Options       map[string]string      `protobuf:"bytes,6,rep,name=Options,proto3" json:"Options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseEndpointConfiguration) Reset() {
	*x = DatabaseEndpointConfiguration{}
	mi := &file_externalservices_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseEndpointConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseEndpointConfiguration) ProtoMessage() {}

func (x *DatabaseEndpointConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_externalservices_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseEndpointConfiguration.ProtoReflect.Descriptor instead.
func (*DatabaseEndpointConfiguration) Descriptor() ([]byte, []int) {
	return file_externalservices_proto_rawDescGZIP(), []int{5}
}

func (x *DatabaseEndpointConfiguration) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *DatabaseEndpointConfiguration) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DatabaseEndpointConfiguration) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *DatabaseEndpointConfiguration) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DatabaseEndpointConfiguration) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DatabaseEndpointConfiguration) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ExternalServiceDefinition struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            string                   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name          string                   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Endpoint      *ExternalServiceEndpoint `protobuf:"bytes,3,opt,name=Endpoint,proto3" json:"Endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalServiceDefinition) Reset() {
	*x = ExternalServiceDefinition{}
	mi := &file_externalservices_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalServiceDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalServiceDefinition) ProtoMessage() {}

func (x *ExternalServiceDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_externalservices_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalServiceDefinition.ProtoReflect.Descriptor instead.
func (*ExternalServiceDefinition) Descriptor() ([]byte, []int) {
	return file_externalservices_proto_rawDescGZIP(), []int{6}
}

func (x *ExternalServiceDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExternalServiceDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExternalServiceDefinition) GetEndpoint() *ExternalServiceEndpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

type ExternalServiceEndpoint struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Type          ExternalServiceEndpointType    `protobuf:"varint,1,opt,name=Type,proto3,enum=Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceEndpointType" json:"Type,omitempty"`
	Http          *HttpEndpointConfiguration     `protobuf:"bytes,2,opt,name=Http,proto3" json:"Http,omitempty"`
	Database      *DatabaseEndpointConfiguration `protobuf:"bytes,3,opt,name=Database,proto3" json:"Database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalServiceEndpoint) Reset() {
	*x = ExternalServiceEndpoint{}
	mi := &file_externalservices_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalServiceEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalServiceEndpoint) ProtoMessage() {}

func (x *ExternalServiceEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_externalservices_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalServiceEndpoint.ProtoReflect.Descriptor instead.
func (*ExternalServiceEndpoint) Descriptor() ([]byte, []int) {
	return file_externalservices_proto_rawDescGZIP(), []int{7}
}

func (x *ExternalServiceEndpoint) GetType() ExternalServiceEndpointType {
	if x != nil {
		return x.Type
	}
	return ExternalServiceEndpointType_Http
}

func (x *ExternalServiceEndpoint) GetHttp() *HttpEndpointConfiguration {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *ExternalServiceEndpoint) GetDatabase() *DatabaseEndpointConfiguration {
	if x != nil {
		return x.Database
	}
	return nil
}

type ExternalServiceResponse struct {
	state             protoimpl.MessageState      `protogen:"open.v1"`
	Id                string                      `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name              string                      `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	EndpointType      ExternalServiceEndpointType `protobuf:"varint,3,opt,name=EndpointType,proto3,enum=Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceEndpointType" json:"EndpointType,omitempty"`
	Url               string                      `protobuf:"bytes,4,opt,name=Url,proto3" json:"Url,omitempty"`
	AuthorizationType AuthorizationType           `protobuf:"varint,5,opt,name=AuthorizationType,proto3,enum=Cratis.Chronicle.Contracts.ExternalServices.AuthorizationType" json:"AuthorizationType,omitempty"`
	Headers           map[string]string           `protobuf:"bytes,6,rep,name=Headers,proto3" json:"Headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Host              string                      `protobuf:"bytes,7,opt,name=Host,proto3" json:"Host,omitempty"`
	Port              int32                       `protobuf:"varint,8,opt,name=Port,proto3" json:"Port,omitempty"`
	Database          string                      `protobuf:"bytes,9,opt,name=Database,proto3" json:"Database,omitempty"`
	Username          string                      `protobuf:"bytes,10,opt,name=Username,proto3" json:"Username,omitempty"`
	Options           map[string]string           `protobuf:"bytes,11,rep,name=Options,proto3" json:"Options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExternalServiceResponse) Reset() {
	*x = ExternalServiceResponse{}
	mi := &file_externalservices_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalServiceResponse) ProtoMessage() {}

func (x *ExternalServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_externalservices_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalServiceResponse.ProtoReflect.Descriptor instead.
func (*ExternalServiceResponse) Descriptor() ([]byte, []int) {
	return file_externalservices_proto_rawDescGZIP(), []int{8}
}

func (x *ExternalServiceResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExternalServiceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExternalServiceResponse) GetEndpointType() ExternalServiceEndpointType {
	if x != nil {
		return x.EndpointType
	}
	return ExternalServiceEndpointType_Http
}

func (x *ExternalServiceResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ExternalServiceResponse) GetAuthorizationType() AuthorizationType {
	if x != nil {
		return x.AuthorizationType
	}
	return AuthorizationType_None
}

func (x *ExternalServiceResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ExternalServiceResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ExternalServiceResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ExternalServiceResponse) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *ExternalServiceResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ExternalServiceResponse) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type GetExternalServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventStore    string                 `protobuf:"bytes,1,opt,name=EventStore,proto3" json:"EventStore,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExternalServicesRequest) Reset() {
	*x = GetExternalServicesRequest{}
	mi := &file_externalservices_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExternalServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExternalServicesRequest) ProtoMessage() {}

func (x *GetExternalServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_externalservices_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExternalServicesRequest.ProtoReflect.Descriptor instead.
func (*GetExternalServicesRequest) Descriptor() ([]byte, []int) {
	return file_externalservices_proto_rawDescGZIP(), []int{9}
}

func (x *GetExternalServicesRequest) GetEventStore() string {
	if x != nil {
		return x.EventStore
	}
	return ""
}

type HttpEndpointConfiguration struct {
	state         protoimpl.MessageState                                                `protogen:"open.v1"`
	Url           string                                                                `protobuf:"bytes,1,opt,name=Url,proto3" json:"Url,omitempty"`
	Authorization *OneOf_BasicAuthorization_BearerTokenAuthorization_OAuthAuthorization `protobuf:"bytes,2,opt,name=Authorization,proto3" json:"Authorization,omitempty"`
	Headers       map[string]string                                                     `protobuf:"bytes,3,rep,name=Headers,proto3" json:"Headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpEndpointConfiguration) Reset() {
	*x = HttpEndpointConfiguration{}
	mi := &file_externalservices_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpEndpointConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpEndpointConfiguration) ProtoMessage() {}

func (x *HttpEndpointConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_externalservices_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpEndpointConfiguration.ProtoReflect.Descriptor instead.
func (*HttpEndpointConfiguration) Descriptor() ([]byte, []int) {
	return file_externalservices_proto_rawDescGZIP(), []int{10}
}

func (x *HttpEndpointConfiguration) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HttpEndpointConfiguration) GetAuthorization() *OneOf_BasicAuthorization_BearerTokenAuthorization_OAuthAuthorization {
	if x != nil {
		return x.Authorization
	}
	return nil
}

func (x *HttpEndpointConfiguration) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type OAuthAuthorization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=Authority,proto3" json:"Authority,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,3,opt,name=ClientSecret,proto3" json:"ClientSecret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuthAuthorization) Reset() {
	*x = OAuthAuthorization{}
	mi := &file_externalservices_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthAuthorization) ProtoMessage() {}

func (x *OAuthAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_externalservices_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthAuthorization.ProtoReflect.Descriptor instead.
func (*OAuthAuthorization) Descriptor() ([]byte, []int) {
	return file_externalservices_proto_rawDescGZIP(), []int{11}
}

func (x *OAuthAuthorization) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *OAuthAuthorization) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OAuthAuthorization) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

type ObserveExternalServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventStore    string                 `protobuf:"bytes,1,opt,name=EventStore,proto3" json:"EventStore,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserveExternalServicesRequest) Reset() {
	*x = ObserveExternalServicesRequest{}
	mi := &file_externalservices_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveExternalServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveExternalServicesRequest) ProtoMessage() {}

func (x *ObserveExternalServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_externalservices_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveExternalServicesRequest.ProtoReflect.Descriptor instead.
func (*ObserveExternalServicesRequest) Descriptor() ([]byte, []int) {
	return file_externalservices_proto_rawDescGZIP(), []int{12}
}

func (x *ObserveExternalServicesRequest) GetEventStore() string {
	if x != nil {
		return x.EventStore
	}
	return ""
}

type OneOf_BasicAuthorization_BearerTokenAuthorization_OAuthAuthorization struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Value0        *BasicAuthorization       `protobuf:"bytes,1,opt,name=Value0,proto3" json:"Value0,omitempty"`
	Value1        *BearerTokenAuthorization `protobuf:"bytes,2,opt,name=Value1,proto3" json:"Value1,omitempty"`
	Value2        *OAuthAuthorization       `protobuf:"bytes,3,opt,name=Value2,proto3" json:"Value2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneOf_BasicAuthorization_BearerTokenAuthorization_OAuthAuthorization) Reset() {
	*x = OneOf_BasicAuthorization_BearerTokenAuthorization_OAuthAuthorization{}
	mi := &file_externalservices_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneOf_BasicAuthorization_BearerTokenAuthorization_OAuthAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOf_BasicAuthorization_BearerTokenAuthorization_OAuthAuthorization) ProtoMessage() {}

func (x *OneOf_BasicAuthorization_BearerTokenAuthorization_OAuthAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_externalservices_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOf_BasicAuthorization_BearerTokenAuthorization_OAuthAuthorization.ProtoReflect.Descriptor instead.
func (*OneOf_BasicAuthorization_BearerTokenAuthorization_OAuthAuthorization) Descriptor() ([]byte, []int) {
	return file_externalservices_proto_rawDescGZIP(), []int{13}
}

func (x *OneOf_BasicAuthorization_BearerTokenAuthorization_OAuthAuthorization) GetValue0() *BasicAuthorization {
	if x != nil {
		return x.Value0
	}
	return nil
}

func (x *OneOf_BasicAuthorization_BearerTokenAuthorization_OAuthAuthorization) GetValue1() *BearerTokenAuthorization {
	if x != nil {
		return x.Value1
	}
	return nil
}

func (x *OneOf_BasicAuthorization_BearerTokenAuthorization_OAuthAuthorization) GetValue2() *OAuthAuthorization {
	if x != nil {
		return x.Value2
	}
	return nil
}

type QueryResult_IEnumerable_ExternalServiceResponse struct {
	state               protoimpl.MessageState     `protogen:"open.v1"`
	CorrelationId       *bcl.Guid                  `protobuf:"bytes,1,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"` // default value could not be applied: 00000000-0000-0000-0000-000000000000
	IsAuthorized        bool                       `protobuf:"varint,2,opt,name=IsAuthorized,proto3" json:"IsAuthorized,omitempty"`
	ValidationResults   []*ValidationResult        `protobuf:"bytes,3,rep,name=ValidationResults,proto3" json:"ValidationResults,omitempty"`
	ExceptionMessages   []string                   `protobuf:"bytes,4,rep,name=ExceptionMessages,proto3" json:"ExceptionMessages,omitempty"`
	ExceptionStackTrace string                     `protobuf:"bytes,5,opt,name=ExceptionStackTrace,proto3" json:"ExceptionStackTrace,omitempty"`
	Data                []*ExternalServiceResponse `protobuf:"bytes,6,rep,name=Data,proto3" json:"Data,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QueryResult_IEnumerable_ExternalServiceResponse) Reset() {
	*x = QueryResult_IEnumerable_ExternalServiceResponse{}
	mi := &file_externalservices_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult_IEnumerable_ExternalServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult_IEnumerable_ExternalServiceResponse) ProtoMessage() {}

func (x *QueryResult_IEnumerable_ExternalServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_externalservices_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult_IEnumerable_ExternalServiceResponse.ProtoReflect.Descriptor instead.
func (*QueryResult_IEnumerable_ExternalServiceResponse) Descriptor() ([]byte, []int) {
	return file_externalservices_proto_rawDescGZIP(), []int{14}
}

func (x *QueryResult_IEnumerable_ExternalServiceResponse) GetCorrelationId() *bcl.Guid {
	if x != nil {
		return x.CorrelationId
	}
	return nil
}

func (x *QueryResult_IEnumerable_ExternalServiceResponse) GetIsAuthorized() bool {
	if x != nil {
		return x.IsAuthorized
	}
	return false
}

func (x *QueryResult_IEnumerable_ExternalServiceResponse) GetValidationResults() []*ValidationResult {
	if x != nil {
		return x.ValidationResults
	}
	return nil
}

func (x *QueryResult_IEnumerable_ExternalServiceResponse) GetExceptionMessages() []string {
	if x != nil {
		return x.ExceptionMessages
	}
	return nil
}

func (x *QueryResult_IEnumerable_ExternalServiceResponse) GetExceptionStackTrace() string {
	if x != nil {
		return x.ExceptionStackTrace
	}
	return ""
}

func (x *QueryResult_IEnumerable_ExternalServiceResponse) GetData() []*ExternalServiceResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type RemoveExternalServiceRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EventStore        string                 `protobuf:"bytes,1,opt,name=EventStore,proto3" json:"EventStore,omitempty"`
	ExternalServiceId string                 `protobuf:"bytes,2,opt,name=ExternalServiceId,proto3" json:"ExternalServiceId,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RemoveExternalServiceRequest) Reset() {
	*x = RemoveExternalServiceRequest{}
	mi := &file_externalservices_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveExternalServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveExternalServiceRequest) ProtoMessage() {}

func (x *RemoveExternalServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_externalservices_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveExternalServiceRequest.ProtoReflect.Descriptor instead.
func (*RemoveExternalServiceRequest) Descriptor() ([]byte, []int) {
	return file_externalservices_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveExternalServiceRequest) GetEventStore() string {
	if x != nil {
		return x.EventStore
	}
	return ""
}

func (x *RemoveExternalServiceRequest) GetExternalServiceId() string {
	if x != nil {
		return x.ExternalServiceId
	}
	return ""
}

type RemoveExternalServicesRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventStore       string                 `protobuf:"bytes,1,opt,name=EventStore,proto3" json:"EventStore,omitempty"`
	ExternalServices []string               `protobuf:"bytes,2,rep,name=ExternalServices,proto3" json:"ExternalServices,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RemoveExternalServicesRequest) Reset() {
	*x = RemoveExternalServicesRequest{}
	mi := &file_externalservices_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveExternalServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveExternalServicesRequest) ProtoMessage() {}

func (x *RemoveExternalServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_externalservices_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveExternalServicesRequest.ProtoReflect.Descriptor instead.
func (*RemoveExternalServicesRequest) Descriptor() ([]byte, []int) {
	return file_externalservices_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveExternalServicesRequest) GetEventStore() string {
	if x != nil {
		return x.EventStore
	}
	return ""
}

func (x *RemoveExternalServicesRequest) GetExternalServices() []string {
	if x != nil {
		return x.ExternalServices
	}
	return nil
}

type ValidationResult struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Severity      ValidationResultSeverity `protobuf:"varint,1,opt,name=Severity,proto3,enum=Cratis.Chronicle.Contracts.ExternalServices.ValidationResultSeverity" json:"Severity,omitempty"` // default value could not be applied: Error
	Message       string                   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Members       []string                 `protobuf:"bytes,3,rep,name=Members,proto3" json:"Members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationResult) Reset() {
	*x = ValidationResult{}
	mi := &file_externalservices_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResult) ProtoMessage() {}

func (x *ValidationResult) ProtoReflect() protoreflect.Message {
	mi := &file_externalservices_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResult.ProtoReflect.Descriptor instead.
func (*ValidationResult) Descriptor() ([]byte, []int) {
	return file_externalservices_proto_rawDescGZIP(), []int{17}
}

func (x *ValidationResult) GetSeverity() ValidationResultSeverity {
	if x != nil {
		return x.Severity
	}
	return ValidationResultSeverity_Unknown
}

func (x *ValidationResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationResult) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_externalservices_proto protoreflect.FileDescriptor

const file_externalservices_proto_rawDesc = "" +
	"\n" +
	"\x16externalservices.proto\x12+Cratis.Chronicle.Contracts.ExternalServices\x1a\x16protobuf-net/bcl.proto\"\x89\b\n" +
	"\x19AddExternalServiceRequest\x12\x1e\n" +
	"\n" +
	"EventStore\x18\x01 \x01(\tR\n" +
	"EventStore\x12\x0e\n" +
	"\x02Id\x18\x02 \x01(\tR\x02Id\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12l\n" +
	"\fEndpointType\x18\x04 \x01(\x0e2H.Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceEndpointTypeR\fEndpointType\x12\x10\n" +
	"\x03Url\x18\x05 \x01(\tR\x03Url\x12l\n" +
	"\x11AuthorizationType\x18\x06 \x01(\x0e2>.Cratis.Chronicle.Contracts.ExternalServices.AuthorizationTypeR\x11AuthorizationType\x12$\n" +
	"\rBasicUsername\x18\a \x01(\tR\rBasicUsername\x12$\n" +
	"\rBasicPassword\x18\b \x01(\tR\rBasicPassword\x12 \n" +
	"\vBearerToken\x18\t \x01(\tR\vBearerToken\x12&\n" +
	"\x0eOAuthAuthority\x18\n" +
	" \x01(\tR\x0eOAuthAuthority\x12$\n" +
	"\rOAuthClientId\x18\v \x01(\tR\rOAuthClientId\x12,\n" +
	"\x11OAuthClientSecret\x18\f \x01(\tR\x11OAuthClientSecret\x12m\n" +
	"\aHeaders\x18\r \x03(\v2S.Cratis.Chronicle.Contracts.ExternalServices.AddExternalServiceRequest.HeadersEntryR\aHeaders\x12\x12\n" +
	"\x04Host\x18\x0e \x01(\tR\x04Host\x12\x12\n" +
	"\x04Port\x18\x0f \x01(\x05R\x04Port\x12\x1a\n" +
	"\bDatabase\x18\x10 \x01(\tR\bDatabase\x12\x1a\n" +
	"\bUsername\x18\x11 \x01(\tR\bUsername\x12\x1a\n" +
	"\bPassword\x18\x12 \x01(\tR\bPassword\x12m\n" +
	"\aOptions\x18\x13 \x03(\v2S.Cratis.Chronicle.Contracts.ExternalServices.AddExternalServiceRequest.OptionsEntryR\aOptions\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb0\x01\n" +
	"\x1aAddExternalServicesRequest\x12\x1e\n" +
	"\n" +
	"EventStore\x18\x01 \x01(\tR\n" +
	"EventStore\x12r\n" +
	"\x10ExternalServices\x18\x02 \x03(\v2F.Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceDefinitionR\x10ExternalServices\"L\n" +
	"\x12BasicAuthorization\x12\x1a\n" +
	"\bUsername\x18\x01 \x01(\tR\bUsername\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\"0\n" +
	"\x18BearerTokenAuthorization\x12\x14\n" +
	"\x05Token\x18\x01 \x01(\tR\x05Token\"\xf1\x02\n" +
	"\rCommandResult\x12/\n" +
	"\rCorrelationId\x18\x01 \x01(\v2\t.bcl.GuidR\rCorrelationId\x12\"\n" +
	"\fIsAuthorized\x18\x02 \x01(\bR\fIsAuthorized\x12k\n" +
	"\x11ValidationResults\x18\x03 \x03(\v2=.Cratis.Chronicle.Contracts.ExternalServices.ValidationResultR\x11ValidationResults\x12,\n" +
	"\x11ExceptionMessages\x18\x04 \x03(\tR\x11ExceptionMessages\x120\n" +
	"\x13ExceptionStackTrace\x18\x05 \x01(\tR\x13ExceptionStackTrace\x12>\n" +
	"\x1aAuthorizationFailureReason\x18\x06 \x01(\tR\x1aAuthorizationFailureReason\"\xca\x02\n" +
	"\x1dDatabaseEndpointConfiguration\x12\x12\n" +
	"\x04Host\x18\x01 \x01(\tR\x04Host\x12\x12\n" +
	"\x04Port\x18\x02 \x01(\x05R\x04Port\x12\x1a\n" +
	"\bDatabase\x18\x03 \x01(\tR\bDatabase\x12\x1a\n" +
	"\bUsername\x18\x04 \x01(\tR\bUsername\x12\x1a\n" +
	"\bPassword\x18\x05 \x01(\tR\bPassword\x12q\n" +
	"\aOptions\x18\x06 \x03(\v2W.Cratis.Chronicle.Contracts.ExternalServices.DatabaseEndpointConfiguration.OptionsEntryR\aOptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa1\x01\n" +
	"\x19ExternalServiceDefinition\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12`\n" +
	"\bEndpoint\x18\x03 \x01(\v2D.Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceEndpointR\bEndpoint\"\xbb\x02\n" +
	"\x17ExternalServiceEndpoint\x12\\\n" +
	"\x04Type\x18\x01 \x01(\x0e2H.Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceEndpointTypeR\x04Type\x12Z\n" +
	"\x04Http\x18\x02 \x01(\v2F.Cratis.Chronicle.Contracts.ExternalServices.HttpEndpointConfigurationR\x04Http\x12f\n" +
	"\bDatabase\x18\x03 \x01(\v2J.Cratis.Chronicle.Contracts.ExternalServices.DatabaseEndpointConfigurationR\bDatabase\"\xdd\x05\n" +
	"\x17ExternalServiceResponse\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12l\n" +
	"\fEndpointType\x18\x03 \x01(\x0e2H.Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceEndpointTypeR\fEndpointType\x12\x10\n" +
	"\x03Url\x18\x04 \x01(\tR\x03Url\x12l\n" +
	"\x11AuthorizationType\x18\x05 \x01(\x0e2>.Cratis.Chronicle.Contracts.ExternalServices.AuthorizationTypeR\x11AuthorizationType\x12k\n" +
	"\aHeaders\x18\x06 \x03(\v2Q.Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceResponse.HeadersEntryR\aHeaders\x12\x12\n" +
	"\x04Host\x18\a \x01(\tR\x04Host\x12\x12\n" +
	"\x04Port\x18\b \x01(\x05R\x04Port\x12\x1a\n" +
	"\bDatabase\x18\t \x01(\tR\bDatabase\x12\x1a\n" +
	"\bUsername\x18\n" +
	" \x01(\tR\bUsername\x12k\n" +
	"\aOptions\x18\v \x03(\v2Q.Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceResponse.OptionsEntryR\aOptions\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\x1aGetExternalServicesRequest\x12\x1e\n" +
	"\n" +
	"EventStore\x18\x01 \x01(\tR\n" +
	"EventStore\"\xf2\x02\n" +
	"\x19HttpEndpointConfiguration\x12\x10\n" +
	"\x03Url\x18\x01 \x01(\tR\x03Url\x12\x97\x01\n" +
	"\rAuthorization\x18\x02 \x01(\v2q.Cratis.Chronicle.Contracts.ExternalServices.OneOf_BasicAuthorization_BearerTokenAuthorization_OAuthAuthorizationR\rAuthorization\x12m\n" +
	"\aHeaders\x18\x03 \x03(\v2S.Cratis.Chronicle.Contracts.ExternalServices.HttpEndpointConfiguration.HeadersEntryR\aHeaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\x12OAuthAuthorization\x12\x1c\n" +
	"\tAuthority\x18\x01 \x01(\tR\tAuthority\x12\x1a\n" +
	"\bClientId\x18\x02 \x01(\tR\bClientId\x12\"\n" +
	"\fClientSecret\x18\x03 \x01(\tR\fClientSecret\"@\n" +
	"\x1eObserveExternalServicesRequest\x12\x1e\n" +
	"\n" +
	"EventStore\x18\x01 \x01(\tR\n" +
	"EventStore\"\xd7\x02\n" +
	"DOneOf_BasicAuthorization_BearerTokenAuthorization_OAuthAuthorization\x12W\n" +
	"\x06Value0\x18\x01 \x01(\v2?.Cratis.Chronicle.Contracts.ExternalServices.BasicAuthorizationR\x06Value0\x12]\n" +
	"\x06Value1\x18\x02 \x01(\v2E.Cratis.Chronicle.Contracts.ExternalServices.BearerTokenAuthorizationR\x06Value1\x12W\n" +
	"\x06Value2\x18\x03 \x01(\v2?.Cratis.Chronicle.Contracts.ExternalServices.OAuthAuthorizationR\x06Value2\"\xad\x03\n" +
	"/QueryResult_IEnumerable_ExternalServiceResponse\x12/\n" +
	"\rCorrelationId\x18\x01 \x01(\v2\t.bcl.GuidR\rCorrelationId\x12\"\n" +
	"\fIsAuthorized\x18\x02 \x01(\bR\fIsAuthorized\x12k\n" +
	"\x11ValidationResults\x18\x03 \x03(\v2=.Cratis.Chronicle.Contracts.ExternalServices.ValidationResultR\x11ValidationResults\x12,\n" +
	"\x11ExceptionMessages\x18\x04 \x03(\tR\x11ExceptionMessages\x120\n" +
	"\x13ExceptionStackTrace\x18\x05 \x01(\tR\x13ExceptionStackTrace\x12X\n" +
	"\x04Data\x18\x06 \x03(\v2D.Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceResponseR\x04Data\"l\n" +
	"\x1cRemoveExternalServiceRequest\x12\x1e\n" +
	"\n" +
	"EventStore\x18\x01 \x01(\tR\n" +
	"EventStore\x12,\n" +
	"\x11ExternalServiceId\x18\x02 \x01(\tR\x11ExternalServiceId\"k\n" +
	"\x1dRemoveExternalServicesRequest\x12\x1e\n" +
	"\n" +
	"EventStore\x18\x01 \x01(\tR\n" +
	"EventStore\x12*\n" +
	"\x10ExternalServices\x18\x02 \x03(\tR\x10ExternalServices\"\xa9\x01\n" +
	"\x10ValidationResult\x12a\n" +
	"\bSeverity\x18\x01 \x01(\x0e2E.Cratis.Chronicle.Contracts.ExternalServices.ValidationResultSeverityR\bSeverity\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\x12\x18\n" +
	"\aMembers\x18\x03 \x03(\tR\aMembers*?\n" +
	"\x11AuthorizationType\x12\b\n" +
	"\x04None\x10\x00\x12\t\n" +
	"\x05Basic\x10\x01\x12\n" +
	"\n" +
	"\x06Bearer\x10\x02\x12\t\n" +
	"\x05OAuth\x10\x03*B\n" +
	"\x1bExternalServiceEndpointType\x12\b\n" +
	"\x04Http\x10\x00\x12\t\n" +
	"\x05MsSql\x10\x01\x12\x0e\n" +
	"\n" +
	"PostgreSql\x10\x02*P\n" +
	"\x18ValidationResultSeverity\x12\v\n" +
	"\aUnknown\x10\x00\x12\x0f\n" +
	"\vInformation\x10\x01\x12\v\n" +
	"\aWarning\x10\x02\x12\t\n" +
	"\x05Error\x10\x032\x96\b\n" +
	"\x10ExternalServices\x12\x98\x01\n" +
	"\x12AddExternalService\x12F.Cratis.Chronicle.Contracts.ExternalServices.AddExternalServiceRequest\x1a:.Cratis.Chronicle.Contracts.ExternalServices.CommandResult\x12\x9a\x01\n" +
	"\x13AddExternalServices\x12G.Cratis.Chronicle.Contracts.ExternalServices.AddExternalServicesRequest\x1a:.Cratis.Chronicle.Contracts.ExternalServices.CommandResult\x12\xbc\x01\n" +
	"\x13GetExternalServices\x12G.Cratis.Chronicle.Contracts.ExternalServices.GetExternalServicesRequest\x1a\\.Cratis.Chronicle.Contracts.ExternalServices.QueryResult_IEnumerable_ExternalServiceResponse\x12\xc6\x01\n" +
	"\x17ObserveExternalServices\x12K.Cratis.Chronicle.Contracts.ExternalServices.ObserveExternalServicesRequest\x1a\\.Cratis.Chronicle.Contracts.ExternalServices.QueryResult_IEnumerable_ExternalServiceResponse0\x01\x12\x9e\x01\n" +
	"\x15RemoveExternalService\x12I.Cratis.Chronicle.Contracts.ExternalServices.RemoveExternalServiceRequest\x1a:.Cratis.Chronicle.Contracts.ExternalServices.CommandResult\x12\xa0\x01\n" +
	"\x16RemoveExternalServices\x12J.Cratis.Chronicle.Contracts.ExternalServices.RemoveExternalServicesRequest\x1a:.Cratis.Chronicle.Contracts.ExternalServices.CommandResultB\xd3\x02\n" +
	"/com.Cratis.Chronicle.Contracts.ExternalServicesB\x15ExternalservicesProtoP\x01Z9github.com/cratis/chronicle.go/contracts/externalservices\xa2\x02\x04CCCE\xaa\x02+Cratis.Chronicle.Contracts.ExternalServices\xca\x02+Cratis\\Chronicle\\Contracts\\ExternalServices\xe2\x027Cratis\\Chronicle\\Contracts\\ExternalServices\\GPBMetadata\xea\x02.Cratis::Chronicle::Contracts::ExternalServicesb\x06proto3"

var (
	file_externalservices_proto_rawDescOnce sync.Once
	file_externalservices_proto_rawDescData []byte
)

func file_externalservices_proto_rawDescGZIP() []byte {
	file_externalservices_proto_rawDescOnce.Do(func() {
		file_externalservices_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_externalservices_proto_rawDesc), len(file_externalservices_proto_rawDesc)))
	})
	return file_externalservices_proto_rawDescData
}

var file_externalservices_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_externalservices_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_externalservices_proto_goTypes = []any{
	(AuthorizationType)(0),                 // 0: Cratis.Chronicle.Contracts.ExternalServices.AuthorizationType
	(ExternalServiceEndpointType)(0),       // 1: Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceEndpointType
	(ValidationResultSeverity)(0),          // 2: Cratis.Chronicle.Contracts.ExternalServices.ValidationResultSeverity
	(*AddExternalServiceRequest)(nil),      // 3: Cratis.Chronicle.Contracts.ExternalServices.AddExternalServiceRequest
	(*AddExternalServicesRequest)(nil),     // 4: Cratis.Chronicle.Contracts.ExternalServices.AddExternalServicesRequest
	(*BasicAuthorization)(nil),             // 5: Cratis.Chronicle.Contracts.ExternalServices.BasicAuthorization
	(*BearerTokenAuthorization)(nil),       // 6: Cratis.Chronicle.Contracts.ExternalServices.BearerTokenAuthorization
	(*CommandResult)(nil),                  // 7: Cratis.Chronicle.Contracts.ExternalServices.CommandResult
	(*DatabaseEndpointConfiguration)(nil),  // 8: Cratis.Chronicle.Contracts.ExternalServices.DatabaseEndpointConfiguration
	(*ExternalServiceDefinition)(nil),      // 9: Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceDefinition
	(*ExternalServiceEndpoint)(nil),        // 10: Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceEndpoint
	(*ExternalServiceResponse)(nil),        // 11: Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceResponse
	(*GetExternalServicesRequest)(nil),     // 12: Cratis.Chronicle.Contracts.ExternalServices.GetExternalServicesRequest
	(*HttpEndpointConfiguration)(nil),      // 13: Cratis.Chronicle.Contracts.ExternalServices.HttpEndpointConfiguration
	(*OAuthAuthorization)(nil),             // 14: Cratis.Chronicle.Contracts.ExternalServices.OAuthAuthorization
	(*ObserveExternalServicesRequest)(nil), // 15: Cratis.Chronicle.Contracts.ExternalServices.ObserveExternalServicesRequest
	(*OneOf_BasicAuthorization_BearerTokenAuthorization_OAuthAuthorization)(nil), // 16: Cratis.Chronicle.Contracts.ExternalServices.OneOf_BasicAuthorization_BearerTokenAuthorization_OAuthAuthorization
	(*QueryResult_IEnumerable_ExternalServiceResponse)(nil),                      // 17: Cratis.Chronicle.Contracts.ExternalServices.QueryResult_IEnumerable_ExternalServiceResponse
	(*RemoveExternalServiceRequest)(nil),                                         // 18: Cratis.Chronicle.Contracts.ExternalServices.RemoveExternalServiceRequest
	(*RemoveExternalServicesRequest)(nil),                                        // 19: Cratis.Chronicle.Contracts.ExternalServices.RemoveExternalServicesRequest
	(*ValidationResult)(nil),                                                     // 20: Cratis.Chronicle.Contracts.ExternalServices.ValidationResult
	nil,                                                                          // 21: Cratis.Chronicle.Contracts.ExternalServices.AddExternalServiceRequest.HeadersEntry
	nil,                                                                          // 22: Cratis.Chronicle.Contracts.ExternalServices.AddExternalServiceRequest.OptionsEntry
	nil,                                                                          // 23: Cratis.Chronicle.Contracts.ExternalServices.DatabaseEndpointConfiguration.OptionsEntry
	nil,                                                                          // 24: Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceResponse.HeadersEntry
	nil,                                                                          // 25: Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceResponse.OptionsEntry
	nil,                                                                          // 26: Cratis.Chronicle.Contracts.ExternalServices.HttpEndpointConfiguration.HeadersEntry
	(*bcl.Guid)(nil),                                                             // 27: bcl.Guid
}
var file_externalservices_proto_depIdxs = []int32{
	1,  // 0: Cratis.Chronicle.Contracts.ExternalServices.AddExternalServiceRequest.EndpointType:type_name -> Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceEndpointType
	0,  // 1: Cratis.Chronicle.Contracts.ExternalServices.AddExternalServiceRequest.AuthorizationType:type_name -> Cratis.Chronicle.Contracts.ExternalServices.AuthorizationType
	21, // 2: Cratis.Chronicle.Contracts.ExternalServices.AddExternalServiceRequest.Headers:type_name -> Cratis.Chronicle.Contracts.ExternalServices.AddExternalServiceRequest.HeadersEntry
	22, // 3: Cratis.Chronicle.Contracts.ExternalServices.AddExternalServiceRequest.Options:type_name -> Cratis.Chronicle.Contracts.ExternalServices.AddExternalServiceRequest.OptionsEntry
	9,  // 4: Cratis.Chronicle.Contracts.ExternalServices.AddExternalServicesRequest.ExternalServices:type_name -> Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceDefinition
	27, // 5: Cratis.Chronicle.Contracts.ExternalServices.CommandResult.CorrelationId:type_name -> bcl.Guid
	20, // 6: Cratis.Chronicle.Contracts.ExternalServices.CommandResult.ValidationResults:type_name -> Cratis.Chronicle.Contracts.ExternalServices.ValidationResult
	23, // 7: Cratis.Chronicle.Contracts.ExternalServices.DatabaseEndpointConfiguration.Options:type_name -> Cratis.Chronicle.Contracts.ExternalServices.DatabaseEndpointConfiguration.OptionsEntry
	10, // 8: Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceDefinition.Endpoint:type_name -> Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceEndpoint
	1,  // 9: Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceEndpoint.Type:type_name -> Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceEndpointType
	13, // 10: Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceEndpoint.Http:type_name -> Cratis.Chronicle.Contracts.ExternalServices.HttpEndpointConfiguration
	8,  // 11: Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceEndpoint.Database:type_name -> Cratis.Chronicle.Contracts.ExternalServices.DatabaseEndpointConfiguration
	1,  // 12: Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceResponse.EndpointType:type_name -> Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceEndpointType
	0,  // 13: Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceResponse.AuthorizationType:type_name -> Cratis.Chronicle.Contracts.ExternalServices.AuthorizationType
	24, // 14: Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceResponse.Headers:type_name -> Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceResponse.HeadersEntry
	25, // 15: Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceResponse.Options:type_name -> Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceResponse.OptionsEntry
	16, // 16: Cratis.Chronicle.Contracts.ExternalServices.HttpEndpointConfiguration.Authorization:type_name -> Cratis.Chronicle.Contracts.ExternalServices.OneOf_BasicAuthorization_BearerTokenAuthorization_OAuthAuthorization
	26, // 17: Cratis.Chronicle.Contracts.ExternalServices.HttpEndpointConfiguration.Headers:type_name -> Cratis.Chronicle.Contracts.ExternalServices.HttpEndpointConfiguration.HeadersEntry
	5,  // 18: Cratis.Chronicle.Contracts.ExternalServices.OneOf_BasicAuthorization_BearerTokenAuthorization_OAuthAuthorization.Value0:type_name -> Cratis.Chronicle.Contracts.ExternalServices.BasicAuthorization
	6,  // 19: Cratis.Chronicle.Contracts.ExternalServices.OneOf_BasicAuthorization_BearerTokenAuthorization_OAuthAuthorization.Value1:type_name -> Cratis.Chronicle.Contracts.ExternalServices.BearerTokenAuthorization
	14, // 20: Cratis.Chronicle.Contracts.ExternalServices.OneOf_BasicAuthorization_BearerTokenAuthorization_OAuthAuthorization.Value2:type_name -> Cratis.Chronicle.Contracts.ExternalServices.OAuthAuthorization
	27, // 21: Cratis.Chronicle.Contracts.ExternalServices.QueryResult_IEnumerable_ExternalServiceResponse.CorrelationId:type_name -> bcl.Guid
	20, // 22: Cratis.Chronicle.Contracts.ExternalServices.QueryResult_IEnumerable_ExternalServiceResponse.ValidationResults:type_name -> Cratis.Chronicle.Contracts.ExternalServices.ValidationResult
	11, // 23: Cratis.Chronicle.Contracts.ExternalServices.QueryResult_IEnumerable_ExternalServiceResponse.Data:type_name -> Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceResponse
	2,  // 24: Cratis.Chronicle.Contracts.ExternalServices.ValidationResult.Severity:type_name -> Cratis.Chronicle.Contracts.ExternalServices.ValidationResultSeverity
	3,  // 25: Cratis.Chronicle.Contracts.ExternalServices.ExternalServices.AddExternalService:input_type -> Cratis.Chronicle.Contracts.ExternalServices.AddExternalServiceRequest
	4,  // 26: Cratis.Chronicle.Contracts.ExternalServices.ExternalServices.AddExternalServices:input_type -> Cratis.Chronicle.Contracts.ExternalServices.AddExternalServicesRequest
	12, // 27: Cratis.Chronicle.Contracts.ExternalServices.ExternalServices.GetExternalServices:input_type -> Cratis.Chronicle.Contracts.ExternalServices.GetExternalServicesRequest
	15, // 28: Cratis.Chronicle.Contracts.ExternalServices.ExternalServices.ObserveExternalServices:input_type -> Cratis.Chronicle.Contracts.ExternalServices.ObserveExternalServicesRequest
	18, // 29: Cratis.Chronicle.Contracts.ExternalServices.ExternalServices.RemoveExternalService:input_type -> Cratis.Chronicle.Contracts.ExternalServices.RemoveExternalServiceRequest
	19, // 30: Cratis.Chronicle.Contracts.ExternalServices.ExternalServices.RemoveExternalServices:input_type -> Cratis.Chronicle.Contracts.ExternalServices.RemoveExternalServicesRequest
	7,  // 31: Cratis.Chronicle.Contracts.ExternalServices.ExternalServices.AddExternalService:output_type -> Cratis.Chronicle.Contracts.ExternalServices.CommandResult
	7,  // 32: Cratis.Chronicle.Contracts.ExternalServices.ExternalServices.AddExternalServices:output_type -> Cratis.Chronicle.Contracts.ExternalServices.CommandResult
	17, // 33: Cratis.Chronicle.Contracts.ExternalServices.ExternalServices.GetExternalServices:output_type -> Cratis.Chronicle.Contracts.ExternalServices.QueryResult_IEnumerable_ExternalServiceResponse
	17, // 34: Cratis.Chronicle.Contracts.ExternalServices.ExternalServices.ObserveExternalServices:output_type -> Cratis.Chronicle.Contracts.ExternalServices.QueryResult_IEnumerable_ExternalServiceResponse
	7,  // 35: Cratis.Chronicle.Contracts.ExternalServices.ExternalServices.RemoveExternalService:output_type -> Cratis.Chronicle.Contracts.ExternalServices.CommandResult
	7,  // 36: Cratis.Chronicle.Contracts.ExternalServices.ExternalServices.RemoveExternalServices:output_type -> Cratis.Chronicle.Contracts.ExternalServices.CommandResult
	31, // [31:37] is the sub-list for method output_type
	25, // [25:31] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_externalservices_proto_init() }
func file_externalservices_proto_init() {
	if File_externalservices_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_externalservices_proto_rawDesc), len(file_externalservices_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_externalservices_proto_goTypes,
		DependencyIndexes: file_externalservices_proto_depIdxs,
		EnumInfos:         file_externalservices_proto_enumTypes,
		MessageInfos:      file_externalservices_proto_msgTypes,
	}.Build()
	File_externalservices_proto = out.File
	file_externalservices_proto_goTypes = nil
	file_externalservices_proto_depIdxs = nil
}
