// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: sequences.proto

package sequences

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventSequences_AllEventSequences_FullMethodName                      = "/Cratis.Chronicle.Contracts.Sequences.EventSequences/AllEventSequences"
	EventSequences_Append_FullMethodName                                 = "/Cratis.Chronicle.Contracts.Sequences.EventSequences/Append"
	EventSequences_AppendedEvents_FullMethodName                         = "/Cratis.Chronicle.Contracts.Sequences.EventSequences/AppendedEvents"
	EventSequences_AppendMany_FullMethodName                             = "/Cratis.Chronicle.Contracts.Sequences.EventSequences/AppendMany"
	EventSequences_AppendManyForEventSources_FullMethodName              = "/Cratis.Chronicle.Contracts.Sequences.EventSequences/AppendManyForEventSources"
	EventSequences_AppendManyForEventSourcesWithNamedTags_FullMethodName = "/Cratis.Chronicle.Contracts.Sequences.EventSequences/AppendManyForEventSourcesWithNamedTags"
	EventSequences_AppendManyWithNamedTags_FullMethodName                = "/Cratis.Chronicle.Contracts.Sequences.EventSequences/AppendManyWithNamedTags"
	EventSequences_AppendWithNamedTags_FullMethodName                    = "/Cratis.Chronicle.Contracts.Sequences.EventSequences/AppendWithNamedTags"
	EventSequences_CompleteStream_FullMethodName                         = "/Cratis.Chronicle.Contracts.Sequences.EventSequences/CompleteStream"
	EventSequences_EndOf_FullMethodName                                  = "/Cratis.Chronicle.Contracts.Sequences.EventSequences/EndOf"
	EventSequences_ExportEvents_FullMethodName                           = "/Cratis.Chronicle.Contracts.Sequences.EventSequences/ExportEvents"
	EventSequences_ForEventSourceIdAndEventTypes_FullMethodName          = "/Cratis.Chronicle.Contracts.Sequences.EventSequences/ForEventSourceIdAndEventTypes"
	EventSequences_FromSequenceNumber_FullMethodName                     = "/Cratis.Chronicle.Contracts.Sequences.EventSequences/FromSequenceNumber"
	EventSequences_HasEventsForEventSourceId_FullMethodName              = "/Cratis.Chronicle.Contracts.Sequences.EventSequences/HasEventsForEventSourceId"
	EventSequences_ParseResolution_FullMethodName                        = "/Cratis.Chronicle.Contracts.Sequences.EventSequences/ParseResolution"
	EventSequences_QueryEvents_FullMethodName                            = "/Cratis.Chronicle.Contracts.Sequences.EventSequences/QueryEvents"
	EventSequences_QueryEventsWithNamedTags_FullMethodName               = "/Cratis.Chronicle.Contracts.Sequences.EventSequences/QueryEventsWithNamedTags"
	EventSequences_Redact_FullMethodName                                 = "/Cratis.Chronicle.Contracts.Sequences.EventSequences/Redact"
	EventSequences_RedactForEventSource_FullMethodName                   = "/Cratis.Chronicle.Contracts.Sequences.EventSequences/RedactForEventSource"
	EventSequences_Revise_FullMethodName                                 = "/Cratis.Chronicle.Contracts.Sequences.EventSequences/Revise"
	EventSequences_SequenceHistogram_FullMethodName                      = "/Cratis.Chronicle.Contracts.Sequences.EventSequences/SequenceHistogram"
	EventSequences_SequenceHistogramWithNamedTags_FullMethodName         = "/Cratis.Chronicle.Contracts.Sequences.EventSequences/SequenceHistogramWithNamedTags"
	EventSequences_TailSequenceNumber_FullMethodName                     = "/Cratis.Chronicle.Contracts.Sequences.EventSequences/TailSequenceNumber"
)

// EventSequencesClient is the client API for EventSequences service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventSequencesClient interface {
	AllEventSequences(ctx context.Context, in *AllEventSequencesRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_EventSequenceNamesResponse, error)
	Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*CommandResult_AppendResponse, error)
	AppendedEvents(ctx context.Context, in *AppendedEventsRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_AppendedEventResponse, error)
	AppendMany(ctx context.Context, in *AppendManyRequest, opts ...grpc.CallOption) (*CommandResult_AppendManyResponse, error)
	AppendManyForEventSources(ctx context.Context, in *AppendManyForEventSourcesRequest, opts ...grpc.CallOption) (*CommandResult_AppendManyResponse, error)
	AppendManyForEventSourcesWithNamedTags(ctx context.Context, in *AppendManyForEventSourcesWithNamedTagsRequest, opts ...grpc.CallOption) (*CommandResult_AppendManyResponse, error)
	AppendManyWithNamedTags(ctx context.Context, in *AppendManyWithNamedTagsRequest, opts ...grpc.CallOption) (*CommandResult_AppendManyResponse, error)
	AppendWithNamedTags(ctx context.Context, in *AppendWithNamedTagsRequest, opts ...grpc.CallOption) (*CommandResult_AppendResponse, error)
	CompleteStream(ctx context.Context, in *CompleteStreamRequest, opts ...grpc.CallOption) (*CommandResult_CompleteStreamResponse, error)
	EndOf(ctx context.Context, in *EndOfRequest, opts ...grpc.CallOption) (*QueryResult_SerializableDateTimeOffset, error)
	ExportEvents(ctx context.Context, in *ExportEventsRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_ExportedEventResponse, error)
	ForEventSourceIdAndEventTypes(ctx context.Context, in *ForEventSourceIdAndEventTypesRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_AppendedEventResponse, error)
	FromSequenceNumber(ctx context.Context, in *FromSequenceNumberRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_AppendedEventResponse, error)
	HasEventsForEventSourceId(ctx context.Context, in *HasEventsForEventSourceIdRequest, opts ...grpc.CallOption) (*QueryResult_EventSourceEventsResponse, error)
	ParseResolution(ctx context.Context, in *ParseResolutionRequest, opts ...grpc.CallOption) (*QueryResult_HistogramResolution, error)
	QueryEvents(ctx context.Context, in *QueryEventsRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_AppendedEventResponse, error)
	QueryEventsWithNamedTags(ctx context.Context, in *QueryEventsWithNamedTagsRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_AppendedEventResponse, error)
	Redact(ctx context.Context, in *RedactRequest, opts ...grpc.CallOption) (*CommandResult, error)
	RedactForEventSource(ctx context.Context, in *RedactForEventSourceRequest, opts ...grpc.CallOption) (*CommandResult, error)
	Revise(ctx context.Context, in *ReviseRequest, opts ...grpc.CallOption) (*CommandResult, error)
	SequenceHistogram(ctx context.Context, in *SequenceHistogramRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_SequenceHistogramBucketResponse, error)
	SequenceHistogramWithNamedTags(ctx context.Context, in *SequenceHistogramWithNamedTagsRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_SequenceHistogramBucketResponse, error)
	TailSequenceNumber(ctx context.Context, in *TailSequenceNumberRequest, opts ...grpc.CallOption) (*QueryResult_EventSequenceTailResponse, error)
}

type eventSequencesClient struct {
	cc grpc.ClientConnInterface
}

func NewEventSequencesClient(cc grpc.ClientConnInterface) EventSequencesClient {
	return &eventSequencesClient{cc}
}

func (c *eventSequencesClient) AllEventSequences(ctx context.Context, in *AllEventSequencesRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_EventSequenceNamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResult_IEnumerable_EventSequenceNamesResponse)
	err := c.cc.Invoke(ctx, EventSequences_AllEventSequences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSequencesClient) Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*CommandResult_AppendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult_AppendResponse)
	err := c.cc.Invoke(ctx, EventSequences_Append_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSequencesClient) AppendedEvents(ctx context.Context, in *AppendedEventsRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_AppendedEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResult_IEnumerable_AppendedEventResponse)
	err := c.cc.Invoke(ctx, EventSequences_AppendedEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSequencesClient) AppendMany(ctx context.Context, in *AppendManyRequest, opts ...grpc.CallOption) (*CommandResult_AppendManyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult_AppendManyResponse)
	err := c.cc.Invoke(ctx, EventSequences_AppendMany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSequencesClient) AppendManyForEventSources(ctx context.Context, in *AppendManyForEventSourcesRequest, opts ...grpc.CallOption) (*CommandResult_AppendManyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult_AppendManyResponse)
	err := c.cc.Invoke(ctx, EventSequences_AppendManyForEventSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSequencesClient) AppendManyForEventSourcesWithNamedTags(ctx context.Context, in *AppendManyForEventSourcesWithNamedTagsRequest, opts ...grpc.CallOption) (*CommandResult_AppendManyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult_AppendManyResponse)
	err := c.cc.Invoke(ctx, EventSequences_AppendManyForEventSourcesWithNamedTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSequencesClient) AppendManyWithNamedTags(ctx context.Context, in *AppendManyWithNamedTagsRequest, opts ...grpc.CallOption) (*CommandResult_AppendManyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult_AppendManyResponse)
	err := c.cc.Invoke(ctx, EventSequences_AppendManyWithNamedTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSequencesClient) AppendWithNamedTags(ctx context.Context, in *AppendWithNamedTagsRequest, opts ...grpc.CallOption) (*CommandResult_AppendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult_AppendResponse)
	err := c.cc.Invoke(ctx, EventSequences_AppendWithNamedTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSequencesClient) CompleteStream(ctx context.Context, in *CompleteStreamRequest, opts ...grpc.CallOption) (*CommandResult_CompleteStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult_CompleteStreamResponse)
	err := c.cc.Invoke(ctx, EventSequences_CompleteStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSequencesClient) EndOf(ctx context.Context, in *EndOfRequest, opts ...grpc.CallOption) (*QueryResult_SerializableDateTimeOffset, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResult_SerializableDateTimeOffset)
	err := c.cc.Invoke(ctx, EventSequences_EndOf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSequencesClient) ExportEvents(ctx context.Context, in *ExportEventsRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_ExportedEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResult_IEnumerable_ExportedEventResponse)
	err := c.cc.Invoke(ctx, EventSequences_ExportEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSequencesClient) ForEventSourceIdAndEventTypes(ctx context.Context, in *ForEventSourceIdAndEventTypesRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_AppendedEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResult_IEnumerable_AppendedEventResponse)
	err := c.cc.Invoke(ctx, EventSequences_ForEventSourceIdAndEventTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSequencesClient) FromSequenceNumber(ctx context.Context, in *FromSequenceNumberRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_AppendedEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResult_IEnumerable_AppendedEventResponse)
	err := c.cc.Invoke(ctx, EventSequences_FromSequenceNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSequencesClient) HasEventsForEventSourceId(ctx context.Context, in *HasEventsForEventSourceIdRequest, opts ...grpc.CallOption) (*QueryResult_EventSourceEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResult_EventSourceEventsResponse)
	err := c.cc.Invoke(ctx, EventSequences_HasEventsForEventSourceId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSequencesClient) ParseResolution(ctx context.Context, in *ParseResolutionRequest, opts ...grpc.CallOption) (*QueryResult_HistogramResolution, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResult_HistogramResolution)
	err := c.cc.Invoke(ctx, EventSequences_ParseResolution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSequencesClient) QueryEvents(ctx context.Context, in *QueryEventsRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_AppendedEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResult_IEnumerable_AppendedEventResponse)
	err := c.cc.Invoke(ctx, EventSequences_QueryEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSequencesClient) QueryEventsWithNamedTags(ctx context.Context, in *QueryEventsWithNamedTagsRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_AppendedEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResult_IEnumerable_AppendedEventResponse)
	err := c.cc.Invoke(ctx, EventSequences_QueryEventsWithNamedTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSequencesClient) Redact(ctx context.Context, in *RedactRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, EventSequences_Redact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSequencesClient) RedactForEventSource(ctx context.Context, in *RedactForEventSourceRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, EventSequences_RedactForEventSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSequencesClient) Revise(ctx context.Context, in *ReviseRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, EventSequences_Revise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSequencesClient) SequenceHistogram(ctx context.Context, in *SequenceHistogramRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_SequenceHistogramBucketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResult_IEnumerable_SequenceHistogramBucketResponse)
	err := c.cc.Invoke(ctx, EventSequences_SequenceHistogram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSequencesClient) SequenceHistogramWithNamedTags(ctx context.Context, in *SequenceHistogramWithNamedTagsRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_SequenceHistogramBucketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResult_IEnumerable_SequenceHistogramBucketResponse)
	err := c.cc.Invoke(ctx, EventSequences_SequenceHistogramWithNamedTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSequencesClient) TailSequenceNumber(ctx context.Context, in *TailSequenceNumberRequest, opts ...grpc.CallOption) (*QueryResult_EventSequenceTailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResult_EventSequenceTailResponse)
	err := c.cc.Invoke(ctx, EventSequences_TailSequenceNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventSequencesServer is the server API for EventSequences service.
// All implementations must embed UnimplementedEventSequencesServer
// for forward compatibility.
type EventSequencesServer interface {
	AllEventSequences(context.Context, *AllEventSequencesRequest) (*QueryResult_IEnumerable_EventSequenceNamesResponse, error)
	Append(context.Context, *AppendRequest) (*CommandResult_AppendResponse, error)
	AppendedEvents(context.Context, *AppendedEventsRequest) (*QueryResult_IEnumerable_AppendedEventResponse, error)
	AppendMany(context.Context, *AppendManyRequest) (*CommandResult_AppendManyResponse, error)
	AppendManyForEventSources(context.Context, *AppendManyForEventSourcesRequest) (*CommandResult_AppendManyResponse, error)
	AppendManyForEventSourcesWithNamedTags(context.Context, *AppendManyForEventSourcesWithNamedTagsRequest) (*CommandResult_AppendManyResponse, error)
	AppendManyWithNamedTags(context.Context, *AppendManyWithNamedTagsRequest) (*CommandResult_AppendManyResponse, error)
	AppendWithNamedTags(context.Context, *AppendWithNamedTagsRequest) (*CommandResult_AppendResponse, error)
	CompleteStream(context.Context, *CompleteStreamRequest) (*CommandResult_CompleteStreamResponse, error)
	EndOf(context.Context, *EndOfRequest) (*QueryResult_SerializableDateTimeOffset, error)
	ExportEvents(context.Context, *ExportEventsRequest) (*QueryResult_IEnumerable_ExportedEventResponse, error)
	ForEventSourceIdAndEventTypes(context.Context, *ForEventSourceIdAndEventTypesRequest) (*QueryResult_IEnumerable_AppendedEventResponse, error)
	FromSequenceNumber(context.Context, *FromSequenceNumberRequest) (*QueryResult_IEnumerable_AppendedEventResponse, error)
	HasEventsForEventSourceId(context.Context, *HasEventsForEventSourceIdRequest) (*QueryResult_EventSourceEventsResponse, error)
	ParseResolution(context.Context, *ParseResolutionRequest) (*QueryResult_HistogramResolution, error)
	QueryEvents(context.Context, *QueryEventsRequest) (*QueryResult_IEnumerable_AppendedEventResponse, error)
	QueryEventsWithNamedTags(context.Context, *QueryEventsWithNamedTagsRequest) (*QueryResult_IEnumerable_AppendedEventResponse, error)
	Redact(context.Context, *RedactRequest) (*CommandResult, error)
	RedactForEventSource(context.Context, *RedactForEventSourceRequest) (*CommandResult, error)
	Revise(context.Context, *ReviseRequest) (*CommandResult, error)
	SequenceHistogram(context.Context, *SequenceHistogramRequest) (*QueryResult_IEnumerable_SequenceHistogramBucketResponse, error)
	SequenceHistogramWithNamedTags(context.Context, *SequenceHistogramWithNamedTagsRequest) (*QueryResult_IEnumerable_SequenceHistogramBucketResponse, error)
	TailSequenceNumber(context.Context, *TailSequenceNumberRequest) (*QueryResult_EventSequenceTailResponse, error)
	mustEmbedUnimplementedEventSequencesServer()
}

// UnimplementedEventSequencesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventSequencesServer struct{}

func (UnimplementedEventSequencesServer) AllEventSequences(context.Context, *AllEventSequencesRequest) (*QueryResult_IEnumerable_EventSequenceNamesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AllEventSequences not implemented")
}
func (UnimplementedEventSequencesServer) Append(context.Context, *AppendRequest) (*CommandResult_AppendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedEventSequencesServer) AppendedEvents(context.Context, *AppendedEventsRequest) (*QueryResult_IEnumerable_AppendedEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendedEvents not implemented")
}
func (UnimplementedEventSequencesServer) AppendMany(context.Context, *AppendManyRequest) (*CommandResult_AppendManyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendMany not implemented")
}
func (UnimplementedEventSequencesServer) AppendManyForEventSources(context.Context, *AppendManyForEventSourcesRequest) (*CommandResult_AppendManyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendManyForEventSources not implemented")
}
func (UnimplementedEventSequencesServer) AppendManyForEventSourcesWithNamedTags(context.Context, *AppendManyForEventSourcesWithNamedTagsRequest) (*CommandResult_AppendManyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendManyForEventSourcesWithNamedTags not implemented")
}
func (UnimplementedEventSequencesServer) AppendManyWithNamedTags(context.Context, *AppendManyWithNamedTagsRequest) (*CommandResult_AppendManyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendManyWithNamedTags not implemented")
}
func (UnimplementedEventSequencesServer) AppendWithNamedTags(context.Context, *AppendWithNamedTagsRequest) (*CommandResult_AppendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendWithNamedTags not implemented")
}
func (UnimplementedEventSequencesServer) CompleteStream(context.Context, *CompleteStreamRequest) (*CommandResult_CompleteStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteStream not implemented")
}
func (UnimplementedEventSequencesServer) EndOf(context.Context, *EndOfRequest) (*QueryResult_SerializableDateTimeOffset, error) {
	return nil, status.Error(codes.Unimplemented, "method EndOf not implemented")
}
func (UnimplementedEventSequencesServer) ExportEvents(context.Context, *ExportEventsRequest) (*QueryResult_IEnumerable_ExportedEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportEvents not implemented")
}
func (UnimplementedEventSequencesServer) ForEventSourceIdAndEventTypes(context.Context, *ForEventSourceIdAndEventTypesRequest) (*QueryResult_IEnumerable_AppendedEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForEventSourceIdAndEventTypes not implemented")
}
func (UnimplementedEventSequencesServer) FromSequenceNumber(context.Context, *FromSequenceNumberRequest) (*QueryResult_IEnumerable_AppendedEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FromSequenceNumber not implemented")
}
func (UnimplementedEventSequencesServer) HasEventsForEventSourceId(context.Context, *HasEventsForEventSourceIdRequest) (*QueryResult_EventSourceEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HasEventsForEventSourceId not implemented")
}
func (UnimplementedEventSequencesServer) ParseResolution(context.Context, *ParseResolutionRequest) (*QueryResult_HistogramResolution, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseResolution not implemented")
}
func (UnimplementedEventSequencesServer) QueryEvents(context.Context, *QueryEventsRequest) (*QueryResult_IEnumerable_AppendedEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryEvents not implemented")
}
func (UnimplementedEventSequencesServer) QueryEventsWithNamedTags(context.Context, *QueryEventsWithNamedTagsRequest) (*QueryResult_IEnumerable_AppendedEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryEventsWithNamedTags not implemented")
}
func (UnimplementedEventSequencesServer) Redact(context.Context, *RedactRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Redact not implemented")
}
func (UnimplementedEventSequencesServer) RedactForEventSource(context.Context, *RedactForEventSourceRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RedactForEventSource not implemented")
}
func (UnimplementedEventSequencesServer) Revise(context.Context, *ReviseRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Revise not implemented")
}
func (UnimplementedEventSequencesServer) SequenceHistogram(context.Context, *SequenceHistogramRequest) (*QueryResult_IEnumerable_SequenceHistogramBucketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SequenceHistogram not implemented")
}
func (UnimplementedEventSequencesServer) SequenceHistogramWithNamedTags(context.Context, *SequenceHistogramWithNamedTagsRequest) (*QueryResult_IEnumerable_SequenceHistogramBucketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SequenceHistogramWithNamedTags not implemented")
}
func (UnimplementedEventSequencesServer) TailSequenceNumber(context.Context, *TailSequenceNumberRequest) (*QueryResult_EventSequenceTailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TailSequenceNumber not implemented")
}
func (UnimplementedEventSequencesServer) mustEmbedUnimplementedEventSequencesServer() {}
func (UnimplementedEventSequencesServer) testEmbeddedByValue()                        {}

// UnsafeEventSequencesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventSequencesServer will
// result in compilation errors.
type UnsafeEventSequencesServer interface {
	mustEmbedUnimplementedEventSequencesServer()
}

func RegisterEventSequencesServer(s grpc.ServiceRegistrar, srv EventSequencesServer) {
	// If the following call panics, it indicates UnimplementedEventSequencesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventSequences_ServiceDesc, srv)
}

func _EventSequences_AllEventSequences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllEventSequencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSequencesServer).AllEventSequences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSequences_AllEventSequences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSequencesServer).AllEventSequences(ctx, req.(*AllEventSequencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSequences_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSequencesServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSequences_Append_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSequencesServer).Append(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSequences_AppendedEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendedEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSequencesServer).AppendedEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSequences_AppendedEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSequencesServer).AppendedEvents(ctx, req.(*AppendedEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSequences_AppendMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendManyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSequencesServer).AppendMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSequences_AppendMany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSequencesServer).AppendMany(ctx, req.(*AppendManyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSequences_AppendManyForEventSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendManyForEventSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSequencesServer).AppendManyForEventSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSequences_AppendManyForEventSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSequencesServer).AppendManyForEventSources(ctx, req.(*AppendManyForEventSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSequences_AppendManyForEventSourcesWithNamedTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendManyForEventSourcesWithNamedTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSequencesServer).AppendManyForEventSourcesWithNamedTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSequences_AppendManyForEventSourcesWithNamedTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSequencesServer).AppendManyForEventSourcesWithNamedTags(ctx, req.(*AppendManyForEventSourcesWithNamedTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSequences_AppendManyWithNamedTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendManyWithNamedTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSequencesServer).AppendManyWithNamedTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSequences_AppendManyWithNamedTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSequencesServer).AppendManyWithNamedTags(ctx, req.(*AppendManyWithNamedTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSequences_AppendWithNamedTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendWithNamedTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSequencesServer).AppendWithNamedTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSequences_AppendWithNamedTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSequencesServer).AppendWithNamedTags(ctx, req.(*AppendWithNamedTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSequences_CompleteStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSequencesServer).CompleteStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSequences_CompleteStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSequencesServer).CompleteStream(ctx, req.(*CompleteStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSequences_EndOf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndOfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSequencesServer).EndOf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSequences_EndOf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSequencesServer).EndOf(ctx, req.(*EndOfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSequences_ExportEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSequencesServer).ExportEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSequences_ExportEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSequencesServer).ExportEvents(ctx, req.(*ExportEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSequences_ForEventSourceIdAndEventTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForEventSourceIdAndEventTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSequencesServer).ForEventSourceIdAndEventTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSequences_ForEventSourceIdAndEventTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSequencesServer).ForEventSourceIdAndEventTypes(ctx, req.(*ForEventSourceIdAndEventTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSequences_FromSequenceNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FromSequenceNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSequencesServer).FromSequenceNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSequences_FromSequenceNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSequencesServer).FromSequenceNumber(ctx, req.(*FromSequenceNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSequences_HasEventsForEventSourceId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasEventsForEventSourceIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSequencesServer).HasEventsForEventSourceId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSequences_HasEventsForEventSourceId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSequencesServer).HasEventsForEventSourceId(ctx, req.(*HasEventsForEventSourceIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSequences_ParseResolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseResolutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSequencesServer).ParseResolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSequences_ParseResolution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSequencesServer).ParseResolution(ctx, req.(*ParseResolutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSequences_QueryEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSequencesServer).QueryEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSequences_QueryEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSequencesServer).QueryEvents(ctx, req.(*QueryEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSequences_QueryEventsWithNamedTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEventsWithNamedTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSequencesServer).QueryEventsWithNamedTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSequences_QueryEventsWithNamedTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSequencesServer).QueryEventsWithNamedTags(ctx, req.(*QueryEventsWithNamedTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSequences_Redact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSequencesServer).Redact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSequences_Redact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSequencesServer).Redact(ctx, req.(*RedactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSequences_RedactForEventSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedactForEventSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSequencesServer).RedactForEventSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSequences_RedactForEventSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSequencesServer).RedactForEventSource(ctx, req.(*RedactForEventSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSequences_Revise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSequencesServer).Revise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSequences_Revise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSequencesServer).Revise(ctx, req.(*ReviseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSequences_SequenceHistogram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SequenceHistogramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSequencesServer).SequenceHistogram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSequences_SequenceHistogram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSequencesServer).SequenceHistogram(ctx, req.(*SequenceHistogramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSequences_SequenceHistogramWithNamedTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SequenceHistogramWithNamedTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSequencesServer).SequenceHistogramWithNamedTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSequences_SequenceHistogramWithNamedTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSequencesServer).SequenceHistogramWithNamedTags(ctx, req.(*SequenceHistogramWithNamedTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSequences_TailSequenceNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TailSequenceNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSequencesServer).TailSequenceNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSequences_TailSequenceNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSequencesServer).TailSequenceNumber(ctx, req.(*TailSequenceNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventSequences_ServiceDesc is the grpc.ServiceDesc for EventSequences service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventSequences_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Cratis.Chronicle.Contracts.Sequences.EventSequences",
	HandlerType: (*EventSequencesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllEventSequences",
			Handler:    _EventSequences_AllEventSequences_Handler,
		},
		{
			MethodName: "Append",
			Handler:    _EventSequences_Append_Handler,
		},
		{
			MethodName: "AppendedEvents",
			Handler:    _EventSequences_AppendedEvents_Handler,
		},
		{
			MethodName: "AppendMany",
			Handler:    _EventSequences_AppendMany_Handler,
		},
		{
			MethodName: "AppendManyForEventSources",
			Handler:    _EventSequences_AppendManyForEventSources_Handler,
		},
		{
			MethodName: "AppendManyForEventSourcesWithNamedTags",
			Handler:    _EventSequences_AppendManyForEventSourcesWithNamedTags_Handler,
		},
		{
			MethodName: "AppendManyWithNamedTags",
			Handler:    _EventSequences_AppendManyWithNamedTags_Handler,
		},
		{
			MethodName: "AppendWithNamedTags",
			Handler:    _EventSequences_AppendWithNamedTags_Handler,
		},
		{
			MethodName: "CompleteStream",
			Handler:    _EventSequences_CompleteStream_Handler,
		},
		{
			MethodName: "EndOf",
			Handler:    _EventSequences_EndOf_Handler,
		},
		{
			MethodName: "ExportEvents",
			Handler:    _EventSequences_ExportEvents_Handler,
		},
		{
			MethodName: "ForEventSourceIdAndEventTypes",
			Handler:    _EventSequences_ForEventSourceIdAndEventTypes_Handler,
		},
		{
			MethodName: "FromSequenceNumber",
			Handler:    _EventSequences_FromSequenceNumber_Handler,
		},
		{
			MethodName: "HasEventsForEventSourceId",
			Handler:    _EventSequences_HasEventsForEventSourceId_Handler,
		},
		{
			MethodName: "ParseResolution",
			Handler:    _EventSequences_ParseResolution_Handler,
		},
		{
			MethodName: "QueryEvents",
			Handler:    _EventSequences_QueryEvents_Handler,
		},
		{
			MethodName: "QueryEventsWithNamedTags",
			Handler:    _EventSequences_QueryEventsWithNamedTags_Handler,
		},
		{
			MethodName: "Redact",
			Handler:    _EventSequences_Redact_Handler,
		},
		{
			MethodName: "RedactForEventSource",
			Handler:    _EventSequences_RedactForEventSource_Handler,
		},
		{
			MethodName: "Revise",
			Handler:    _EventSequences_Revise_Handler,
		},
		{
			MethodName: "SequenceHistogram",
			Handler:    _EventSequences_SequenceHistogram_Handler,
		},
		{
			MethodName: "SequenceHistogramWithNamedTags",
			Handler:    _EventSequences_SequenceHistogramWithNamedTags_Handler,
		},
		{
			MethodName: "TailSequenceNumber",
			Handler:    _EventSequences_TailSequenceNumber_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sequences.proto",
}
