// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: namespaces.proto

package namespaces

import (
	bcl "github.com/cratis/chronicle.go/contracts/bcl"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidationResultSeverity int32

const (
	ValidationResultSeverity_Unknown     ValidationResultSeverity = 0
	ValidationResultSeverity_Information ValidationResultSeverity = 1
	ValidationResultSeverity_Warning     ValidationResultSeverity = 2
	ValidationResultSeverity_Error       ValidationResultSeverity = 3
)

// Enum value maps for ValidationResultSeverity.
var (
	ValidationResultSeverity_name = map[int32]string{
		0: "Unknown",
		1: "Information",
		2: "Warning",
		3: "Error",
	}
	ValidationResultSeverity_value = map[string]int32{
		"Unknown":     0,
		"Information": 1,
		"Warning":     2,
		"Error":       3,
	}
)

func (x ValidationResultSeverity) Enum() *ValidationResultSeverity {
	p := new(ValidationResultSeverity)
	*p = x
	return p
}

func (x ValidationResultSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidationResultSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_namespaces_proto_enumTypes[0].Descriptor()
}

func (ValidationResultSeverity) Type() protoreflect.EnumType {
	return &file_namespaces_proto_enumTypes[0]
}

func (x ValidationResultSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidationResultSeverity.Descriptor instead.
func (ValidationResultSeverity) EnumDescriptor() ([]byte, []int) {
	return file_namespaces_proto_rawDescGZIP(), []int{0}
}

type AllNamespacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventStore    string                 `protobuf:"bytes,1,opt,name=EventStore,proto3" json:"EventStore,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllNamespacesRequest) Reset() {
	*x = AllNamespacesRequest{}
	mi := &file_namespaces_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllNamespacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllNamespacesRequest) ProtoMessage() {}

func (x *AllNamespacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_namespaces_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllNamespacesRequest.ProtoReflect.Descriptor instead.
func (*AllNamespacesRequest) Descriptor() ([]byte, []int) {
	return file_namespaces_proto_rawDescGZIP(), []int{0}
}

func (x *AllNamespacesRequest) GetEventStore() string {
	if x != nil {
		return x.EventStore
	}
	return ""
}

type CommandResult struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId              *bcl.Guid              `protobuf:"bytes,1,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"` // default value could not be applied: 00000000-0000-0000-0000-000000000000
	IsAuthorized               bool                   `protobuf:"varint,2,opt,name=IsAuthorized,proto3" json:"IsAuthorized,omitempty"`
	ValidationResults          []*ValidationResult    `protobuf:"bytes,3,rep,name=ValidationResults,proto3" json:"ValidationResults,omitempty"`
	ExceptionMessages          []string               `protobuf:"bytes,4,rep,name=ExceptionMessages,proto3" json:"ExceptionMessages,omitempty"`
	ExceptionStackTrace        string                 `protobuf:"bytes,5,opt,name=ExceptionStackTrace,proto3" json:"ExceptionStackTrace,omitempty"`
	AuthorizationFailureReason string                 `protobuf:"bytes,6,opt,name=AuthorizationFailureReason,proto3" json:"AuthorizationFailureReason,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_namespaces_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_namespaces_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_namespaces_proto_rawDescGZIP(), []int{1}
}

func (x *CommandResult) GetCorrelationId() *bcl.Guid {
	if x != nil {
		return x.CorrelationId
	}
	return nil
}

func (x *CommandResult) GetIsAuthorized() bool {
	if x != nil {
		return x.IsAuthorized
	}
	return false
}

func (x *CommandResult) GetValidationResults() []*ValidationResult {
	if x != nil {
		return x.ValidationResults
	}
	return nil
}

func (x *CommandResult) GetExceptionMessages() []string {
	if x != nil {
		return x.ExceptionMessages
	}
	return nil
}

func (x *CommandResult) GetExceptionStackTrace() string {
	if x != nil {
		return x.ExceptionStackTrace
	}
	return ""
}

func (x *CommandResult) GetAuthorizationFailureReason() string {
	if x != nil {
		return x.AuthorizationFailureReason
	}
	return ""
}

type EnsureNamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventStore    string                 `protobuf:"bytes,1,opt,name=EventStore,proto3" json:"EventStore,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureNamespaceRequest) Reset() {
	*x = EnsureNamespaceRequest{}
	mi := &file_namespaces_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureNamespaceRequest) ProtoMessage() {}

func (x *EnsureNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_namespaces_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureNamespaceRequest.ProtoReflect.Descriptor instead.
func (*EnsureNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_namespaces_proto_rawDescGZIP(), []int{2}
}

func (x *EnsureNamespaceRequest) GetEventStore() string {
	if x != nil {
		return x.EventStore
	}
	return ""
}

func (x *EnsureNamespaceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type NamespaceNamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceNamesResponse) Reset() {
	*x = NamespaceNamesResponse{}
	mi := &file_namespaces_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceNamesResponse) ProtoMessage() {}

func (x *NamespaceNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_namespaces_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceNamesResponse.ProtoReflect.Descriptor instead.
func (*NamespaceNamesResponse) Descriptor() ([]byte, []int) {
	return file_namespaces_proto_rawDescGZIP(), []int{3}
}

func (x *NamespaceNamesResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NamespaceNamesResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ObserveNamespacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventStore    string                 `protobuf:"bytes,1,opt,name=EventStore,proto3" json:"EventStore,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserveNamespacesRequest) Reset() {
	*x = ObserveNamespacesRequest{}
	mi := &file_namespaces_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveNamespacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveNamespacesRequest) ProtoMessage() {}

func (x *ObserveNamespacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_namespaces_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveNamespacesRequest.ProtoReflect.Descriptor instead.
func (*ObserveNamespacesRequest) Descriptor() ([]byte, []int) {
	return file_namespaces_proto_rawDescGZIP(), []int{4}
}

func (x *ObserveNamespacesRequest) GetEventStore() string {
	if x != nil {
		return x.EventStore
	}
	return ""
}

type QueryResult_IEnumerable_NamespaceNamesResponse struct {
	state               protoimpl.MessageState    `protogen:"open.v1"`
	CorrelationId       *bcl.Guid                 `protobuf:"bytes,1,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"` // default value could not be applied: 00000000-0000-0000-0000-000000000000
	IsAuthorized        bool                      `protobuf:"varint,2,opt,name=IsAuthorized,proto3" json:"IsAuthorized,omitempty"`
	ValidationResults   []*ValidationResult       `protobuf:"bytes,3,rep,name=ValidationResults,proto3" json:"ValidationResults,omitempty"`
	ExceptionMessages   []string                  `protobuf:"bytes,4,rep,name=ExceptionMessages,proto3" json:"ExceptionMessages,omitempty"`
	ExceptionStackTrace string                    `protobuf:"bytes,5,opt,name=ExceptionStackTrace,proto3" json:"ExceptionStackTrace,omitempty"`
	Data                []*NamespaceNamesResponse `protobuf:"bytes,6,rep,name=Data,proto3" json:"Data,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QueryResult_IEnumerable_NamespaceNamesResponse) Reset() {
	*x = QueryResult_IEnumerable_NamespaceNamesResponse{}
	mi := &file_namespaces_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult_IEnumerable_NamespaceNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult_IEnumerable_NamespaceNamesResponse) ProtoMessage() {}

func (x *QueryResult_IEnumerable_NamespaceNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_namespaces_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult_IEnumerable_NamespaceNamesResponse.ProtoReflect.Descriptor instead.
func (*QueryResult_IEnumerable_NamespaceNamesResponse) Descriptor() ([]byte, []int) {
	return file_namespaces_proto_rawDescGZIP(), []int{5}
}

func (x *QueryResult_IEnumerable_NamespaceNamesResponse) GetCorrelationId() *bcl.Guid {
	if x != nil {
		return x.CorrelationId
	}
	return nil
}

func (x *QueryResult_IEnumerable_NamespaceNamesResponse) GetIsAuthorized() bool {
	if x != nil {
		return x.IsAuthorized
	}
	return false
}

func (x *QueryResult_IEnumerable_NamespaceNamesResponse) GetValidationResults() []*ValidationResult {
	if x != nil {
		return x.ValidationResults
	}
	return nil
}

func (x *QueryResult_IEnumerable_NamespaceNamesResponse) GetExceptionMessages() []string {
	if x != nil {
		return x.ExceptionMessages
	}
	return nil
}

func (x *QueryResult_IEnumerable_NamespaceNamesResponse) GetExceptionStackTrace() string {
	if x != nil {
		return x.ExceptionStackTrace
	}
	return ""
}

func (x *QueryResult_IEnumerable_NamespaceNamesResponse) GetData() []*NamespaceNamesResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ValidationResult struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Severity      ValidationResultSeverity `protobuf:"varint,1,opt,name=Severity,proto3,enum=Cratis.Chronicle.Contracts.Namespaces.ValidationResultSeverity" json:"Severity,omitempty"` // default value could not be applied: Error
	Message       string                   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Members       []string                 `protobuf:"bytes,3,rep,name=Members,proto3" json:"Members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationResult) Reset() {
	*x = ValidationResult{}
	mi := &file_namespaces_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResult) ProtoMessage() {}

func (x *ValidationResult) ProtoReflect() protoreflect.Message {
	mi := &file_namespaces_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResult.ProtoReflect.Descriptor instead.
func (*ValidationResult) Descriptor() ([]byte, []int) {
	return file_namespaces_proto_rawDescGZIP(), []int{6}
}

func (x *ValidationResult) GetSeverity() ValidationResultSeverity {
	if x != nil {
		return x.Severity
	}
	return ValidationResultSeverity_Unknown
}

func (x *ValidationResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationResult) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_namespaces_proto protoreflect.FileDescriptor

const file_namespaces_proto_rawDesc = "" +
	"\n" +
	"\x10namespaces.proto\x12%Cratis.Chronicle.Contracts.Namespaces\x1a\x16protobuf-net/bcl.proto\"6\n" +
	"\x14AllNamespacesRequest\x12\x1e\n" +
	"\n" +
	"EventStore\x18\x01 \x01(\tR\n" +
	"EventStore\"\xeb\x02\n" +
	"\rCommandResult\x12/\n" +
	"\rCorrelationId\x18\x01 \x01(\v2\t.bcl.GuidR\rCorrelationId\x12\"\n" +
	"\fIsAuthorized\x18\x02 \x01(\bR\fIsAuthorized\x12e\n" +
	"\x11ValidationResults\x18\x03 \x03(\v27.Cratis.Chronicle.Contracts.Namespaces.ValidationResultR\x11ValidationResults\x12,\n" +
	"\x11ExceptionMessages\x18\x04 \x03(\tR\x11ExceptionMessages\x120\n" +
	"\x13ExceptionStackTrace\x18\x05 \x01(\tR\x13ExceptionStackTrace\x12>\n" +
	"\x1aAuthorizationFailureReason\x18\x06 \x01(\tR\x1aAuthorizationFailureReason\"V\n" +
	"\x16EnsureNamespaceRequest\x12\x1e\n" +
	"\n" +
	"EventStore\x18\x01 \x01(\tR\n" +
	"EventStore\x12\x1c\n" +
	"\tNamespace\x18\x02 \x01(\tR\tNamespace\"<\n" +
	"\x16NamespaceNamesResponse\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x0e\n" +
	"\x02Id\x18\x02 \x01(\tR\x02Id\":\n" +
	"\x18ObserveNamespacesRequest\x12\x1e\n" +
	"\n" +
	"EventStore\x18\x01 \x01(\tR\n" +
	"EventStore\"\x9f\x03\n" +
	".QueryResult_IEnumerable_NamespaceNamesResponse\x12/\n" +
	"\rCorrelationId\x18\x01 \x01(\v2\t.bcl.GuidR\rCorrelationId\x12\"\n" +
	"\fIsAuthorized\x18\x02 \x01(\bR\fIsAuthorized\x12e\n" +
	"\x11ValidationResults\x18\x03 \x03(\v27.Cratis.Chronicle.Contracts.Namespaces.ValidationResultR\x11ValidationResults\x12,\n" +
	"\x11ExceptionMessages\x18\x04 \x03(\tR\x11ExceptionMessages\x120\n" +
	"\x13ExceptionStackTrace\x18\x05 \x01(\tR\x13ExceptionStackTrace\x12Q\n" +
	"\x04Data\x18\x06 \x03(\v2=.Cratis.Chronicle.Contracts.Namespaces.NamespaceNamesResponseR\x04Data\"\xa3\x01\n" +
	"\x10ValidationResult\x12[\n" +
	"\bSeverity\x18\x01 \x01(\x0e2?.Cratis.Chronicle.Contracts.Namespaces.ValidationResultSeverityR\bSeverity\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\x12\x18\n" +
	"\aMembers\x18\x03 \x03(\tR\aMembers*P\n" +
	"\x18ValidationResultSeverity\x12\v\n" +
	"\aUnknown\x10\x00\x12\x0f\n" +
	"\vInformation\x10\x01\x12\v\n" +
	"\aWarning\x10\x02\x12\t\n" +
	"\x05Error\x10\x032\xeb\x03\n" +
	"\n" +
	"Namespaces\x12\xa3\x01\n" +
	"\rAllNamespaces\x12;.Cratis.Chronicle.Contracts.Namespaces.AllNamespacesRequest\x1aU.Cratis.Chronicle.Contracts.Namespaces.QueryResult_IEnumerable_NamespaceNamesResponse\x12\x86\x01\n" +
	"\x0fEnsureNamespace\x12=.Cratis.Chronicle.Contracts.Namespaces.EnsureNamespaceRequest\x1a4.Cratis.Chronicle.Contracts.Namespaces.CommandResult\x12\xad\x01\n" +
	"\x11ObserveNamespaces\x12?.Cratis.Chronicle.Contracts.Namespaces.ObserveNamespacesRequest\x1aU.Cratis.Chronicle.Contracts.Namespaces.QueryResult_IEnumerable_NamespaceNamesResponse0\x01B\xa9\x02\n" +
	")com.Cratis.Chronicle.Contracts.NamespacesB\x0fNamespacesProtoP\x01Z3github.com/cratis/chronicle.go/contracts/namespaces\xa2\x02\x04CCCN\xaa\x02%Cratis.Chronicle.Contracts.Namespaces\xca\x02%Cratis\\Chronicle\\Contracts\\Namespaces\xe2\x021Cratis\\Chronicle\\Contracts\\Namespaces\\GPBMetadata\xea\x02(Cratis::Chronicle::Contracts::Namespacesb\x06proto3"

var (
	file_namespaces_proto_rawDescOnce sync.Once
	file_namespaces_proto_rawDescData []byte
)

func file_namespaces_proto_rawDescGZIP() []byte {
	file_namespaces_proto_rawDescOnce.Do(func() {
		file_namespaces_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_namespaces_proto_rawDesc), len(file_namespaces_proto_rawDesc)))
	})
	return file_namespaces_proto_rawDescData
}

var file_namespaces_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_namespaces_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_namespaces_proto_goTypes = []any{
	(ValidationResultSeverity)(0),                          // 0: Cratis.Chronicle.Contracts.Namespaces.ValidationResultSeverity
	(*AllNamespacesRequest)(nil),                           // 1: Cratis.Chronicle.Contracts.Namespaces.AllNamespacesRequest
	(*CommandResult)(nil),                                  // 2: Cratis.Chronicle.Contracts.Namespaces.CommandResult
	(*EnsureNamespaceRequest)(nil),                         // 3: Cratis.Chronicle.Contracts.Namespaces.EnsureNamespaceRequest
	(*NamespaceNamesResponse)(nil),                         // 4: Cratis.Chronicle.Contracts.Namespaces.NamespaceNamesResponse
	(*ObserveNamespacesRequest)(nil),                       // 5: Cratis.Chronicle.Contracts.Namespaces.ObserveNamespacesRequest
	(*QueryResult_IEnumerable_NamespaceNamesResponse)(nil), // 6: Cratis.Chronicle.Contracts.Namespaces.QueryResult_IEnumerable_NamespaceNamesResponse
	(*ValidationResult)(nil),                               // 7: Cratis.Chronicle.Contracts.Namespaces.ValidationResult
	(*bcl.Guid)(nil),                                       // 8: bcl.Guid
}
var file_namespaces_proto_depIdxs = []int32{
	8, // 0: Cratis.Chronicle.Contracts.Namespaces.CommandResult.CorrelationId:type_name -> bcl.Guid
	7, // 1: Cratis.Chronicle.Contracts.Namespaces.CommandResult.ValidationResults:type_name -> Cratis.Chronicle.Contracts.Namespaces.ValidationResult
	8, // 2: Cratis.Chronicle.Contracts.Namespaces.QueryResult_IEnumerable_NamespaceNamesResponse.CorrelationId:type_name -> bcl.Guid
	7, // 3: Cratis.Chronicle.Contracts.Namespaces.QueryResult_IEnumerable_NamespaceNamesResponse.ValidationResults:type_name -> Cratis.Chronicle.Contracts.Namespaces.ValidationResult
	4, // 4: Cratis.Chronicle.Contracts.Namespaces.QueryResult_IEnumerable_NamespaceNamesResponse.Data:type_name -> Cratis.Chronicle.Contracts.Namespaces.NamespaceNamesResponse
	0, // 5: Cratis.Chronicle.Contracts.Namespaces.ValidationResult.Severity:type_name -> Cratis.Chronicle.Contracts.Namespaces.ValidationResultSeverity
	1, // 6: Cratis.Chronicle.Contracts.Namespaces.Namespaces.AllNamespaces:input_type -> Cratis.Chronicle.Contracts.Namespaces.AllNamespacesRequest
	3, // 7: Cratis.Chronicle.Contracts.Namespaces.Namespaces.EnsureNamespace:input_type -> Cratis.Chronicle.Contracts.Namespaces.EnsureNamespaceRequest
	5, // 8: Cratis.Chronicle.Contracts.Namespaces.Namespaces.ObserveNamespaces:input_type -> Cratis.Chronicle.Contracts.Namespaces.ObserveNamespacesRequest
	6, // 9: Cratis.Chronicle.Contracts.Namespaces.Namespaces.AllNamespaces:output_type -> Cratis.Chronicle.Contracts.Namespaces.QueryResult_IEnumerable_NamespaceNamesResponse
	2, // 10: Cratis.Chronicle.Contracts.Namespaces.Namespaces.EnsureNamespace:output_type -> Cratis.Chronicle.Contracts.Namespaces.CommandResult
	6, // 11: Cratis.Chronicle.Contracts.Namespaces.Namespaces.ObserveNamespaces:output_type -> Cratis.Chronicle.Contracts.Namespaces.QueryResult_IEnumerable_NamespaceNamesResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_namespaces_proto_init() }
func file_namespaces_proto_init() {
	if File_namespaces_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_namespaces_proto_rawDesc), len(file_namespaces_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_namespaces_proto_goTypes,
		DependencyIndexes: file_namespaces_proto_depIdxs,
		EnumInfos:         file_namespaces_proto_enumTypes,
		MessageInfos:      file_namespaces_proto_msgTypes,
	}.Build()
	File_namespaces_proto = out.File
	file_namespaces_proto_goTypes = nil
	file_namespaces_proto_depIdxs = nil
}
