// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: eventsequences.proto

package eventsequences

import (
	bcl "github.com/cratis/chronicle.go/contracts/bcl"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidationResultSeverity int32

const (
	ValidationResultSeverity_Unknown     ValidationResultSeverity = 0
	ValidationResultSeverity_Information ValidationResultSeverity = 1
	ValidationResultSeverity_Warning     ValidationResultSeverity = 2
	ValidationResultSeverity_Error       ValidationResultSeverity = 3
)

// Enum value maps for ValidationResultSeverity.
var (
	ValidationResultSeverity_name = map[int32]string{
		0: "Unknown",
		1: "Information",
		2: "Warning",
		3: "Error",
	}
	ValidationResultSeverity_value = map[string]int32{
		"Unknown":     0,
		"Information": 1,
		"Warning":     2,
		"Error":       3,
	}
)

func (x ValidationResultSeverity) Enum() *ValidationResultSeverity {
	p := new(ValidationResultSeverity)
	*p = x
	return p
}

func (x ValidationResultSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidationResultSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_eventsequences_proto_enumTypes[0].Descriptor()
}

func (ValidationResultSeverity) Type() protoreflect.EnumType {
	return &file_eventsequences_proto_enumTypes[0]
}

func (x ValidationResultSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidationResultSeverity.Descriptor instead.
func (ValidationResultSeverity) EnumDescriptor() ([]byte, []int) {
	return file_eventsequences_proto_rawDescGZIP(), []int{0}
}

type IsStreamCompletedRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventSequenceId string                 `protobuf:"bytes,1,opt,name=EventSequenceId,proto3" json:"EventSequenceId,omitempty"`
	EventStore      string                 `protobuf:"bytes,2,opt,name=EventStore,proto3" json:"EventStore,omitempty"`
	Namespace       string                 `protobuf:"bytes,3,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	EventStreamType string                 `protobuf:"bytes,4,opt,name=EventStreamType,proto3" json:"EventStreamType,omitempty"`
	EventStreamId   string                 `protobuf:"bytes,5,opt,name=EventStreamId,proto3" json:"EventStreamId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IsStreamCompletedRequest) Reset() {
	*x = IsStreamCompletedRequest{}
	mi := &file_eventsequences_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsStreamCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsStreamCompletedRequest) ProtoMessage() {}

func (x *IsStreamCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventsequences_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsStreamCompletedRequest.ProtoReflect.Descriptor instead.
func (*IsStreamCompletedRequest) Descriptor() ([]byte, []int) {
	return file_eventsequences_proto_rawDescGZIP(), []int{0}
}

func (x *IsStreamCompletedRequest) GetEventSequenceId() string {
	if x != nil {
		return x.EventSequenceId
	}
	return ""
}

func (x *IsStreamCompletedRequest) GetEventStore() string {
	if x != nil {
		return x.EventStore
	}
	return ""
}

func (x *IsStreamCompletedRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *IsStreamCompletedRequest) GetEventStreamType() string {
	if x != nil {
		return x.EventStreamType
	}
	return ""
}

func (x *IsStreamCompletedRequest) GetEventStreamId() string {
	if x != nil {
		return x.EventStreamId
	}
	return ""
}

type QueryResult_Boolean struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId       *bcl.Guid              `protobuf:"bytes,1,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"` // default value could not be applied: 00000000-0000-0000-0000-000000000000
	IsAuthorized        bool                   `protobuf:"varint,2,opt,name=IsAuthorized,proto3" json:"IsAuthorized,omitempty"`
	ValidationResults   []*ValidationResult    `protobuf:"bytes,3,rep,name=ValidationResults,proto3" json:"ValidationResults,omitempty"`
	ExceptionMessages   []string               `protobuf:"bytes,4,rep,name=ExceptionMessages,proto3" json:"ExceptionMessages,omitempty"`
	ExceptionStackTrace string                 `protobuf:"bytes,5,opt,name=ExceptionStackTrace,proto3" json:"ExceptionStackTrace,omitempty"`
	Data                bool                   `protobuf:"varint,6,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QueryResult_Boolean) Reset() {
	*x = QueryResult_Boolean{}
	mi := &file_eventsequences_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult_Boolean) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult_Boolean) ProtoMessage() {}

func (x *QueryResult_Boolean) ProtoReflect() protoreflect.Message {
	mi := &file_eventsequences_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult_Boolean.ProtoReflect.Descriptor instead.
func (*QueryResult_Boolean) Descriptor() ([]byte, []int) {
	return file_eventsequences_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResult_Boolean) GetCorrelationId() *bcl.Guid {
	if x != nil {
		return x.CorrelationId
	}
	return nil
}

func (x *QueryResult_Boolean) GetIsAuthorized() bool {
	if x != nil {
		return x.IsAuthorized
	}
	return false
}

func (x *QueryResult_Boolean) GetValidationResults() []*ValidationResult {
	if x != nil {
		return x.ValidationResults
	}
	return nil
}

func (x *QueryResult_Boolean) GetExceptionMessages() []string {
	if x != nil {
		return x.ExceptionMessages
	}
	return nil
}

func (x *QueryResult_Boolean) GetExceptionStackTrace() string {
	if x != nil {
		return x.ExceptionStackTrace
	}
	return ""
}

func (x *QueryResult_Boolean) GetData() bool {
	if x != nil {
		return x.Data
	}
	return false
}

type ValidationResult struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Severity      ValidationResultSeverity `protobuf:"varint,1,opt,name=Severity,proto3,enum=Cratis.Chronicle.Contracts.EventSequences.ValidationResultSeverity" json:"Severity,omitempty"` // default value could not be applied: Error
	Message       string                   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Members       []string                 `protobuf:"bytes,3,rep,name=Members,proto3" json:"Members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationResult) Reset() {
	*x = ValidationResult{}
	mi := &file_eventsequences_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResult) ProtoMessage() {}

func (x *ValidationResult) ProtoReflect() protoreflect.Message {
	mi := &file_eventsequences_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResult.ProtoReflect.Descriptor instead.
func (*ValidationResult) Descriptor() ([]byte, []int) {
	return file_eventsequences_proto_rawDescGZIP(), []int{2}
}

func (x *ValidationResult) GetSeverity() ValidationResultSeverity {
	if x != nil {
		return x.Severity
	}
	return ValidationResultSeverity_Unknown
}

func (x *ValidationResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationResult) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_eventsequences_proto protoreflect.FileDescriptor

const file_eventsequences_proto_rawDesc = "" +
	"\n" +
	"\x14eventsequences.proto\x12)Cratis.Chronicle.Contracts.EventSequences\x1a\x16protobuf-net/bcl.proto\"\xd2\x01\n" +
	"\x18IsStreamCompletedRequest\x12(\n" +
	"\x0fEventSequenceId\x18\x01 \x01(\tR\x0fEventSequenceId\x12\x1e\n" +
	"\n" +
	"EventStore\x18\x02 \x01(\tR\n" +
	"EventStore\x12\x1c\n" +
	"\tNamespace\x18\x03 \x01(\tR\tNamespace\x12(\n" +
	"\x0fEventStreamType\x18\x04 \x01(\tR\x0fEventStreamType\x12$\n" +
	"\rEventStreamId\x18\x05 \x01(\tR\rEventStreamId\"\xc9\x02\n" +
	"\x13QueryResult_Boolean\x12/\n" +
	"\rCorrelationId\x18\x01 \x01(\v2\t.bcl.GuidR\rCorrelationId\x12\"\n" +
	"\fIsAuthorized\x18\x02 \x01(\bR\fIsAuthorized\x12i\n" +
	"\x11ValidationResults\x18\x03 \x03(\v2;.Cratis.Chronicle.Contracts.EventSequences.ValidationResultR\x11ValidationResults\x12,\n" +
	"\x11ExceptionMessages\x18\x04 \x03(\tR\x11ExceptionMessages\x120\n" +
	"\x13ExceptionStackTrace\x18\x05 \x01(\tR\x13ExceptionStackTrace\x12\x12\n" +
	"\x04Data\x18\x06 \x01(\bR\x04Data\"\xa7\x01\n" +
	"\x10ValidationResult\x12_\n" +
	"\bSeverity\x18\x01 \x01(\x0e2C.Cratis.Chronicle.Contracts.EventSequences.ValidationResultSeverityR\bSeverity\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\x12\x18\n" +
	"\aMembers\x18\x03 \x03(\tR\aMembers*P\n" +
	"\x18ValidationResultSeverity\x12\v\n" +
	"\aUnknown\x10\x00\x12\x0f\n" +
	"\vInformation\x10\x01\x12\v\n" +
	"\aWarning\x10\x02\x12\t\n" +
	"\x05Error\x10\x032\xb1\x01\n" +
	"\x14EventSequenceQueries\x12\x98\x01\n" +
	"\x11IsStreamCompleted\x12C.Cratis.Chronicle.Contracts.EventSequences.IsStreamCompletedRequest\x1a>.Cratis.Chronicle.Contracts.EventSequences.QueryResult_BooleanB\xc5\x02\n" +
	"-com.Cratis.Chronicle.Contracts.EventSequencesB\x13EventsequencesProtoP\x01Z7github.com/cratis/chronicle.go/contracts/eventsequences\xa2\x02\x04CCCE\xaa\x02)Cratis.Chronicle.Contracts.EventSequences\xca\x02)Cratis\\Chronicle\\Contracts\\EventSequences\xe2\x025Cratis\\Chronicle\\Contracts\\EventSequences\\GPBMetadata\xea\x02,Cratis::Chronicle::Contracts::EventSequencesb\x06proto3"

var (
	file_eventsequences_proto_rawDescOnce sync.Once
	file_eventsequences_proto_rawDescData []byte
)

func file_eventsequences_proto_rawDescGZIP() []byte {
	file_eventsequences_proto_rawDescOnce.Do(func() {
		file_eventsequences_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eventsequences_proto_rawDesc), len(file_eventsequences_proto_rawDesc)))
	})
	return file_eventsequences_proto_rawDescData
}

var file_eventsequences_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_eventsequences_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_eventsequences_proto_goTypes = []any{
	(ValidationResultSeverity)(0),    // 0: Cratis.Chronicle.Contracts.EventSequences.ValidationResultSeverity
	(*IsStreamCompletedRequest)(nil), // 1: Cratis.Chronicle.Contracts.EventSequences.IsStreamCompletedRequest
	(*QueryResult_Boolean)(nil),      // 2: Cratis.Chronicle.Contracts.EventSequences.QueryResult_Boolean
	(*ValidationResult)(nil),         // 3: Cratis.Chronicle.Contracts.EventSequences.ValidationResult
	(*bcl.Guid)(nil),                 // 4: bcl.Guid
}
var file_eventsequences_proto_depIdxs = []int32{
	4, // 0: Cratis.Chronicle.Contracts.EventSequences.QueryResult_Boolean.CorrelationId:type_name -> bcl.Guid
	3, // 1: Cratis.Chronicle.Contracts.EventSequences.QueryResult_Boolean.ValidationResults:type_name -> Cratis.Chronicle.Contracts.EventSequences.ValidationResult
	0, // 2: Cratis.Chronicle.Contracts.EventSequences.ValidationResult.Severity:type_name -> Cratis.Chronicle.Contracts.EventSequences.ValidationResultSeverity
	1, // 3: Cratis.Chronicle.Contracts.EventSequences.EventSequenceQueries.IsStreamCompleted:input_type -> Cratis.Chronicle.Contracts.EventSequences.IsStreamCompletedRequest
	2, // 4: Cratis.Chronicle.Contracts.EventSequences.EventSequenceQueries.IsStreamCompleted:output_type -> Cratis.Chronicle.Contracts.EventSequences.QueryResult_Boolean
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_eventsequences_proto_init() }
func file_eventsequences_proto_init() {
	if File_eventsequences_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eventsequences_proto_rawDesc), len(file_eventsequences_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eventsequences_proto_goTypes,
		DependencyIndexes: file_eventsequences_proto_depIdxs,
		EnumInfos:         file_eventsequences_proto_enumTypes,
		MessageInfos:      file_eventsequences_proto_msgTypes,
	}.Build()
	File_eventsequences_proto = out.File
	file_eventsequences_proto_goTypes = nil
	file_eventsequences_proto_depIdxs = nil
}
