// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: clients.proto

package clients

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConnectionService_CheckCompatibility_FullMethodName      = "/Cratis.Chronicle.Contracts.Clients.ConnectionService/CheckCompatibility"
	ConnectionService_Connect_FullMethodName                 = "/Cratis.Chronicle.Contracts.Clients.ConnectionService/Connect"
	ConnectionService_ConnectionKeepAlive_FullMethodName     = "/Cratis.Chronicle.Contracts.Clients.ConnectionService/ConnectionKeepAlive"
	ConnectionService_GetConnectedClients_FullMethodName     = "/Cratis.Chronicle.Contracts.Clients.ConnectionService/GetConnectedClients"
	ConnectionService_GetDescriptorSet_FullMethodName        = "/Cratis.Chronicle.Contracts.Clients.ConnectionService/GetDescriptorSet"
	ConnectionService_ObserveConnectedClients_FullMethodName = "/Cratis.Chronicle.Contracts.Clients.ConnectionService/ObserveConnectedClients"
)

// ConnectionServiceClient is the client API for ConnectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConnectionServiceClient interface {
	CheckCompatibility(ctx context.Context, in *CompatibilityRequest, opts ...grpc.CallOption) (*CompatibilityResponse, error)
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConnectionKeepAlive], error)
	ConnectionKeepAlive(ctx context.Context, in *ConnectionKeepAlive, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetConnectedClients(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*IEnumerable_ConnectedClient, error)
	GetDescriptorSet(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DescriptorSetResponse, error)
	ObserveConnectedClients(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IEnumerable_ConnectedClient], error)
}

type connectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectionServiceClient(cc grpc.ClientConnInterface) ConnectionServiceClient {
	return &connectionServiceClient{cc}
}

func (c *connectionServiceClient) CheckCompatibility(ctx context.Context, in *CompatibilityRequest, opts ...grpc.CallOption) (*CompatibilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompatibilityResponse)
	err := c.cc.Invoke(ctx, ConnectionService_CheckCompatibility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConnectionKeepAlive], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConnectionService_ServiceDesc.Streams[0], ConnectionService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConnectRequest, ConnectionKeepAlive]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectionService_ConnectClient = grpc.ServerStreamingClient[ConnectionKeepAlive]

func (c *connectionServiceClient) ConnectionKeepAlive(ctx context.Context, in *ConnectionKeepAlive, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ConnectionService_ConnectionKeepAlive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) GetConnectedClients(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*IEnumerable_ConnectedClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IEnumerable_ConnectedClient)
	err := c.cc.Invoke(ctx, ConnectionService_GetConnectedClients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) GetDescriptorSet(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DescriptorSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescriptorSetResponse)
	err := c.cc.Invoke(ctx, ConnectionService_GetDescriptorSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) ObserveConnectedClients(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IEnumerable_ConnectedClient], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConnectionService_ServiceDesc.Streams[1], ConnectionService_ObserveConnectedClients_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, IEnumerable_ConnectedClient]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectionService_ObserveConnectedClientsClient = grpc.ServerStreamingClient[IEnumerable_ConnectedClient]

// ConnectionServiceServer is the server API for ConnectionService service.
// All implementations must embed UnimplementedConnectionServiceServer
// for forward compatibility.
type ConnectionServiceServer interface {
	CheckCompatibility(context.Context, *CompatibilityRequest) (*CompatibilityResponse, error)
	Connect(*ConnectRequest, grpc.ServerStreamingServer[ConnectionKeepAlive]) error
	ConnectionKeepAlive(context.Context, *ConnectionKeepAlive) (*emptypb.Empty, error)
	GetConnectedClients(context.Context, *emptypb.Empty) (*IEnumerable_ConnectedClient, error)
	GetDescriptorSet(context.Context, *emptypb.Empty) (*DescriptorSetResponse, error)
	ObserveConnectedClients(*emptypb.Empty, grpc.ServerStreamingServer[IEnumerable_ConnectedClient]) error
	mustEmbedUnimplementedConnectionServiceServer()
}

// UnimplementedConnectionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConnectionServiceServer struct{}

func (UnimplementedConnectionServiceServer) CheckCompatibility(context.Context, *CompatibilityRequest) (*CompatibilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckCompatibility not implemented")
}
func (UnimplementedConnectionServiceServer) Connect(*ConnectRequest, grpc.ServerStreamingServer[ConnectionKeepAlive]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedConnectionServiceServer) ConnectionKeepAlive(context.Context, *ConnectionKeepAlive) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectionKeepAlive not implemented")
}
func (UnimplementedConnectionServiceServer) GetConnectedClients(context.Context, *emptypb.Empty) (*IEnumerable_ConnectedClient, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConnectedClients not implemented")
}
func (UnimplementedConnectionServiceServer) GetDescriptorSet(context.Context, *emptypb.Empty) (*DescriptorSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDescriptorSet not implemented")
}
func (UnimplementedConnectionServiceServer) ObserveConnectedClients(*emptypb.Empty, grpc.ServerStreamingServer[IEnumerable_ConnectedClient]) error {
	return status.Error(codes.Unimplemented, "method ObserveConnectedClients not implemented")
}
func (UnimplementedConnectionServiceServer) mustEmbedUnimplementedConnectionServiceServer() {}
func (UnimplementedConnectionServiceServer) testEmbeddedByValue()                           {}

// UnsafeConnectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectionServiceServer will
// result in compilation errors.
type UnsafeConnectionServiceServer interface {
	mustEmbedUnimplementedConnectionServiceServer()
}

func RegisterConnectionServiceServer(s grpc.ServiceRegistrar, srv ConnectionServiceServer) {
	// If the following call panics, it indicates UnimplementedConnectionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConnectionService_ServiceDesc, srv)
}

func _ConnectionService_CheckCompatibility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompatibilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).CheckCompatibility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionService_CheckCompatibility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).CheckCompatibility(ctx, req.(*CompatibilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConnectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConnectionServiceServer).Connect(m, &grpc.GenericServerStream[ConnectRequest, ConnectionKeepAlive]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectionService_ConnectServer = grpc.ServerStreamingServer[ConnectionKeepAlive]

func _ConnectionService_ConnectionKeepAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionKeepAlive)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).ConnectionKeepAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionService_ConnectionKeepAlive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).ConnectionKeepAlive(ctx, req.(*ConnectionKeepAlive))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_GetConnectedClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).GetConnectedClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionService_GetConnectedClients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).GetConnectedClients(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_GetDescriptorSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).GetDescriptorSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionService_GetDescriptorSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).GetDescriptorSet(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_ObserveConnectedClients_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConnectionServiceServer).ObserveConnectedClients(m, &grpc.GenericServerStream[emptypb.Empty, IEnumerable_ConnectedClient]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectionService_ObserveConnectedClientsServer = grpc.ServerStreamingServer[IEnumerable_ConnectedClient]

// ConnectionService_ServiceDesc is the grpc.ServiceDesc for ConnectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Cratis.Chronicle.Contracts.Clients.ConnectionService",
	HandlerType: (*ConnectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckCompatibility",
			Handler:    _ConnectionService_CheckCompatibility_Handler,
		},
		{
			MethodName: "ConnectionKeepAlive",
			Handler:    _ConnectionService_ConnectionKeepAlive_Handler,
		},
		{
			MethodName: "GetConnectedClients",
			Handler:    _ConnectionService_GetConnectedClients_Handler,
		},
		{
			MethodName: "GetDescriptorSet",
			Handler:    _ConnectionService_GetDescriptorSet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _ConnectionService_Connect_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ObserveConnectedClients",
			Handler:       _ConnectionService_ObserveConnectedClients_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "clients.proto",
}
