// Code generated by scripts/generate-contracts.py. DO NOT EDIT.
// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

package contracts

// ProtocolVersion is the upstream Chronicle release.
const ProtocolVersion = "19.32.3"

// ProtocolCommit is the immutable schema source revision.
const ProtocolCommit = "e72af7ead164425141f29db61a9fe7b4915767e6"
