// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: eventsources.proto

package eventsources

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventSources_AllEventSources_FullMethodName      = "/Cratis.Chronicle.Contracts.EventSources.EventSources/AllEventSources"
	EventSources_ObserveEventSources_FullMethodName  = "/Cratis.Chronicle.Contracts.EventSources.EventSources/ObserveEventSources"
	EventSources_RegisterEventSources_FullMethodName = "/Cratis.Chronicle.Contracts.EventSources.EventSources/RegisterEventSources"
)

// EventSourcesClient is the client API for EventSources service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventSourcesClient interface {
	AllEventSources(ctx context.Context, in *AllEventSourcesRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_EventSourceDetailsResponse, error)
	ObserveEventSources(ctx context.Context, in *ObserveEventSourcesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResult_IEnumerable_EventSourceDetailsResponse], error)
	RegisterEventSources(ctx context.Context, in *RegisterEventSourcesRequest, opts ...grpc.CallOption) (*CommandResult, error)
}

type eventSourcesClient struct {
	cc grpc.ClientConnInterface
}

func NewEventSourcesClient(cc grpc.ClientConnInterface) EventSourcesClient {
	return &eventSourcesClient{cc}
}

func (c *eventSourcesClient) AllEventSources(ctx context.Context, in *AllEventSourcesRequest, opts ...grpc.CallOption) (*QueryResult_IEnumerable_EventSourceDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResult_IEnumerable_EventSourceDetailsResponse)
	err := c.cc.Invoke(ctx, EventSources_AllEventSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventSourcesClient) ObserveEventSources(ctx context.Context, in *ObserveEventSourcesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResult_IEnumerable_EventSourceDetailsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventSources_ServiceDesc.Streams[0], EventSources_ObserveEventSources_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ObserveEventSourcesRequest, QueryResult_IEnumerable_EventSourceDetailsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventSources_ObserveEventSourcesClient = grpc.ServerStreamingClient[QueryResult_IEnumerable_EventSourceDetailsResponse]

func (c *eventSourcesClient) RegisterEventSources(ctx context.Context, in *RegisterEventSourcesRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, EventSources_RegisterEventSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventSourcesServer is the server API for EventSources service.
// All implementations must embed UnimplementedEventSourcesServer
// for forward compatibility.
type EventSourcesServer interface {
	AllEventSources(context.Context, *AllEventSourcesRequest) (*QueryResult_IEnumerable_EventSourceDetailsResponse, error)
	ObserveEventSources(*ObserveEventSourcesRequest, grpc.ServerStreamingServer[QueryResult_IEnumerable_EventSourceDetailsResponse]) error
	RegisterEventSources(context.Context, *RegisterEventSourcesRequest) (*CommandResult, error)
	mustEmbedUnimplementedEventSourcesServer()
}

// UnimplementedEventSourcesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventSourcesServer struct{}

func (UnimplementedEventSourcesServer) AllEventSources(context.Context, *AllEventSourcesRequest) (*QueryResult_IEnumerable_EventSourceDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AllEventSources not implemented")
}
func (UnimplementedEventSourcesServer) ObserveEventSources(*ObserveEventSourcesRequest, grpc.ServerStreamingServer[QueryResult_IEnumerable_EventSourceDetailsResponse]) error {
	return status.Error(codes.Unimplemented, "method ObserveEventSources not implemented")
}
func (UnimplementedEventSourcesServer) RegisterEventSources(context.Context, *RegisterEventSourcesRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterEventSources not implemented")
}
func (UnimplementedEventSourcesServer) mustEmbedUnimplementedEventSourcesServer() {}
func (UnimplementedEventSourcesServer) testEmbeddedByValue()                      {}

// UnsafeEventSourcesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventSourcesServer will
// result in compilation errors.
type UnsafeEventSourcesServer interface {
	mustEmbedUnimplementedEventSourcesServer()
}

func RegisterEventSourcesServer(s grpc.ServiceRegistrar, srv EventSourcesServer) {
	// If the following call panics, it indicates UnimplementedEventSourcesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventSources_ServiceDesc, srv)
}

func _EventSources_AllEventSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllEventSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSourcesServer).AllEventSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSources_AllEventSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSourcesServer).AllEventSources(ctx, req.(*AllEventSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventSources_ObserveEventSources_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ObserveEventSourcesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventSourcesServer).ObserveEventSources(m, &grpc.GenericServerStream[ObserveEventSourcesRequest, QueryResult_IEnumerable_EventSourceDetailsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventSources_ObserveEventSourcesServer = grpc.ServerStreamingServer[QueryResult_IEnumerable_EventSourceDetailsResponse]

func _EventSources_RegisterEventSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterEventSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSourcesServer).RegisterEventSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventSources_RegisterEventSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSourcesServer).RegisterEventSources(ctx, req.(*RegisterEventSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventSources_ServiceDesc is the grpc.ServiceDesc for EventSources service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventSources_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Cratis.Chronicle.Contracts.EventSources.EventSources",
	HandlerType: (*EventSourcesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllEventSources",
			Handler:    _EventSources_AllEventSources_Handler,
		},
		{
			MethodName: "RegisterEventSources",
			Handler:    _EventSources_RegisterEventSources_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ObserveEventSources",
			Handler:       _EventSources_ObserveEventSources_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "eventsources.proto",
}
