// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: observation_reducers.proto

package reducers

import (
	bcl "github.com/cratis/chronicle.go/contracts/bcl"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventObservationState int32

const (
	EventObservationState_EVENT_OBSERVATION_STATE_None EventObservationState = 0
	EventObservationState_Initial                      EventObservationState = 1
	EventObservationState_Replay                       EventObservationState = 2
)

// Enum value maps for EventObservationState.
var (
	EventObservationState_name = map[int32]string{
		0: "EVENT_OBSERVATION_STATE_None",
		1: "Initial",
		2: "Replay",
	}
	EventObservationState_value = map[string]int32{
		"EVENT_OBSERVATION_STATE_None": 0,
		"Initial":                      1,
		"Replay":                       2,
	}
)

func (x EventObservationState) Enum() *EventObservationState {
	p := new(EventObservationState)
	*p = x
	return p
}

func (x EventObservationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventObservationState) Descriptor() protoreflect.EnumDescriptor {
	return file_observation_reducers_proto_enumTypes[0].Descriptor()
}

func (EventObservationState) Type() protoreflect.EnumType {
	return &file_observation_reducers_proto_enumTypes[0]
}

func (x EventObservationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventObservationState.Descriptor instead.
func (EventObservationState) EnumDescriptor() ([]byte, []int) {
	return file_observation_reducers_proto_rawDescGZIP(), []int{0}
}

type ObservationState int32

const (
	ObservationState_OBSERVATION_STATE_None ObservationState = 0
	ObservationState_Success                ObservationState = 1
	ObservationState_Failed                 ObservationState = 2
)

// Enum value maps for ObservationState.
var (
	ObservationState_name = map[int32]string{
		0: "OBSERVATION_STATE_None",
		1: "Success",
		2: "Failed",
	}
	ObservationState_value = map[string]int32{
		"OBSERVATION_STATE_None": 0,
		"Success":                1,
		"Failed":                 2,
	}
)

func (x ObservationState) Enum() *ObservationState {
	p := new(ObservationState)
	*p = x
	return p
}

func (x ObservationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObservationState) Descriptor() protoreflect.EnumDescriptor {
	return file_observation_reducers_proto_enumTypes[1].Descriptor()
}

func (ObservationState) Type() protoreflect.EnumType {
	return &file_observation_reducers_proto_enumTypes[1]
}

func (x ObservationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObservationState.Descriptor instead.
func (ObservationState) EnumDescriptor() ([]byte, []int) {
	return file_observation_reducers_proto_rawDescGZIP(), []int{1}
}

type ReplayState int32

const (
	ReplayState_REPLAY_STATE_None    ReplayState = 0
	ReplayState_BeginReplay          ReplayState = 1
	ReplayState_EndReplay            ReplayState = 2
	ReplayState_BeginReplayPartition ReplayState = 3
	ReplayState_EndReplayPartition   ReplayState = 4
)

// Enum value maps for ReplayState.
var (
	ReplayState_name = map[int32]string{
		0: "REPLAY_STATE_None",
		1: "BeginReplay",
		2: "EndReplay",
		3: "BeginReplayPartition",
		4: "EndReplayPartition",
	}
	ReplayState_value = map[string]int32{
		"REPLAY_STATE_None":    0,
		"BeginReplay":          1,
		"EndReplay":            2,
		"BeginReplayPartition": 3,
		"EndReplayPartition":   4,
	}
)

func (x ReplayState) Enum() *ReplayState {
	p := new(ReplayState)
	*p = x
	return p
}

func (x ReplayState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReplayState) Descriptor() protoreflect.EnumDescriptor {
	return file_observation_reducers_proto_enumTypes[2].Descriptor()
}

func (ReplayState) Type() protoreflect.EnumType {
	return &file_observation_reducers_proto_enumTypes[2]
}

func (x ReplayState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReplayState.Descriptor instead.
func (ReplayState) EnumDescriptor() ([]byte, []int) {
	return file_observation_reducers_proto_rawDescGZIP(), []int{2}
}

type AppendedEvent struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Context             *EventContext          `protobuf:"bytes,1,opt,name=Context,proto3" json:"Context,omitempty"`
	Content             string                 `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	OriginalContent     string                 `protobuf:"bytes,3,opt,name=OriginalContent,proto3" json:"OriginalContent,omitempty"`
	Revisions           []*EventRevision       `protobuf:"bytes,4,rep,name=Revisions,proto3" json:"Revisions,omitempty"`
	GenerationalContent map[int32]string       `protobuf:"bytes,5,rep,name=GenerationalContent,proto3" json:"GenerationalContent,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AppendedEvent) Reset() {
	*x = AppendedEvent{}
	mi := &file_observation_reducers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendedEvent) ProtoMessage() {}

func (x *AppendedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_observation_reducers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendedEvent.ProtoReflect.Descriptor instead.
func (*AppendedEvent) Descriptor() ([]byte, []int) {
	return file_observation_reducers_proto_rawDescGZIP(), []int{0}
}

func (x *AppendedEvent) GetContext() *EventContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *AppendedEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AppendedEvent) GetOriginalContent() string {
	if x != nil {
		return x.OriginalContent
	}
	return ""
}

func (x *AppendedEvent) GetRevisions() []*EventRevision {
	if x != nil {
		return x.Revisions
	}
	return nil
}

func (x *AppendedEvent) GetGenerationalContent() map[int32]string {
	if x != nil {
		return x.GenerationalContent
	}
	return nil
}

type Causation struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Occurred      *SerializableDateTimeOffset `protobuf:"bytes,1,opt,name=Occurred,proto3" json:"Occurred,omitempty"`
	Type          string                      `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Properties    map[string]string           `protobuf:"bytes,3,rep,name=Properties,proto3" json:"Properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Causation) Reset() {
	*x = Causation{}
	mi := &file_observation_reducers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Causation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Causation) ProtoMessage() {}

func (x *Causation) ProtoReflect() protoreflect.Message {
	mi := &file_observation_reducers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Causation.ProtoReflect.Descriptor instead.
func (*Causation) Descriptor() ([]byte, []int) {
	return file_observation_reducers_proto_rawDescGZIP(), []int{1}
}

func (x *Causation) GetOccurred() *SerializableDateTimeOffset {
	if x != nil {
		return x.Occurred
	}
	return nil
}

func (x *Causation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Causation) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type EventContext struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	EventType        *EventType                  `protobuf:"bytes,1,opt,name=EventType,proto3" json:"EventType,omitempty"`
	EventSourceType  string                      `protobuf:"bytes,2,opt,name=EventSourceType,proto3" json:"EventSourceType,omitempty"`
	EventSourceId    string                      `protobuf:"bytes,3,opt,name=EventSourceId,proto3" json:"EventSourceId,omitempty"`
	SequenceNumber   uint64                      `protobuf:"varint,4,opt,name=SequenceNumber,proto3" json:"SequenceNumber,omitempty"`
	EventStreamType  string                      `protobuf:"bytes,5,opt,name=EventStreamType,proto3" json:"EventStreamType,omitempty"`
	EventStreamId    string                      `protobuf:"bytes,6,opt,name=EventStreamId,proto3" json:"EventStreamId,omitempty"`
	Occurred         *SerializableDateTimeOffset `protobuf:"bytes,7,opt,name=Occurred,proto3" json:"Occurred,omitempty"`
	EventStore       string                      `protobuf:"bytes,8,opt,name=EventStore,proto3" json:"EventStore,omitempty"`
	Namespace        string                      `protobuf:"bytes,9,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	CorrelationId    *bcl.Guid                   `protobuf:"bytes,10,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"` // default value could not be applied: 00000000-0000-0000-0000-000000000000
	Causation        []*Causation                `protobuf:"bytes,11,rep,name=Causation,proto3" json:"Causation,omitempty"`
	CausedBy         *Identity                   `protobuf:"bytes,12,opt,name=CausedBy,proto3" json:"CausedBy,omitempty"`
	ObservationState EventObservationState       `protobuf:"varint,13,opt,name=ObservationState,proto3,enum=Cratis.Chronicle.Contracts.Observation.Reducers.EventObservationState" json:"ObservationState,omitempty"`
	Tags             []string                    `protobuf:"bytes,14,rep,name=Tags,proto3" json:"Tags,omitempty"`
	Hash             string                      `protobuf:"bytes,15,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Subject          string                      `protobuf:"bytes,16,opt,name=Subject,proto3" json:"Subject,omitempty"`
	NamedTags        []*NamedTag                 `protobuf:"bytes,17,rep,name=NamedTags,proto3" json:"NamedTags,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventContext) Reset() {
	*x = EventContext{}
	mi := &file_observation_reducers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventContext) ProtoMessage() {}

func (x *EventContext) ProtoReflect() protoreflect.Message {
	mi := &file_observation_reducers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventContext.ProtoReflect.Descriptor instead.
func (*EventContext) Descriptor() ([]byte, []int) {
	return file_observation_reducers_proto_rawDescGZIP(), []int{2}
}

func (x *EventContext) GetEventType() *EventType {
	if x != nil {
		return x.EventType
	}
	return nil
}

func (x *EventContext) GetEventSourceType() string {
	if x != nil {
		return x.EventSourceType
	}
	return ""
}

func (x *EventContext) GetEventSourceId() string {
	if x != nil {
		return x.EventSourceId
	}
	return ""
}

func (x *EventContext) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *EventContext) GetEventStreamType() string {
	if x != nil {
		return x.EventStreamType
	}
	return ""
}

func (x *EventContext) GetEventStreamId() string {
	if x != nil {
		return x.EventStreamId
	}
	return ""
}

func (x *EventContext) GetOccurred() *SerializableDateTimeOffset {
	if x != nil {
		return x.Occurred
	}
	return nil
}

func (x *EventContext) GetEventStore() string {
	if x != nil {
		return x.EventStore
	}
	return ""
}

func (x *EventContext) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *EventContext) GetCorrelationId() *bcl.Guid {
	if x != nil {
		return x.CorrelationId
	}
	return nil
}

func (x *EventContext) GetCausation() []*Causation {
	if x != nil {
		return x.Causation
	}
	return nil
}

func (x *EventContext) GetCausedBy() *Identity {
	if x != nil {
		return x.CausedBy
	}
	return nil
}

func (x *EventContext) GetObservationState() EventObservationState {
	if x != nil {
		return x.ObservationState
	}
	return EventObservationState_EVENT_OBSERVATION_STATE_None
}

func (x *EventContext) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *EventContext) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *EventContext) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EventContext) GetNamedTags() []*NamedTag {
	if x != nil {
		return x.NamedTags
	}
	return nil
}

type EventRevision struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Generation    uint32                      `protobuf:"varint,1,opt,name=Generation,proto3" json:"Generation,omitempty"`
	CorrelationId string                      `protobuf:"bytes,2,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	CausedBy      *Identity                   `protobuf:"bytes,3,opt,name=CausedBy,proto3" json:"CausedBy,omitempty"`
	Occurred      *SerializableDateTimeOffset `protobuf:"bytes,4,opt,name=Occurred,proto3" json:"Occurred,omitempty"`
	Content       string                      `protobuf:"bytes,5,opt,name=Content,proto3" json:"Content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRevision) Reset() {
	*x = EventRevision{}
	mi := &file_observation_reducers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRevision) ProtoMessage() {}

func (x *EventRevision) ProtoReflect() protoreflect.Message {
	mi := &file_observation_reducers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRevision.ProtoReflect.Descriptor instead.
func (*EventRevision) Descriptor() ([]byte, []int) {
	return file_observation_reducers_proto_rawDescGZIP(), []int{3}
}

func (x *EventRevision) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *EventRevision) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *EventRevision) GetCausedBy() *Identity {
	if x != nil {
		return x.CausedBy
	}
	return nil
}

func (x *EventRevision) GetOccurred() *SerializableDateTimeOffset {
	if x != nil {
		return x.Occurred
	}
	return nil
}

func (x *EventRevision) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type EventType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Generation    uint32                 `protobuf:"varint,2,opt,name=Generation,proto3" json:"Generation,omitempty"`
	Tombstone     bool                   `protobuf:"varint,3,opt,name=Tombstone,proto3" json:"Tombstone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventType) Reset() {
	*x = EventType{}
	mi := &file_observation_reducers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventType) ProtoMessage() {}

func (x *EventType) ProtoReflect() protoreflect.Message {
	mi := &file_observation_reducers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventType.ProtoReflect.Descriptor instead.
func (*EventType) Descriptor() ([]byte, []int) {
	return file_observation_reducers_proto_rawDescGZIP(), []int{4}
}

func (x *EventType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventType) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *EventType) GetTombstone() bool {
	if x != nil {
		return x.Tombstone
	}
	return false
}

type EventTypeWithKeyExpression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     *EventType             `protobuf:"bytes,1,opt,name=EventType,proto3" json:"EventType,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventTypeWithKeyExpression) Reset() {
	*x = EventTypeWithKeyExpression{}
	mi := &file_observation_reducers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventTypeWithKeyExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTypeWithKeyExpression) ProtoMessage() {}

func (x *EventTypeWithKeyExpression) ProtoReflect() protoreflect.Message {
	mi := &file_observation_reducers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTypeWithKeyExpression.ProtoReflect.Descriptor instead.
func (*EventTypeWithKeyExpression) Descriptor() ([]byte, []int) {
	return file_observation_reducers_proto_rawDescGZIP(), []int{5}
}

func (x *EventTypeWithKeyExpression) GetEventType() *EventType {
	if x != nil {
		return x.EventType
	}
	return nil
}

func (x *EventTypeWithKeyExpression) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=Subject,proto3" json:"Subject,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=UserName,proto3" json:"UserName,omitempty"`
	OnBehalfOf    *Identity              `protobuf:"bytes,4,opt,name=OnBehalfOf,proto3" json:"OnBehalfOf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_observation_reducers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_observation_reducers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_observation_reducers_proto_rawDescGZIP(), []int{6}
}

func (x *Identity) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Identity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Identity) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Identity) GetOnBehalfOf() *Identity {
	if x != nil {
		return x.OnBehalfOf
	}
	return nil
}

type NamedTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamedTag) Reset() {
	*x = NamedTag{}
	mi := &file_observation_reducers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedTag) ProtoMessage() {}

func (x *NamedTag) ProtoReflect() protoreflect.Message {
	mi := &file_observation_reducers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedTag.ProtoReflect.Descriptor instead.
func (*NamedTag) Descriptor() ([]byte, []int) {
	return file_observation_reducers_proto_rawDescGZIP(), []int{7}
}

func (x *NamedTag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NamedTag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ObserverFilters struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FilterTags      []string               `protobuf:"bytes,1,rep,name=FilterTags,proto3" json:"FilterTags,omitempty"`
	EventSourceType string                 `protobuf:"bytes,2,opt,name=EventSourceType,proto3" json:"EventSourceType,omitempty"`
	EventStreamType string                 `protobuf:"bytes,3,opt,name=EventStreamType,proto3" json:"EventStreamType,omitempty"` // default value could not be applied: All
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ObserverFilters) Reset() {
	*x = ObserverFilters{}
	mi := &file_observation_reducers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserverFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserverFilters) ProtoMessage() {}

func (x *ObserverFilters) ProtoReflect() protoreflect.Message {
	mi := &file_observation_reducers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserverFilters.ProtoReflect.Descriptor instead.
func (*ObserverFilters) Descriptor() ([]byte, []int) {
	return file_observation_reducers_proto_rawDescGZIP(), []int{8}
}

func (x *ObserverFilters) GetFilterTags() []string {
	if x != nil {
		return x.FilterTags
	}
	return nil
}

func (x *ObserverFilters) GetEventSourceType() string {
	if x != nil {
		return x.EventSourceType
	}
	return ""
}

func (x *ObserverFilters) GetEventStreamType() string {
	if x != nil {
		return x.EventStreamType
	}
	return ""
}

type OneOf_RegisterReducer_ReducerResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value0        *RegisterReducer       `protobuf:"bytes,1,opt,name=Value0,proto3" json:"Value0,omitempty"`
	Value1        *ReducerResult         `protobuf:"bytes,2,opt,name=Value1,proto3" json:"Value1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneOf_RegisterReducer_ReducerResult) Reset() {
	*x = OneOf_RegisterReducer_ReducerResult{}
	mi := &file_observation_reducers_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneOf_RegisterReducer_ReducerResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOf_RegisterReducer_ReducerResult) ProtoMessage() {}

func (x *OneOf_RegisterReducer_ReducerResult) ProtoReflect() protoreflect.Message {
	mi := &file_observation_reducers_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOf_RegisterReducer_ReducerResult.ProtoReflect.Descriptor instead.
func (*OneOf_RegisterReducer_ReducerResult) Descriptor() ([]byte, []int) {
	return file_observation_reducers_proto_rawDescGZIP(), []int{9}
}

func (x *OneOf_RegisterReducer_ReducerResult) GetValue0() *RegisterReducer {
	if x != nil {
		return x.Value0
	}
	return nil
}

func (x *OneOf_RegisterReducer_ReducerResult) GetValue1() *ReducerResult {
	if x != nil {
		return x.Value1
	}
	return nil
}

type ReduceOperationMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     string                 `protobuf:"bytes,1,opt,name=Partition,proto3" json:"Partition,omitempty"`
	InitialState  string                 `protobuf:"bytes,2,opt,name=InitialState,proto3" json:"InitialState,omitempty"`
	Events        []*AppendedEvent       `protobuf:"bytes,3,rep,name=Events,proto3" json:"Events,omitempty"`
	ReplayState   ReplayState            `protobuf:"varint,4,opt,name=ReplayState,proto3,enum=Cratis.Chronicle.Contracts.Observation.Reducers.ReplayState" json:"ReplayState,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReduceOperationMessage) Reset() {
	*x = ReduceOperationMessage{}
	mi := &file_observation_reducers_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReduceOperationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceOperationMessage) ProtoMessage() {}

func (x *ReduceOperationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_observation_reducers_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceOperationMessage.ProtoReflect.Descriptor instead.
func (*ReduceOperationMessage) Descriptor() ([]byte, []int) {
	return file_observation_reducers_proto_rawDescGZIP(), []int{10}
}

func (x *ReduceOperationMessage) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *ReduceOperationMessage) GetInitialState() string {
	if x != nil {
		return x.InitialState
	}
	return ""
}

func (x *ReduceOperationMessage) GetEvents() []*AppendedEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ReduceOperationMessage) GetReplayState() ReplayState {
	if x != nil {
		return x.ReplayState
	}
	return ReplayState_REPLAY_STATE_None
}

type ReducerDefinition struct {
	state           protoimpl.MessageState        `protogen:"open.v1"`
	ReducerId       string                        `protobuf:"bytes,1,opt,name=ReducerId,proto3" json:"ReducerId,omitempty"`
	EventSequenceId string                        `protobuf:"bytes,2,opt,name=EventSequenceId,proto3" json:"EventSequenceId,omitempty"`
	EventTypes      []*EventTypeWithKeyExpression `protobuf:"bytes,3,rep,name=EventTypes,proto3" json:"EventTypes,omitempty"`
	ReadModel       string                        `protobuf:"bytes,4,opt,name=ReadModel,proto3" json:"ReadModel,omitempty"`
	IsActive        bool                          `protobuf:"varint,5,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	Tags            []string                      `protobuf:"bytes,7,rep,name=Tags,proto3" json:"Tags,omitempty"`
	Filters         *ObserverFilters              `protobuf:"bytes,8,opt,name=Filters,proto3" json:"Filters,omitempty"`
	Hash            string                        `protobuf:"bytes,9,opt,name=Hash,proto3" json:"Hash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReducerDefinition) Reset() {
	*x = ReducerDefinition{}
	mi := &file_observation_reducers_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReducerDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReducerDefinition) ProtoMessage() {}

func (x *ReducerDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_observation_reducers_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReducerDefinition.ProtoReflect.Descriptor instead.
func (*ReducerDefinition) Descriptor() ([]byte, []int) {
	return file_observation_reducers_proto_rawDescGZIP(), []int{11}
}

func (x *ReducerDefinition) GetReducerId() string {
	if x != nil {
		return x.ReducerId
	}
	return ""
}

func (x *ReducerDefinition) GetEventSequenceId() string {
	if x != nil {
		return x.EventSequenceId
	}
	return ""
}

func (x *ReducerDefinition) GetEventTypes() []*EventTypeWithKeyExpression {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *ReducerDefinition) GetReadModel() string {
	if x != nil {
		return x.ReadModel
	}
	return ""
}

func (x *ReducerDefinition) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ReducerDefinition) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ReducerDefinition) GetFilters() *ObserverFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ReducerDefinition) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type ReducerMessage struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Content       *OneOf_RegisterReducer_ReducerResult `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReducerMessage) Reset() {
	*x = ReducerMessage{}
	mi := &file_observation_reducers_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReducerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReducerMessage) ProtoMessage() {}

func (x *ReducerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_observation_reducers_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReducerMessage.ProtoReflect.Descriptor instead.
func (*ReducerMessage) Descriptor() ([]byte, []int) {
	return file_observation_reducers_proto_rawDescGZIP(), []int{12}
}

func (x *ReducerMessage) GetContent() *OneOf_RegisterReducer_ReducerResult {
	if x != nil {
		return x.Content
	}
	return nil
}

type ReducerResult struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Partition                 string                 `protobuf:"bytes,1,opt,name=Partition,proto3" json:"Partition,omitempty"`
	State                     ObservationState       `protobuf:"varint,2,opt,name=State,proto3,enum=Cratis.Chronicle.Contracts.Observation.Reducers.ObservationState" json:"State,omitempty"`
	LastSuccessfulObservation uint64                 `protobuf:"varint,3,opt,name=LastSuccessfulObservation,proto3" json:"LastSuccessfulObservation,omitempty"`
	ExceptionMessages         []string               `protobuf:"bytes,4,rep,name=ExceptionMessages,proto3" json:"ExceptionMessages,omitempty"`
	ExceptionStackTrace       string                 `protobuf:"bytes,5,opt,name=ExceptionStackTrace,proto3" json:"ExceptionStackTrace,omitempty"`
	ReadModelState            string                 `protobuf:"bytes,6,opt,name=ReadModelState,proto3" json:"ReadModelState,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ReducerResult) Reset() {
	*x = ReducerResult{}
	mi := &file_observation_reducers_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReducerResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReducerResult) ProtoMessage() {}

func (x *ReducerResult) ProtoReflect() protoreflect.Message {
	mi := &file_observation_reducers_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReducerResult.ProtoReflect.Descriptor instead.
func (*ReducerResult) Descriptor() ([]byte, []int) {
	return file_observation_reducers_proto_rawDescGZIP(), []int{13}
}

func (x *ReducerResult) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *ReducerResult) GetState() ObservationState {
	if x != nil {
		return x.State
	}
	return ObservationState_OBSERVATION_STATE_None
}

func (x *ReducerResult) GetLastSuccessfulObservation() uint64 {
	if x != nil {
		return x.LastSuccessfulObservation
	}
	return 0
}

func (x *ReducerResult) GetExceptionMessages() []string {
	if x != nil {
		return x.ExceptionMessages
	}
	return nil
}

func (x *ReducerResult) GetExceptionStackTrace() string {
	if x != nil {
		return x.ExceptionStackTrace
	}
	return ""
}

func (x *ReducerResult) GetReadModelState() string {
	if x != nil {
		return x.ReadModelState
	}
	return ""
}

type RegisterReducer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=ConnectionId,proto3" json:"ConnectionId,omitempty"`
	EventStore    string                 `protobuf:"bytes,2,opt,name=EventStore,proto3" json:"EventStore,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	Reducer       *ReducerDefinition     `protobuf:"bytes,4,opt,name=Reducer,proto3" json:"Reducer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReducer) Reset() {
	*x = RegisterReducer{}
	mi := &file_observation_reducers_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReducer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReducer) ProtoMessage() {}

func (x *RegisterReducer) ProtoReflect() protoreflect.Message {
	mi := &file_observation_reducers_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReducer.ProtoReflect.Descriptor instead.
func (*RegisterReducer) Descriptor() ([]byte, []int) {
	return file_observation_reducers_proto_rawDescGZIP(), []int{14}
}

func (x *RegisterReducer) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *RegisterReducer) GetEventStore() string {
	if x != nil {
		return x.EventStore
	}
	return ""
}

func (x *RegisterReducer) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RegisterReducer) GetReducer() *ReducerDefinition {
	if x != nil {
		return x.Reducer
	}
	return nil
}

// Represents a DateTimeOffset value as an ISO 8601 string (e.g., "2024-01-15T12:30:00.0000000+02:00").
type SerializableDateTimeOffset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerializableDateTimeOffset) Reset() {
	*x = SerializableDateTimeOffset{}
	mi := &file_observation_reducers_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializableDateTimeOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializableDateTimeOffset) ProtoMessage() {}

func (x *SerializableDateTimeOffset) ProtoReflect() protoreflect.Message {
	mi := &file_observation_reducers_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializableDateTimeOffset.ProtoReflect.Descriptor instead.
func (*SerializableDateTimeOffset) Descriptor() ([]byte, []int) {
	return file_observation_reducers_proto_rawDescGZIP(), []int{15}
}

func (x *SerializableDateTimeOffset) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_observation_reducers_proto protoreflect.FileDescriptor

const file_observation_reducers_proto_rawDesc = "" +
	"\n" +
	"\x1aobservation_reducers.proto\x12/Cratis.Chronicle.Contracts.Observation.Reducers\x1a\x16protobuf-net/bcl.proto\"\xde\x03\n" +
	"\rAppendedEvent\x12W\n" +
	"\aContext\x18\x01 \x01(\v2=.Cratis.Chronicle.Contracts.Observation.Reducers.EventContextR\aContext\x12\x18\n" +
	"\aContent\x18\x02 \x01(\tR\aContent\x12(\n" +
	"\x0fOriginalContent\x18\x03 \x01(\tR\x0fOriginalContent\x12\\\n" +
	"\tRevisions\x18\x04 \x03(\v2>.Cratis.Chronicle.Contracts.Observation.Reducers.EventRevisionR\tRevisions\x12\x89\x01\n" +
	"\x13GenerationalContent\x18\x05 \x03(\v2W.Cratis.Chronicle.Contracts.Observation.Reducers.AppendedEvent.GenerationalContentEntryR\x13GenerationalContent\x1aF\n" +
	"\x18GenerationalContentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x02\n" +
	"\tCausation\x12g\n" +
	"\bOccurred\x18\x01 \x01(\v2K.Cratis.Chronicle.Contracts.Observation.Reducers.SerializableDateTimeOffsetR\bOccurred\x12\x12\n" +
	"\x04Type\x18\x02 \x01(\tR\x04Type\x12j\n" +
	"\n" +
	"Properties\x18\x03 \x03(\v2J.Cratis.Chronicle.Contracts.Observation.Reducers.Causation.PropertiesEntryR\n" +
	"Properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc8\a\n" +
	"\fEventContext\x12X\n" +
	"\tEventType\x18\x01 \x01(\v2:.Cratis.Chronicle.Contracts.Observation.Reducers.EventTypeR\tEventType\x12(\n" +
	"\x0fEventSourceType\x18\x02 \x01(\tR\x0fEventSourceType\x12$\n" +
	"\rEventSourceId\x18\x03 \x01(\tR\rEventSourceId\x12&\n" +
	"\x0eSequenceNumber\x18\x04 \x01(\x04R\x0eSequenceNumber\x12(\n" +
	"\x0fEventStreamType\x18\x05 \x01(\tR\x0fEventStreamType\x12$\n" +
	"\rEventStreamId\x18\x06 \x01(\tR\rEventStreamId\x12g\n" +
	"\bOccurred\x18\a \x01(\v2K.Cratis.Chronicle.Contracts.Observation.Reducers.SerializableDateTimeOffsetR\bOccurred\x12\x1e\n" +
	"\n" +
	"EventStore\x18\b \x01(\tR\n" +
	"EventStore\x12\x1c\n" +
	"\tNamespace\x18\t \x01(\tR\tNamespace\x12/\n" +
	"\rCorrelationId\x18\n" +
	" \x01(\v2\t.bcl.GuidR\rCorrelationId\x12X\n" +
	"\tCausation\x18\v \x03(\v2:.Cratis.Chronicle.Contracts.Observation.Reducers.CausationR\tCausation\x12U\n" +
	"\bCausedBy\x18\f \x01(\v29.Cratis.Chronicle.Contracts.Observation.Reducers.IdentityR\bCausedBy\x12r\n" +
	"\x10ObservationState\x18\r \x01(\x0e2F.Cratis.Chronicle.Contracts.Observation.Reducers.EventObservationStateR\x10ObservationState\x12\x12\n" +
	"\x04Tags\x18\x0e \x03(\tR\x04Tags\x12\x12\n" +
	"\x04Hash\x18\x0f \x01(\tR\x04Hash\x12\x18\n" +
	"\aSubject\x18\x10 \x01(\tR\aSubject\x12W\n" +
	"\tNamedTags\x18\x11 \x03(\v29.Cratis.Chronicle.Contracts.Observation.Reducers.NamedTagR\tNamedTags\"\xaf\x02\n" +
	"\rEventRevision\x12\x1e\n" +
	"\n" +
	"Generation\x18\x01 \x01(\rR\n" +
	"Generation\x12$\n" +
	"\rCorrelationId\x18\x02 \x01(\tR\rCorrelationId\x12U\n" +
	"\bCausedBy\x18\x03 \x01(\v29.Cratis.Chronicle.Contracts.Observation.Reducers.IdentityR\bCausedBy\x12g\n" +
	"\bOccurred\x18\x04 \x01(\v2K.Cratis.Chronicle.Contracts.Observation.Reducers.SerializableDateTimeOffsetR\bOccurred\x12\x18\n" +
	"\aContent\x18\x05 \x01(\tR\aContent\"Y\n" +
	"\tEventType\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x1e\n" +
	"\n" +
	"Generation\x18\x02 \x01(\rR\n" +
	"Generation\x12\x1c\n" +
	"\tTombstone\x18\x03 \x01(\bR\tTombstone\"\x88\x01\n" +
	"\x1aEventTypeWithKeyExpression\x12X\n" +
	"\tEventType\x18\x01 \x01(\v2:.Cratis.Chronicle.Contracts.Observation.Reducers.EventTypeR\tEventType\x12\x10\n" +
	"\x03Key\x18\x02 \x01(\tR\x03Key\"\xaf\x01\n" +
	"\bIdentity\x12\x18\n" +
	"\aSubject\x18\x01 \x01(\tR\aSubject\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1a\n" +
	"\bUserName\x18\x03 \x01(\tR\bUserName\x12Y\n" +
	"\n" +
	"OnBehalfOf\x18\x04 \x01(\v29.Cratis.Chronicle.Contracts.Observation.Reducers.IdentityR\n" +
	"OnBehalfOf\"4\n" +
	"\bNamedTag\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\tR\x05Value\"\x85\x01\n" +
	"\x0fObserverFilters\x12\x1e\n" +
	"\n" +
	"FilterTags\x18\x01 \x03(\tR\n" +
	"FilterTags\x12(\n" +
	"\x0fEventSourceType\x18\x02 \x01(\tR\x0fEventSourceType\x12(\n" +
	"\x0fEventStreamType\x18\x03 \x01(\tR\x0fEventStreamType\"\xd7\x01\n" +
	"#OneOf_RegisterReducer_ReducerResult\x12X\n" +
	"\x06Value0\x18\x01 \x01(\v2@.Cratis.Chronicle.Contracts.Observation.Reducers.RegisterReducerR\x06Value0\x12V\n" +
	"\x06Value1\x18\x02 \x01(\v2>.Cratis.Chronicle.Contracts.Observation.Reducers.ReducerResultR\x06Value1\"\x92\x02\n" +
	"\x16ReduceOperationMessage\x12\x1c\n" +
	"\tPartition\x18\x01 \x01(\tR\tPartition\x12\"\n" +
	"\fInitialState\x18\x02 \x01(\tR\fInitialState\x12V\n" +
	"\x06Events\x18\x03 \x03(\v2>.Cratis.Chronicle.Contracts.Observation.Reducers.AppendedEventR\x06Events\x12^\n" +
	"\vReplayState\x18\x04 \x01(\x0e2<.Cratis.Chronicle.Contracts.Observation.Reducers.ReplayStateR\vReplayState\"\x86\x03\n" +
	"\x11ReducerDefinition\x12\x1c\n" +
	"\tReducerId\x18\x01 \x01(\tR\tReducerId\x12(\n" +
	"\x0fEventSequenceId\x18\x02 \x01(\tR\x0fEventSequenceId\x12k\n" +
	"\n" +
	"EventTypes\x18\x03 \x03(\v2K.Cratis.Chronicle.Contracts.Observation.Reducers.EventTypeWithKeyExpressionR\n" +
	"EventTypes\x12\x1c\n" +
	"\tReadModel\x18\x04 \x01(\tR\tReadModel\x12\x1a\n" +
	"\bIsActive\x18\x05 \x01(\bR\bIsActive\x12\x12\n" +
	"\x04Tags\x18\a \x03(\tR\x04Tags\x12Z\n" +
	"\aFilters\x18\b \x01(\v2@.Cratis.Chronicle.Contracts.Observation.Reducers.ObserverFiltersR\aFilters\x12\x12\n" +
	"\x04Hash\x18\t \x01(\tR\x04Hash\"\x80\x01\n" +
	"\x0eReducerMessage\x12n\n" +
	"\aContent\x18\x01 \x01(\v2T.Cratis.Chronicle.Contracts.Observation.Reducers.OneOf_RegisterReducer_ReducerResultR\aContent\"\xcc\x02\n" +
	"\rReducerResult\x12\x1c\n" +
	"\tPartition\x18\x01 \x01(\tR\tPartition\x12W\n" +
	"\x05State\x18\x02 \x01(\x0e2A.Cratis.Chronicle.Contracts.Observation.Reducers.ObservationStateR\x05State\x12<\n" +
	"\x19LastSuccessfulObservation\x18\x03 \x01(\x04R\x19LastSuccessfulObservation\x12,\n" +
	"\x11ExceptionMessages\x18\x04 \x03(\tR\x11ExceptionMessages\x120\n" +
	"\x13ExceptionStackTrace\x18\x05 \x01(\tR\x13ExceptionStackTrace\x12&\n" +
	"\x0eReadModelState\x18\x06 \x01(\tR\x0eReadModelState\"\xd1\x01\n" +
	"\x0fRegisterReducer\x12\"\n" +
	"\fConnectionId\x18\x01 \x01(\tR\fConnectionId\x12\x1e\n" +
	"\n" +
	"EventStore\x18\x02 \x01(\tR\n" +
	"EventStore\x12\x1c\n" +
	"\tNamespace\x18\x03 \x01(\tR\tNamespace\x12\\\n" +
	"\aReducer\x18\x04 \x01(\v2B.Cratis.Chronicle.Contracts.Observation.Reducers.ReducerDefinitionR\aReducer\"2\n" +
	"\x1aSerializableDateTimeOffset\x12\x14\n" +
	"\x05Value\x18\x01 \x01(\tR\x05Value*R\n" +
	"\x15EventObservationState\x12 \n" +
	"\x1cEVENT_OBSERVATION_STATE_None\x10\x00\x12\v\n" +
	"\aInitial\x10\x01\x12\n" +
	"\n" +
	"\x06Replay\x10\x02*G\n" +
	"\x10ObservationState\x12\x1a\n" +
	"\x16OBSERVATION_STATE_None\x10\x00\x12\v\n" +
	"\aSuccess\x10\x01\x12\n" +
	"\n" +
	"\x06Failed\x10\x02*v\n" +
	"\vReplayState\x12\x15\n" +
	"\x11REPLAY_STATE_None\x10\x00\x12\x0f\n" +
	"\vBeginReplay\x10\x01\x12\r\n" +
	"\tEndReplay\x10\x02\x12\x18\n" +
	"\x14BeginReplayPartition\x10\x03\x12\x16\n" +
	"\x12EndReplayPartition\x10\x042\xa4\x01\n" +
	"\bReducers\x12\x97\x01\n" +
	"\aObserve\x12?.Cratis.Chronicle.Contracts.Observation.Reducers.ReducerMessage\x1aG.Cratis.Chronicle.Contracts.Observation.Reducers.ReduceOperationMessage(\x010\x01B\xf0\x02\n" +
	"3com.Cratis.Chronicle.Contracts.Observation.ReducersB\x18ObservationReducersProtoP\x01Z=github.com/cratis/chronicle.go/contracts/observation/reducers\xa2\x02\x05CCCOR\xaa\x02/Cratis.Chronicle.Contracts.Observation.Reducers\xca\x02/Cratis\\Chronicle\\Contracts\\Observation\\Reducers\xe2\x02;Cratis\\Chronicle\\Contracts\\Observation\\Reducers\\GPBMetadata\xea\x023Cratis::Chronicle::Contracts::Observation::Reducersb\x06proto3"

var (
	file_observation_reducers_proto_rawDescOnce sync.Once
	file_observation_reducers_proto_rawDescData []byte
)

func file_observation_reducers_proto_rawDescGZIP() []byte {
	file_observation_reducers_proto_rawDescOnce.Do(func() {
		file_observation_reducers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_observation_reducers_proto_rawDesc), len(file_observation_reducers_proto_rawDesc)))
	})
	return file_observation_reducers_proto_rawDescData
}

var file_observation_reducers_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_observation_reducers_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_observation_reducers_proto_goTypes = []any{
	(EventObservationState)(0),                  // 0: Cratis.Chronicle.Contracts.Observation.Reducers.EventObservationState
	(ObservationState)(0),                       // 1: Cratis.Chronicle.Contracts.Observation.Reducers.ObservationState
	(ReplayState)(0),                            // 2: Cratis.Chronicle.Contracts.Observation.Reducers.ReplayState
	(*AppendedEvent)(nil),                       // 3: Cratis.Chronicle.Contracts.Observation.Reducers.AppendedEvent
	(*Causation)(nil),                           // 4: Cratis.Chronicle.Contracts.Observation.Reducers.Causation
	(*EventContext)(nil),                        // 5: Cratis.Chronicle.Contracts.Observation.Reducers.EventContext
	(*EventRevision)(nil),                       // 6: Cratis.Chronicle.Contracts.Observation.Reducers.EventRevision
	(*EventType)(nil),                           // 7: Cratis.Chronicle.Contracts.Observation.Reducers.EventType
	(*EventTypeWithKeyExpression)(nil),          // 8: Cratis.Chronicle.Contracts.Observation.Reducers.EventTypeWithKeyExpression
	(*Identity)(nil),                            // 9: Cratis.Chronicle.Contracts.Observation.Reducers.Identity
	(*NamedTag)(nil),                            // 10: Cratis.Chronicle.Contracts.Observation.Reducers.NamedTag
	(*ObserverFilters)(nil),                     // 11: Cratis.Chronicle.Contracts.Observation.Reducers.ObserverFilters
	(*OneOf_RegisterReducer_ReducerResult)(nil), // 12: Cratis.Chronicle.Contracts.Observation.Reducers.OneOf_RegisterReducer_ReducerResult
	(*ReduceOperationMessage)(nil),              // 13: Cratis.Chronicle.Contracts.Observation.Reducers.ReduceOperationMessage
	(*ReducerDefinition)(nil),                   // 14: Cratis.Chronicle.Contracts.Observation.Reducers.ReducerDefinition
	(*ReducerMessage)(nil),                      // 15: Cratis.Chronicle.Contracts.Observation.Reducers.ReducerMessage
	(*ReducerResult)(nil),                       // 16: Cratis.Chronicle.Contracts.Observation.Reducers.ReducerResult
	(*RegisterReducer)(nil),                     // 17: Cratis.Chronicle.Contracts.Observation.Reducers.RegisterReducer
	(*SerializableDateTimeOffset)(nil),          // 18: Cratis.Chronicle.Contracts.Observation.Reducers.SerializableDateTimeOffset
	nil,                                         // 19: Cratis.Chronicle.Contracts.Observation.Reducers.AppendedEvent.GenerationalContentEntry
	nil,                                         // 20: Cratis.Chronicle.Contracts.Observation.Reducers.Causation.PropertiesEntry
	(*bcl.Guid)(nil),                            // 21: bcl.Guid
}
var file_observation_reducers_proto_depIdxs = []int32{
	5,  // 0: Cratis.Chronicle.Contracts.Observation.Reducers.AppendedEvent.Context:type_name -> Cratis.Chronicle.Contracts.Observation.Reducers.EventContext
	6,  // 1: Cratis.Chronicle.Contracts.Observation.Reducers.AppendedEvent.Revisions:type_name -> Cratis.Chronicle.Contracts.Observation.Reducers.EventRevision
	19, // 2: Cratis.Chronicle.Contracts.Observation.Reducers.AppendedEvent.GenerationalContent:type_name -> Cratis.Chronicle.Contracts.Observation.Reducers.AppendedEvent.GenerationalContentEntry
	18, // 3: Cratis.Chronicle.Contracts.Observation.Reducers.Causation.Occurred:type_name -> Cratis.Chronicle.Contracts.Observation.Reducers.SerializableDateTimeOffset
	20, // 4: Cratis.Chronicle.Contracts.Observation.Reducers.Causation.Properties:type_name -> Cratis.Chronicle.Contracts.Observation.Reducers.Causation.PropertiesEntry
	7,  // 5: Cratis.Chronicle.Contracts.Observation.Reducers.EventContext.EventType:type_name -> Cratis.Chronicle.Contracts.Observation.Reducers.EventType
	18, // 6: Cratis.Chronicle.Contracts.Observation.Reducers.EventContext.Occurred:type_name -> Cratis.Chronicle.Contracts.Observation.Reducers.SerializableDateTimeOffset
	21, // 7: Cratis.Chronicle.Contracts.Observation.Reducers.EventContext.CorrelationId:type_name -> bcl.Guid
	4,  // 8: Cratis.Chronicle.Contracts.Observation.Reducers.EventContext.Causation:type_name -> Cratis.Chronicle.Contracts.Observation.Reducers.Causation
	9,  // 9: Cratis.Chronicle.Contracts.Observation.Reducers.EventContext.CausedBy:type_name -> Cratis.Chronicle.Contracts.Observation.Reducers.Identity
	0,  // 10: Cratis.Chronicle.Contracts.Observation.Reducers.EventContext.ObservationState:type_name -> Cratis.Chronicle.Contracts.Observation.Reducers.EventObservationState
	10, // 11: Cratis.Chronicle.Contracts.Observation.Reducers.EventContext.NamedTags:type_name -> Cratis.Chronicle.Contracts.Observation.Reducers.NamedTag
	9,  // 12: Cratis.Chronicle.Contracts.Observation.Reducers.EventRevision.CausedBy:type_name -> Cratis.Chronicle.Contracts.Observation.Reducers.Identity
	18, // 13: Cratis.Chronicle.Contracts.Observation.Reducers.EventRevision.Occurred:type_name -> Cratis.Chronicle.Contracts.Observation.Reducers.SerializableDateTimeOffset
	7,  // 14: Cratis.Chronicle.Contracts.Observation.Reducers.EventTypeWithKeyExpression.EventType:type_name -> Cratis.Chronicle.Contracts.Observation.Reducers.EventType
	9,  // 15: Cratis.Chronicle.Contracts.Observation.Reducers.Identity.OnBehalfOf:type_name -> Cratis.Chronicle.Contracts.Observation.Reducers.Identity
	17, // 16: Cratis.Chronicle.Contracts.Observation.Reducers.OneOf_RegisterReducer_ReducerResult.Value0:type_name -> Cratis.Chronicle.Contracts.Observation.Reducers.RegisterReducer
	16, // 17: Cratis.Chronicle.Contracts.Observation.Reducers.OneOf_RegisterReducer_ReducerResult.Value1:type_name -> Cratis.Chronicle.Contracts.Observation.Reducers.ReducerResult
	3,  // 18: Cratis.Chronicle.Contracts.Observation.Reducers.ReduceOperationMessage.Events:type_name -> Cratis.Chronicle.Contracts.Observation.Reducers.AppendedEvent
	2,  // 19: Cratis.Chronicle.Contracts.Observation.Reducers.ReduceOperationMessage.ReplayState:type_name -> Cratis.Chronicle.Contracts.Observation.Reducers.ReplayState
	8,  // 20: Cratis.Chronicle.Contracts.Observation.Reducers.ReducerDefinition.EventTypes:type_name -> Cratis.Chronicle.Contracts.Observation.Reducers.EventTypeWithKeyExpression
	11, // 21: Cratis.Chronicle.Contracts.Observation.Reducers.ReducerDefinition.Filters:type_name -> Cratis.Chronicle.Contracts.Observation.Reducers.ObserverFilters
	12, // 22: Cratis.Chronicle.Contracts.Observation.Reducers.ReducerMessage.Content:type_name -> Cratis.Chronicle.Contracts.Observation.Reducers.OneOf_RegisterReducer_ReducerResult
	1,  // 23: Cratis.Chronicle.Contracts.Observation.Reducers.ReducerResult.State:type_name -> Cratis.Chronicle.Contracts.Observation.Reducers.ObservationState
	14, // 24: Cratis.Chronicle.Contracts.Observation.Reducers.RegisterReducer.Reducer:type_name -> Cratis.Chronicle.Contracts.Observation.Reducers.ReducerDefinition
	15, // 25: Cratis.Chronicle.Contracts.Observation.Reducers.Reducers.Observe:input_type -> Cratis.Chronicle.Contracts.Observation.Reducers.ReducerMessage
	13, // 26: Cratis.Chronicle.Contracts.Observation.Reducers.Reducers.Observe:output_type -> Cratis.Chronicle.Contracts.Observation.Reducers.ReduceOperationMessage
	26, // [26:27] is the sub-list for method output_type
	25, // [25:26] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_observation_reducers_proto_init() }
func file_observation_reducers_proto_init() {
	if File_observation_reducers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_observation_reducers_proto_rawDesc), len(file_observation_reducers_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_observation_reducers_proto_goTypes,
		DependencyIndexes: file_observation_reducers_proto_depIdxs,
		EnumInfos:         file_observation_reducers_proto_enumTypes,
		MessageInfos:      file_observation_reducers_proto_msgTypes,
	}.Build()
	File_observation_reducers_proto = out.File
	file_observation_reducers_proto_goTypes = nil
	file_observation_reducers_proto_depIdxs = nil
}
