// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: observation_reducers.proto

package reducers

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Reducers_Observe_FullMethodName = "/Cratis.Chronicle.Contracts.Observation.Reducers.Reducers/Observe"
)

// ReducersClient is the client API for Reducers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReducersClient interface {
	Observe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReducerMessage, ReduceOperationMessage], error)
}

type reducersClient struct {
	cc grpc.ClientConnInterface
}

func NewReducersClient(cc grpc.ClientConnInterface) ReducersClient {
	return &reducersClient{cc}
}

func (c *reducersClient) Observe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReducerMessage, ReduceOperationMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Reducers_ServiceDesc.Streams[0], Reducers_Observe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReducerMessage, ReduceOperationMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Reducers_ObserveClient = grpc.BidiStreamingClient[ReducerMessage, ReduceOperationMessage]

// ReducersServer is the server API for Reducers service.
// All implementations must embed UnimplementedReducersServer
// for forward compatibility.
type ReducersServer interface {
	Observe(grpc.BidiStreamingServer[ReducerMessage, ReduceOperationMessage]) error
	mustEmbedUnimplementedReducersServer()
}

// UnimplementedReducersServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReducersServer struct{}

func (UnimplementedReducersServer) Observe(grpc.BidiStreamingServer[ReducerMessage, ReduceOperationMessage]) error {
	return status.Error(codes.Unimplemented, "method Observe not implemented")
}
func (UnimplementedReducersServer) mustEmbedUnimplementedReducersServer() {}
func (UnimplementedReducersServer) testEmbeddedByValue()                  {}

// UnsafeReducersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReducersServer will
// result in compilation errors.
type UnsafeReducersServer interface {
	mustEmbedUnimplementedReducersServer()
}

func RegisterReducersServer(s grpc.ServiceRegistrar, srv ReducersServer) {
	// If the following call panics, it indicates UnimplementedReducersServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Reducers_ServiceDesc, srv)
}

func _Reducers_Observe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReducersServer).Observe(&grpc.GenericServerStream[ReducerMessage, ReduceOperationMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Reducers_ObserveServer = grpc.BidiStreamingServer[ReducerMessage, ReduceOperationMessage]

// Reducers_ServiceDesc is the grpc.ServiceDesc for Reducers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Reducers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Cratis.Chronicle.Contracts.Observation.Reducers.Reducers",
	HandlerType: (*ReducersServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Observe",
			Handler:       _Reducers_Observe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "observation_reducers.proto",
}
